import type { KnotCharacter } from './types';

export const KNOT_HOP_TITLE = 'Knot Hop';

export const STORAGE_KEYS = {
  best: 'knothop_spiral_best_v3',
  gemsLegacy: 'rachos-fun-knothop-gems',
  walletGold: 'rachos-fun-knothop-gold',
  walletGreen: 'rachos-fun-knothop-green',
  walletPurple: 'rachos-fun-knothop-purple',
  unlockedCharacters: 'rachos-fun-knothop-unlocked-characters',
  selectedCharacter: 'rachos-fun-knothop-selected-character',
  unlockedBallsLegacy: 'rachos-fun-knothop-unlocked-balls',
  selectedBallLegacy: 'rachos-fun-knothop-selected-ball',
};

export const OBSTACLE_COLORS = {
  blackCore: '#060606',
  blackFlash: '#3f1a1a',
  redCore: '#C1121F',
  redFlash: '#FF8B95',
  rustCore: '#8B3F1E',
  rustFlash: '#E8A26B',
};

export const COLLECTIBLE_COLORS = {
  goldA: '#FFD326',
  goldB: '#FFF3A3',
  greenA: '#3BFF71',
  greenB: '#B9FFD0',
  purpleA: '#A85CFF',
  purpleB: '#E4C7FF',
};

export const CHARACTER_MODELS: KnotCharacter[] = [
  {
    id: 'flux-core',
    name: 'Flux Core',
    model: 'core',
    primary: '#f3fbff',
    secondary: '#9deeff',
    emissive: '#59d6ff',
    roughness: 0.1,
    metalness: 0.28,
    cost: { gold: 0, green: 0, purple: 0 },
    description: 'Baseline knot runner.',
  },
  {
    id: 'ember-spike',
    name: 'Ember Spike',
    model: 'spike',
    primary: '#ffb089',
    secondary: '#ff6a42',
    emissive: '#ff7a5a',
    roughness: 0.2,
    metalness: 0.24,
    cost: { gold: 40, green: 0, purple: 0 },
    description: 'A sharp, aggressive spear profile.',
  },
  {
    id: 'verdant-loop',
    name: 'Verdant Loop',
    model: 'ringed',
    primary: '#9fffd0',
    secondary: '#2ddf8f',
    emissive: '#41ff93',
    roughness: 0.22,
    metalness: 0.2,
    cost: { gold: 55, green: 0, purple: 0 },
    description: 'Layered ring shell with a bright core.',
  },
  {
    id: 'rust-hopper',
    name: 'Rust Hopper',
    model: 'poly',
    primary: '#f0b194',
    secondary: '#c66b43',
    emissive: '#ea8a5e',
    roughness: 0.3,
    metalness: 0.18,
    cost: { gold: 80, green: 4, purple: 0 },
    description: 'Chunky poly runner with hard planes.',
  },
  {
    id: 'violet-fracta',
    name: 'Violet Fracta',
    model: 'fractal',
    primary: '#d2bcff',
    secondary: '#9b67ff',
    emissive: '#b987ff',
    roughness: 0.18,
    metalness: 0.26,
    cost: { gold: 95, green: 6, purple: 0 },
    description: 'Fractal bloom with recursive satellites.',
  },
  {
    id: 'supernova-shell',
    name: 'Supernova Shell',
    model: 'supershape',
    primary: '#ffc6dd',
    secondary: '#ff8ea8',
    emissive: '#ff6f95',
    roughness: 0.16,
    metalness: 0.25,
    cost: { gold: 110, green: 10, purple: 0 },
    description: 'Super-shape shell with compressed poles.',
  },
  {
    id: 'knot-sage',
    name: 'Knot Sage',
    model: 'knot',
    primary: '#a5f3ff',
    secondary: '#60d7ff',
    emissive: '#48beff',
    roughness: 0.12,
    metalness: 0.3,
    cost: { gold: 130, green: 12, purple: 0 },
    description: 'Twin torus-knot form built for flow.',
  },
  {
    id: 'void-capsule',
    name: 'Void Capsule',
    model: 'capsule',
    primary: '#e7e9ff',
    secondary: '#9ea8ff',
    emissive: '#7d93ff',
    roughness: 0.2,
    metalness: 0.34,
    cost: { gold: 90, green: 12, purple: 1 },
    description: 'A sleek capsule with edge stabilizers.',
  },
  {
    id: 'eclipse-wing',
    name: 'Eclipse Wing',
    model: 'winged',
    primary: '#ffe0b5',
    secondary: '#f29b4e',
    emissive: '#ffba66',
    roughness: 0.2,
    metalness: 0.28,
    cost: { gold: 120, green: 15, purple: 2 },
    description: 'Wide wing profile for confident lines.',
  },
  {
    id: 'helix-drone',
    name: 'Helix Drone',
    model: 'helix',
    primary: '#d2ffd4',
    secondary: '#6fff86',
    emissive: '#62ff9f',
    roughness: 0.2,
    metalness: 0.22,
    cost: { gold: 140, green: 18, purple: 2 },
    description: 'Double-helix silhouette that spins fast.',
  },
  {
    id: 'iron-aster',
    name: 'Iron Aster',
    model: 'asteroid',
    primary: '#d8d8de',
    secondary: '#8e8e9a',
    emissive: '#c3c3db',
    roughness: 0.36,
    metalness: 0.14,
    cost: { gold: 160, green: 22, purple: 3 },
    description: 'Dense asteroid-style shell with craters.',
  },
  {
    id: 'crownforge',
    name: 'Crownforge',
    model: 'crown',
    primary: '#ffe0aa',
    secondary: '#ffb954',
    emissive: '#ffca77',
    roughness: 0.18,
    metalness: 0.38,
    cost: { gold: 180, green: 24, purple: 3 },
    description: 'Crowned shell with radial spikes.',
  },
  {
    id: 'fractal-empress',
    name: 'Fractal Empress',
    model: 'fractal',
    primary: '#f0d4ff',
    secondary: '#cb8aff',
    emissive: '#d293ff',
    roughness: 0.16,
    metalness: 0.32,
    cost: { gold: 210, green: 30, purple: 4 },
    description: 'High-tier fractal lattice.',
  },
  {
    id: 'hyper-knot',
    name: 'Hyper Knot',
    model: 'knot',
    primary: '#ccf9ff',
    secondary: '#6ce9ff',
    emissive: '#4ed9ff',
    roughness: 0.1,
    metalness: 0.36,
    cost: { gold: 235, green: 36, purple: 6 },
    description: 'A super-tight knot engine.',
  },
  {
    id: 'royal-super',
    name: 'Royal Super',
    model: 'supershape',
    primary: '#ffe4f8',
    secondary: '#ff9bd9',
    emissive: '#ff7fc7',
    roughness: 0.14,
    metalness: 0.34,
    cost: { gold: 260, green: 42, purple: 8 },
    description: 'Signature supershape with layered shell.',
  },
  {
    id: 'mythic-orbit',
    name: 'Mythic Orbit',
    model: 'core',
    primary: '#fff4c4',
    secondary: '#e9b44f',
    emissive: '#ffd35f',
    roughness: 0.12,
    metalness: 0.42,
    cost: { gold: 300, green: 48, purple: 10 },
    description: 'Mythic final-tier orbit core.',
  },
];

export const DEFAULT_CHARACTER = CHARACTER_MODELS[0].id;
