export const EMAILJS_SERVICE_ID =
  process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || 'RachoDevs';

export const EMAILJS_TEMPLATE_ID =
  process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID || 'RachoDevs';

export const EMAILJS_PUBLIC_KEY =
  process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || 'asi1IXWXVQKV4AGlS';

export const EMAILJS_BUG_TEMPLATE_ID =
  process.env.NEXT_PUBLIC_EMAILJS_BUG_TEMPLATE_ID || EMAILJS_TEMPLATE_ID;
