/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: orca_studio (https://sketchfab.com/orca_studio)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ugly-face-monster-8c2e666b04f04bcab1e86a2dd3d77ecc
title: ugly face  monster
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/alien.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/alien.glb')
