/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nikita Borovkov (https://sketchfab.com/NickBorovik)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/arcade-machine-444b485039474d818aa661ca13ff4dff
title: Arcade Machine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/arcade.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['������������_������_19_GLASS_0'].geometry}
        material={materials.PaletteMaterial001}
        position={[0.64, 110.48, -13.61]}
        rotation={[-0.18, 0, 0]}
      />
      <mesh
        geometry={nodes['������������_��������������_5_NEON_0'].geometry}
        material={materials.PaletteMaterial002}
        position={[-12.5, 30.88, 15.61]}
      />
      <mesh
        geometry={nodes['������������_������_7_SCREEN_0'].geometry}
        material={materials.PaletteMaterial003}
        position={[0.64, 110.38, -14.16]}
        rotation={[-0.18, 0, 0]}
      />
      <mesh
        geometry={nodes['������������_������_5_ARCADE_0'].geometry}
        material={materials.ARCADE}
        position={[0.62, 146.59, 8.96]}
      />
    </group>
  )
}

useGLTF.preload('/arcade.glb')
