/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/button1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Torus015.geometry}
        material={materials['Material.037']}
        position={[0.15, -6.95, -0.59]}
        scale={[0.75, 1, 1.12]}
      />
      <mesh
        geometry={nodes.Torus016.geometry}
        material={materials['Material.038']}
        position={[0.15, -6.95, -0.59]}
        scale={[0.75, 1, 1.12]}
      />
      <mesh
        geometry={nodes.Object_9270.geometry}
        material={materials['UV_switch.009']}
        position={[0.15, -7.07, -0.65]}
        rotation={[-Math.PI, 0.04, -Math.PI]}
        scale={[0.79, 0.75, 1]}
      />
    </group>
  )
}

useGLTF.preload('/button1.glb')
