/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/button4.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Torus019.geometry}
        material={materials['Material.041']}
        position={[-5.62, -6.95, 2.09]}
        rotation={[0, -1.23, 0]}
        scale={[0.75, 1, 1.12]}
      />
      <mesh
        geometry={nodes.Object_9359.geometry}
        material={materials['UV_switch.012']}
        position={[-5.59, -7.06, 2.03]}
        rotation={[-Math.PI, 1.2, -Math.PI]}
        scale={[1.03, 0.84, 1.01]}
      />
    </group>
  )
}

useGLTF.preload('/button4.glb')
