/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/button3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Torus018.geometry}
        material={materials['Material.040']}
        position={[0.12, -6.95, 9.92]}
        scale={[0.75, 1, 1.12]}
      />
      <mesh
        geometry={nodes.Object_9330.geometry}
        material={materials['UV_switch.011']}
        position={[0.13, -7.06, 9.91]}
        rotation={[-Math.PI, 0.03, -Math.PI]}
        scale={[0.96, 0.84, 1.07]}
      />
    </group>
  )
}

useGLTF.preload('/button3.glb')
