/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/crystalHeart.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Heart.geometry} material={materials['02_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/crystalHeart.glb')
