/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/CthuluMeBit.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.HeadBack001.geometry}
        material={nodes.HeadBack001.material}
        position={[0.11, -0.01, -0.05]}
        rotation={[0.03, 0.01, 3.13]}
        scale={[0.26, 0.02, 0.23]}
      />
      <mesh geometry={nodes.Curve044.geometry} material={nodes.Curve044.material} />
      <mesh geometry={nodes.Curve048.geometry} material={nodes.Curve048.material} />
      <mesh geometry={nodes.Curve049.geometry} material={nodes.Curve049.material} />
      <mesh geometry={nodes.Curve014.geometry} material={nodes.Curve014.material} />
      <mesh geometry={nodes.Curve017.geometry} material={nodes.Curve017.material} />
      <mesh geometry={nodes.Curve034.geometry} material={nodes.Curve034.material} />
      <mesh geometry={nodes.Curve037.geometry} material={nodes.Curve037.material} />
    </group>
  )
}

useGLTF.preload('/CthuluMeBit.glb')
