/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/EmptyDome.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Wireframe001.geometry}
        material={materials.PaletteMaterial001}
        position={[-5.26, 0, -13.2]}
        scale={[14.9, 8.51, 13.9]}
      />
      <mesh
        name="Torus025"
        geometry={nodes.Torus025.geometry}
        material={materials['Material.048']}
        position={[0.52, 11.99, 1.37]}
        scale={[12.47, 21.75, 11.63]}
      />
      <mesh
        name="Torus026"
        geometry={nodes.Torus026.geometry}
        material={materials['Material.049']}
        position={[0.58, -0.76, 1.22]}
        rotation={[0, 0, -0.21]}
        scale={[20.29, 9.74, 18.98]}
      />
      <mesh
        name="Torus027"
        geometry={nodes.Torus027.geometry}
        material={materials['Material.050']}
        position={[0.45, -3.25, 1.36]}
        rotation={[-0.08, 0, 0]}
        scale={[20.35, 8.7, 18.98]}
      />
      <mesh
        name="Torus028"
        geometry={nodes.Torus028.geometry}
        material={materials['Material.051']}
        position={[0.14, -1.58, 1.58]}
        rotation={[0, 0, 0.08]}
        scale={[3, 1.83, 2.78]}
      />
      <mesh
        name="Torus029"
        geometry={nodes.Torus029.geometry}
        material={materials['Material.052']}
        position={[0.32, 19.68, 1.68]}
        scale={[7.89, 21.75, 7.36]}
      />
      <group position={[-5.26, -0.07, -13.2]} rotation={[Math.PI, -1.16, 0]} scale={[16.91, 8.82, 17.74]}>
        <mesh geometry={nodes.Icosphere006.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Icosphere006_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.PaletteMaterial004}
        position={[-5.26, 0, -13.2]}
        scale={[14.9, 8.51, 13.9]}
      />
      <mesh
        geometry={nodes.SignBackground001.geometry}
        material={materials.PaletteMaterial005}
        position={[-5.26, 0, -13.2]}
        scale={[10.36, 1.52, 1.34]}
      />
      <mesh
        geometry={nodes.path7001.geometry}
        material={nodes.path7001.material}
        position={[-5.26, 0, -10.61]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[62.6, 15.29, 97.05]}
      />
      <group name="Head" position={[0.54, 1.01, -14.85]} rotation={[0.02, 0, 1.57]} scale={[82.9, 3.56, 104.32]}>
        <mesh geometry={nodes.path1004.geometry} material={nodes.path1004.material} />
        <mesh geometry={nodes.path1004_1.geometry} material={nodes.path1004_1.material} />
        <mesh geometry={nodes.path1004_2.geometry} material={nodes.path1004_2.material} />
        <mesh geometry={nodes.path1004_3.geometry} material={nodes.path1004_3.material} />
        <mesh geometry={nodes.path1004_4.geometry} material={nodes.path1004_4.material} />
        <mesh geometry={nodes.path1004_5.geometry} material={nodes.path1004_5.material} />
        <mesh geometry={nodes.path1004_6.geometry} material={nodes.path1004_6.material} />
        <mesh geometry={nodes.path1004_7.geometry} material={nodes.path1004_7.material} />
        <mesh geometry={nodes.path1004_8.geometry} material={nodes.path1004_8.material} />
        <mesh geometry={nodes.path1004_9.geometry} material={nodes.path1004_9.material} />
        <mesh geometry={nodes.path1004_10.geometry} material={nodes.path1004_10.material} />
        <mesh geometry={nodes.path1004_11.geometry} material={nodes.path1004_11.material} />
      </group>
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.069']}
        position={[0.5, -7.11, 1.53]}
        rotation={[0, -0.36, 0]}
        scale={[1.03, 2.84, 0.97]}
      />
    </group>
  )
}

useGLTF.preload('/EmptyDome.glb')
