/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/PaddleHand.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <primitive object={nodes.Bone003} />
      <primitive object={nodes.Bone006} />
      <primitive object={nodes.Bone010} />
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0.geometry}
        material={materials.M_PingPongPaddle}
        position={[-0.37, -0.93, 6.16]}
        rotation={[-1.57, 0, -0.05]}
        scale={[151.73, 151.73, 143.51]}
      />
      <skinnedMesh
        geometry={nodes.arm.geometry}
        material={materials.glove}
        skeleton={nodes.arm.skeleton}
        rotation={[1.88, -0.35, 2.32]}
        scale={[2.97, 2.97, 2.97]}
      />
    </group>
  )
}

useGLTF.preload('/PaddleHand.glb')
