/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Paddle.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0.geometry}
        material={materials.M_PingPongPaddle}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/Paddle.glb')
