/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/RachoMonitors.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.44, 0, -0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.16, 0.79, -1.97]} rotation={[-0.54, 0.93, -1.12]} scale={0.5}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          </group>
          <group position={[-2.79, 0.27, 1.82]} rotation={[-1.44, 1.22, 1.43]} scale={0.5}>
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
          </group>
          <group position={[-5.6, 4.62, -0.03]} rotation={[-1.96, 0.16, 1.2]} scale={0.5}>
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
          </group>
          <group position={[0.63, 0, -3]} rotation={[0, 0.17, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
          </group>
          <group position={[-2.36, 0.32, -2.02]} rotation={[0, 0.53, -Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
          </group>
          <group position={[-3.53, 0, 0.59]} rotation={[Math.PI, -1.09, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
          </group>
          <group position={[-3.79, 0, 1.66]} rotation={[-Math.PI, -1.39, 0]} scale={[-1.52, -1.52, -1.52]}>
            <mesh geometry={nodes.Object_58.geometry} material={nodes.Object_58.material} />
          </group>
          <group position={[-3.69, 0, 2.59]} rotation={[0, -1.57, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_62.geometry} material={nodes.Object_62.material} />
          </group>
          <group position={[-5.36, 2.18, 0.81]} rotation={[0, 0.77, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_64.geometry} material={nodes.Object_64.material} />
          </group>
          <group position={[-5.56, 1.57, 0.69]} rotation={[0, 1.17, -Math.PI / 2]} scale={[-1.52, -1.52, -1.52]}>
            <mesh geometry={nodes.Object_68.geometry} material={nodes.Object_68.material} />
          </group>
          <group position={[-5.47, 2.79, 0.74]} rotation={[Math.PI, -1.16, Math.PI / 2]} scale={1.52}>
            <mesh geometry={nodes.Object_72.geometry} material={nodes.Object_72.material} />
          </group>
          <group position={[-5.29, 3.41, 0.89]} rotation={[Math.PI, -0.76, -Math.PI / 2]} scale={[-1.52, -1.52, -1.52]}>
            <mesh geometry={nodes.Object_76.geometry} material={nodes.Object_76.material} />
          </group>
          <group position={[-5.28, 0, -2.33]} rotation={[0, 0.75, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_80.geometry} material={nodes.Object_80.material} />
          </group>
          <group position={[-5.49, 0, -1.38]} rotation={[Math.PI, -0.99, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_84.geometry} material={nodes.Object_84.material} />
          </group>
          <group position={[-3.01, 0, -3.79]} rotation={[0, 0.6, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_88.geometry} material={nodes.Object_88.material} />
          </group>
          <group position={[-2.08, 0, -4.32]} rotation={[Math.PI, -0.6, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_92.geometry} material={nodes.Object_92.material} />
          </group>
          <group position={[-1.02, 0, -4.49]} rotation={[0, 0.31, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_94.geometry} material={nodes.Object_94.material} />
          </group>
          <group position={[-5.31, 1.83, -1.41]} rotation={[0, 1.06, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_98.geometry} material={nodes.Object_98.material} />
          </group>
          <group position={[-4.18, 1.83, -3.06]} rotation={[-Math.PI, -0.46, -Math.PI / 2]} scale={1.52}>
            <mesh geometry={nodes.Object_100.geometry} material={nodes.Object_100.material} />
          </group>
          <group position={[-1.76, 1.83, -3.6]} rotation={[0, -1.16, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_102.geometry} material={nodes.Object_102.material} />
          </group>
          <group position={[-0.25, 1.83, -5.54]} rotation={[0, 1.55, 1.57]} scale={1.52}>
            <mesh geometry={nodes.Object_104.geometry} material={nodes.Object_104.material} />
          </group>
          <group position={[-5.28, 2.14, -2.33]} rotation={[Math.PI, -0.75, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_108.geometry} material={nodes.Object_108.material} />
          </group>
          <group position={[-5.49, 2.14, -1.38]} rotation={[0, 0.99, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_112.geometry} material={nodes.Object_112.material} />
          </group>
          <group position={[-3.01, 2.14, -3.79]} rotation={[Math.PI, -0.6, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_116.geometry} material={nodes.Object_116.material} />
          </group>
          <group position={[-2.08, 2.14, -4.32]} rotation={[0, 0.6, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_120.geometry} material={nodes.Object_120.material} />
          </group>
          <group position={[-1.02, 2.14, -4.49]} rotation={[Math.PI, -0.31, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_122.geometry} material={nodes.Object_122.material} />
          </group>
          <group position={[-5.31, 3.98, -1.41]} rotation={[0, 1.06, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_126.geometry} material={nodes.Object_126.material} />
          </group>
          <group position={[-4.18, 3.98, -3.06]} rotation={[-Math.PI, -0.46, -Math.PI / 2]} scale={1.52}>
            <mesh geometry={nodes.Object_128.geometry} material={nodes.Object_128.material} />
          </group>
          <group position={[-1.17, 3.98, -4.45]} rotation={[0, 0.17, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_130.geometry} material={nodes.Object_130.material} />
          </group>
          <group position={[-0.94, 3.98, -4.66]} rotation={[Math.PI, 0.02, -Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_132.geometry} material={nodes.Object_132.material} />
          </group>
          <group position={[5.53, 2.18, 0.17]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_140.geometry} material={nodes.Object_140.material} />
          </group>
          <group position={[5.74, 1.57, 0.05]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_144.geometry} material={nodes.Object_144.material} />
          </group>
          <group position={[5.65, 2.79, 0.11]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_148.geometry} material={nodes.Object_148.material} />
          </group>
          <group position={[5.46, 3.41, 0.26]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_152.geometry} material={nodes.Object_152.material} />
          </group>
          <group position={[4.86, 0, -2.54]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_156.geometry} material={nodes.Object_156.material} />
          </group>
          <group position={[5.06, 0, -1.6]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_160.geometry} material={nodes.Object_160.material} />
          </group>
          <group position={[2.59, 0, -4]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_164.geometry} material={nodes.Object_164.material} />
          </group>
          <group position={[1.66, 0, -4.54]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_168.geometry} material={nodes.Object_168.material} />
          </group>
          <group position={[0.59, 0, -4.7]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_170.geometry} material={nodes.Object_170.material} />
          </group>
          <group position={[4.89, 1.83, -1.62]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_172.geometry} material={nodes.Object_172.material} />
          </group>
          <group position={[3.75, 1.83, -3.28]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_174.geometry} material={nodes.Object_174.material} />
          </group>
          <group position={[1.33, 1.83, -3.82]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_176.geometry} material={nodes.Object_176.material} />
          </group>
          <group position={[4.86, 2.14, -2.54]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_180.geometry} material={nodes.Object_180.material} />
          </group>
          <group position={[5.06, 2.14, -1.6]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_184.geometry} material={nodes.Object_184.material} />
          </group>
          <group position={[2.59, 2.14, -4]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_188.geometry} material={nodes.Object_188.material} />
          </group>
          <group position={[1.66, 2.14, -4.54]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_192.geometry} material={nodes.Object_192.material} />
          </group>
          <group position={[0.59, 2.14, -4.7]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_194.geometry} material={nodes.Object_194.material} />
          </group>
          <group position={[4.89, 3.98, -1.62]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_196.geometry} material={nodes.Object_196.material} />
          </group>
          <group position={[3.75, 3.98, -3.28]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_198.geometry} material={nodes.Object_198.material} />
          </group>
          <group position={[0.75, 3.98, -4.66]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_200.geometry} material={nodes.Object_200.material} />
          </group>
          <group position={[-0.19, 0, -2.96]} rotation={[0, -0.06, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
          </group>
          <group position={[-2.9, 0.3, -1.47]} rotation={[Math.PI, -1.35, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
          </group>
          <group position={[-5.61, 0.94, 0.82]} rotation={[0, 1.32, 1.57]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_66.geometry} material={nodes.Object_66.material} />
          </group>
          <group position={[-5.26, 0.32, 1.01]} rotation={[0, 0.79, -Math.PI / 2]} scale={[-1.52, -1.52, -1.52]}>
            <mesh geometry={nodes.Object_70.geometry} material={nodes.Object_70.material} />
          </group>
          <group position={[-5.39, 4.03, 0.99]} rotation={[Math.PI, -0.61, Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_74.geometry} material={nodes.Object_74.material} />
          </group>
          <group position={[-5.7, 4.66, 0.72]} rotation={[Math.PI, -1.13, -Math.PI / 2]} scale={[-1.52, -1.52, -1.52]}>
            <mesh geometry={nodes.Object_78.geometry} material={nodes.Object_78.material} />
          </group>
          <group position={[-5.95, 0, -0.64]} rotation={[0, 0.95, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_82.geometry} material={nodes.Object_82.material} />
          </group>
          <group position={[-4.48, 0, -2.75]} rotation={[Math.PI, -0.57, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_86.geometry} material={nodes.Object_86.material} />
          </group>
          <group position={[-3.72, 0, -2.89]} rotation={[0, 0.64, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_90.geometry} material={nodes.Object_90.material} />
          </group>
          <group position={[-0.08, 0, -5.03]} rotation={[Math.PI, -0.04, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_96.geometry} material={nodes.Object_96.material} />
          </group>
          <group position={[-4.19, 1.84, -2.77]} rotation={[Math.PI, -0.66, -Math.PI / 2]} scale={-1.52}>
            <mesh geometry={nodes.Object_106.geometry} material={nodes.Object_106.material} />
          </group>
          <group position={[-5.95, 2.14, -0.64]} rotation={[Math.PI, -0.95, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_110.geometry} material={nodes.Object_110.material} />
          </group>
          <group position={[-4.48, 2.14, -2.75]} rotation={[0, 0.57, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_114.geometry} material={nodes.Object_114.material} />
          </group>
          <group position={[-3.73, 2.14, -3.1]} rotation={[Math.PI, -0.64, Math.PI]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_118.geometry} material={nodes.Object_118.material} />
          </group>
          <group position={[-0.08, 2.14, -5.03]} rotation={[0, 0.04, 0]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_124.geometry} material={nodes.Object_124.material} />
          </group>
          <group position={[-4.19, 3.98, -2.77]} rotation={[Math.PI, -0.66, -Math.PI / 2]} scale={-1.52}>
            <mesh geometry={nodes.Object_134.geometry} material={nodes.Object_134.material} />
          </group>
          <group position={[5.79, 0.94, 0.18]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_142.geometry} material={nodes.Object_142.material} />
          </group>
          <group position={[5.43, 0.32, 0.37]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_146.geometry} material={nodes.Object_146.material} />
          </group>
          <group position={[5.56, 4.03, 0.35]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_150.geometry} material={nodes.Object_150.material} />
          </group>
          <group position={[5.87, 4.66, 0.08]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_154.geometry} material={nodes.Object_154.material} />
          </group>
          <group position={[5.53, 0, -0.85]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_158.geometry} material={nodes.Object_158.material} />
          </group>
          <group position={[4.05, 0, -2.96]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_162.geometry} material={nodes.Object_162.material} />
          </group>
          <group position={[3.29, 0, -3.1]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_166.geometry} material={nodes.Object_166.material} />
          </group>
          <group position={[3.77, 1.84, -2.98]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_178.geometry} material={nodes.Object_178.material} />
          </group>
          <group position={[5.53, 2.14, -0.85]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_182.geometry} material={nodes.Object_182.material} />
          </group>
          <group position={[4.05, 2.14, -2.96]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_186.geometry} material={nodes.Object_186.material} />
          </group>
          <group position={[3.3, 2.14, -3.31]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_190.geometry} material={nodes.Object_190.material} />
          </group>
          <group position={[3.77, 3.98, -2.98]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_202.geometry} material={nodes.Object_202.material} />
          </group>
          <group position={[1.89, 0, -1.94]} rotation={[0, -0.44, 0]} scale={[1.5, 1, 1.5]}>
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
          </group>
          <group position={[-1.1, 4.29, -4.43]} rotation={[0, 0.36, 0]}>
            <mesh geometry={nodes.Object_136.geometry} material={nodes.Object_136.material} />
          </group>
          <group position={[-5.25, 4.29, -1.47]} rotation={[0, 1.25, 0]}>
            <mesh geometry={nodes.Object_138.geometry} material={nodes.Object_138.material} />
          </group>
          <group position={[3.2, 4.29, -3.09]} rotation={[-Math.PI, 0.56, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_204.geometry} material={nodes.Object_204.material} />
          </group>
          <group position={[0.27, 1.53, -2.61]}>
            <mesh
              geometry={nodes.Object_206.geometry}
              material={nodes.Object_206.material}
              position={[0, 0.39, 0]}
              scale={[1.84, 2.65, 0.32]}
            />
            <mesh
              geometry={nodes.Object_207.geometry}
              material={nodes.Object_207.material}
              position={[0, 0, 0.02]}
              scale={[2.16, 3.31, 0.32]}
            />
          </group>
          <group position={[-3.9, 4.29, -2.64]} rotation={[0, 0.54, 0]}>
            <mesh
              geometry={nodes.Object_224.geometry}
              material={nodes.Object_224.material}
              position={[-3.76, 0.67, 2.54]}
              rotation={[0, 0.31, 0]}
            />
            <mesh
              geometry={nodes.Object_225.geometry}
              material={nodes.Object_225.material}
              position={[-3.76, 0.67, 2.54]}
              rotation={[0, 0.31, 0]}
            />
          </group>
          <group position={[0.96, 4.28, -4.2]} rotation={[0, -0.65, 0]}>
            <mesh
              geometry={nodes.Object_227.geometry}
              material={nodes.Object_227.material}
              position={[-2.38, 0.27, 1.78]}
              rotation={[0, 0.36, 0]}
            />
            <mesh
              geometry={nodes.Object_228.geometry}
              material={nodes.Object_228.material}
              position={[-2.38, 0.27, 1.78]}
              rotation={[0, 0.36, 0]}
            />
          </group>
          <group position={[4.68, 4.29, -1.56]} rotation={[0, -Math.PI / 3, 0]}>
            <mesh
              geometry={nodes.Object_230.geometry}
              material={nodes.Object_230.material}
              position={[2.99, 0.76, 0.25]}
              rotation={[0, -0.11, 0]}
            />
            <mesh
              geometry={nodes.Object_231.geometry}
              material={nodes.Object_231.material}
              position={[2.99, 0.76, 0.25]}
              rotation={[0, -0.11, 0]}
            />
          </group>
        </group>
      </group>
      <group position={[1.81, -5.9, 1.82]} rotation={[-Math.PI / 2, 0, -0.99]} scale={[1.29, 1.46, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.27, 1.53, -2.61]}>
            <mesh
              geometry={nodes.Object_206001.geometry}
              material={materials['Texture.001']}
              position={[-0.05, 6.3, -0.28]}
              scale={[2.26, 4.45, 0.31]}
            />
            <mesh
              geometry={nodes.Object_207001.geometry}
              material={materials['Screen.001']}
              position={[-0.05, 5.65, -0.25]}
              scale={[2.66, 5.53, 0.31]}
            />
          </group>
        </group>
      </group>
      <group position={[-2.68, -4.95, 3.71]} rotation={[-Math.PI / 2, 0, 1.08]} scale={[1.25, 1.48, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.27, 1.53, -2.61]}>
            <mesh
              geometry={nodes.Object_206002.geometry}
              material={materials['Texture.002']}
              position={[0.05, 5.22, -0.49]}
              rotation={[0, 0.01, 0]}
              scale={[3.48, 2.22, 0.34]}
            />
            <mesh
              geometry={nodes.Object_207002.geometry}
              material={materials['Screen.002']}
              position={[0.05, 5, -0.47]}
              rotation={[0, 0.01, 0]}
              scale={[4.25, 2.61, 0.34]}
            />
          </group>
        </group>
      </group>
      <group position={[-0.98, 0.65, 0.53]} rotation={[-Math.PI / 2, 0, -0.45]} scale={[1.49, 1.23, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.36, 0.32, -2.02]} rotation={[0, 0.53, -Math.PI / 2]} scale={1.52}>
            <mesh geometry={nodes.Object_20001.geometry} material={materials['Texture.003']} />
          </group>
        </group>
      </group>
      <group position={[6.19, 0.34, -0.1]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.36, 0.32, -2.02]} rotation={[0, 0.53, -Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_20002.geometry} material={materials['Texture.004']} />
          </group>
        </group>
      </group>
      <group position={[-5.45, -4.47, -0.99]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.87, 4.66, 0.08]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_154001.geometry} material={materials['Texture.005']} />
          </group>
        </group>
      </group>
      <group position={[-4.26, -3.87, -0.62]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.87, 4.66, 0.08]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_154002.geometry} material={materials['Texture.006']} />
          </group>
        </group>
      </group>
      <group position={[2.45, 1.15, 2.56]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.89, 0, -1.94]} rotation={[0, -0.44, 0]} scale={[1.5, 1, 1.5]}>
            <mesh geometry={nodes.Object_38001.geometry} material={materials['Texture.007']} />
          </group>
        </group>
      </group>
      <group position={[8.88, -0.2, 3.62]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.36, 0.32, -2.02]} rotation={[0, 0.53, -Math.PI / 2]} scale={[1.52, 1.52, 1.52]}>
            <mesh geometry={nodes.Object_20003.geometry} material={materials['Texture.008']} />
          </group>
        </group>
      </group>
      <group position={[3.38, 0.43, 4.26]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.89, 0, -1.94]} rotation={[0, -0.44, 0]} scale={[1.5, 1, 1.5]}>
            <mesh geometry={nodes.Object_38002.geometry} material={materials['Texture.009']} />
          </group>
        </group>
      </group>
      <group position={[-2.8, -1.47, 2.06]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.74, 1.57, 0.05]} rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_144001.geometry} material={materials['Texture.010']} />
          </group>
        </group>
      </group>
      <group position={[6.5, 0.34, 0.34]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.96, 4.28, -4.2]} rotation={[0, -0.65, 0]}>
            <mesh
              geometry={nodes.Object_227001.geometry}
              material={materials['Texture.011']}
              position={[-2.61, 0.27, 1.84]}
              rotation={[0, -0.27, 0]}
            />
            <mesh
              geometry={nodes.Object_228001.geometry}
              material={materials['Screen.003']}
              position={[-2.61, 0.27, 1.84]}
              rotation={[0, -0.27, 0]}
            />
          </group>
        </group>
      </group>
      <group position={[4.6, -0.02, 0.3]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.1, 4.29, -4.43]} rotation={[0, 0.36, 0]}>
            <mesh geometry={nodes.Object_136001.geometry} material={materials['Texture.012']} />
          </group>
        </group>
      </group>
      <group position={[4.6, 0.27, 0.3]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.1, 4.29, -4.43]} rotation={[0, 0.36, 0]}>
            <mesh geometry={nodes.Object_136002.geometry} material={materials['Texture.013']} />
          </group>
        </group>
      </group>
      <group position={[-9.24, -0.01, -1.78]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.54, 1.12, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[3.2, 4.29, -3.09]} rotation={[-Math.PI, 0.56, 0]} scale={[-1, -1, -1]}>
            <mesh geometry={nodes.Object_204001.geometry} material={materials['Texture.014']} />
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[-1.07, 1.1, -2.51]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.47, 1.32, -2.52]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[2.3, 1.91, -1.33]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[3.33, 1.1, -0.91]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[7.08, 3.8, -0.14]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[2.54, 3.8, -4.16]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={nodes.Sphere006.material}
        position={[-4.06, 3.8, -3.92]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={nodes.Sphere007.material}
        position={[-7.7, 4.59, -2.06]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={nodes.Sphere008.material}
        position={[-5.12, 2.85, 1.31]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={nodes.Sphere009.material}
        position={[-2.3, 1.73, -1.7]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/RachoMonitors.glb')
