/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/UFOgames.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.94, -1.01, 0.12]} rotation={[1.57, 0, 0]} scale={[0.57, 0.94, 0.57]}>
        <group name="AlienOrange" position={[-2.65, 0.04, -1.47]} rotation={[0, 0, -Math.PI]} scale={[7.63, 1, 7.63]}>
          <mesh geometry={nodes.Curve391.geometry} material={nodes.Curve391.material} />
          <mesh geometry={nodes.Curve391_1.geometry} material={materials.PaletteMaterial002} />
          <mesh geometry={nodes.Curve391_2.geometry} material={nodes.Curve391_2.material} />
          <mesh geometry={nodes.Curve391_3.geometry} material={nodes.Curve391_3.material} />
        </group>
        <group name="AlienPurple" position={[-0.74, 0.01, -1.59]} rotation={[0, 0, -3.14]} scale={[7.63, 1, 7.63]}>
          <mesh geometry={nodes.Curve123.geometry} material={nodes.Curve123.material} />
          <mesh geometry={nodes.Curve123_1.geometry} material={nodes.Curve123_1.material} />
          <mesh geometry={nodes.Curve123_2.geometry} material={materials.PaletteMaterial003} />
          <mesh geometry={nodes.Curve123_3.geometry} material={nodes.Curve123_3.material} />
          <mesh geometry={nodes.Curve123_4.geometry} material={nodes.Curve123_4.material} />
          <mesh geometry={nodes.Curve123_5.geometry} material={nodes.Curve123_5.material} />
          <mesh geometry={nodes.Curve123_6.geometry} material={nodes.Curve123_6.material} />
          <mesh geometry={nodes.Curve123_7.geometry} material={nodes.Curve123_7.material} />
          <mesh geometry={nodes.Curve123_8.geometry} material={nodes.Curve123_8.material} />
          <mesh geometry={nodes.Curve123_9.geometry} material={nodes.Curve123_9.material} />
          <mesh geometry={nodes.Curve123_10.geometry} material={nodes.Curve123_10.material} />
          <mesh geometry={nodes.Curve123_11.geometry} material={nodes.Curve123_11.material} />
          <mesh geometry={nodes.Curve123_12.geometry} material={nodes.Curve123_12.material} />
          <mesh geometry={nodes.Curve123_13.geometry} material={nodes.Curve123_13.material} />
          <mesh geometry={nodes.Curve123_14.geometry} material={nodes.Curve123_14.material} />
          <mesh geometry={nodes.Curve123_15.geometry} material={nodes.Curve123_15.material} />
          <mesh geometry={nodes.Curve123_16.geometry} material={nodes.Curve123_16.material} />
          <mesh geometry={nodes.Curve123_17.geometry} material={nodes.Curve123_17.material} />
          <mesh geometry={nodes.Curve123_18.geometry} material={nodes.Curve123_18.material} />
          <mesh geometry={nodes.Curve123_19.geometry} material={nodes.Curve123_19.material} />
          <mesh geometry={nodes.Curve123_20.geometry} material={nodes.Curve123_20.material} />
          <mesh geometry={nodes.Curve123_21.geometry} material={nodes.Curve123_21.material} />
          <mesh geometry={nodes.Curve123_22.geometry} material={nodes.Curve123_22.material} />
          <mesh geometry={nodes.Curve123_23.geometry} material={nodes.Curve123_23.material} />
          <mesh geometry={nodes.Curve123_24.geometry} material={nodes.Curve123_24.material} />
          <mesh geometry={nodes.Curve123_25.geometry} material={nodes.Curve123_25.material} />
          <mesh geometry={nodes.Curve123_26.geometry} material={nodes.Curve123_26.material} />
          <mesh geometry={nodes.Curve123_27.geometry} material={nodes.Curve123_27.material} />
          <mesh geometry={nodes.Curve123_28.geometry} material={nodes.Curve123_28.material} />
          <mesh geometry={nodes.Curve123_29.geometry} material={nodes.Curve123_29.material} />
          <mesh geometry={nodes.Curve123_30.geometry} material={nodes.Curve123_30.material} />
          <mesh geometry={nodes.Curve123_31.geometry} material={nodes.Curve123_31.material} />
          <mesh geometry={nodes.Curve123_32.geometry} material={nodes.Curve123_32.material} />
        </group>
        <group name="AlienRLeft" position={[-1.66, -0.18, -2.16]} rotation={[1.57, 0, -3.14]} scale={[3, 0.11, 3]}>
          <mesh geometry={nodes.Curve063.geometry} material={nodes.Curve063.material} />
          <mesh geometry={nodes.Curve063_1.geometry} material={nodes.Curve063_1.material} />
          <mesh geometry={nodes.Curve063_2.geometry} material={nodes.Curve063_2.material} />
          <mesh geometry={nodes.Curve063_3.geometry} material={nodes.Curve063_3.material} />
        </group>
        <group name="AlienRMiddle" position={[-1.66, -0.18, -2.16]} rotation={[0, 0, Math.PI]} scale={[3, 0.11, 3]}>
          <mesh geometry={nodes.Curve011.geometry} material={nodes.Curve011.material} />
          <mesh geometry={nodes.Curve011_1.geometry} material={nodes.Curve011_1.material} />
          <mesh geometry={nodes.Curve011_2.geometry} material={nodes.Curve011_2.material} />
          <mesh geometry={nodes.Curve011_3.geometry} material={nodes.Curve011_3.material} />
        </group>
        <group name="AlienRRight" position={[-1.66, -0.18, -2.16]} rotation={[0, 0, -Math.PI]} scale={[3, 0.11, 3]}>
          <mesh geometry={nodes.Curve125.geometry} material={nodes.Curve125.material} />
          <mesh geometry={nodes.Curve125_1.geometry} material={nodes.Curve125_1.material} />
          <mesh geometry={nodes.Curve125_2.geometry} material={nodes.Curve125_2.material} />
          <mesh geometry={nodes.Curve125_3.geometry} material={nodes.Curve125_3.material} />
        </group>
      </group>
      <group position={[1.66, 2.46, 0.02]} rotation={[-1.69, 0, 0]}>
        <group
          name="AliensGreenLeft"
          position={[-1.68, 0.2, -2.17]}
          rotation={[0, -0.26, -3.14]}
          scale={[2.85, 0.29, 2.84]}>
          <mesh geometry={nodes.Curve127.geometry} material={nodes.Curve127.material} />
          <mesh geometry={nodes.Curve127_1.geometry} material={nodes.Curve127_1.material} />
          <mesh geometry={nodes.Curve127_2.geometry} material={nodes.Curve127_2.material} />
          <mesh geometry={nodes.Curve127_3.geometry} material={nodes.Curve127_3.material} />
        </group>
        <group
          name="AliensGreenMiddle"
          position={[-1.67, 0.17, -2.24]}
          rotation={[0, -Math.PI / 4, -3.14]}
          scale={[3.88, 0.24, 2.84]}>
          <mesh geometry={nodes.Curve294.geometry} material={nodes.Curve294.material} />
          <mesh geometry={nodes.Curve294_1.geometry} material={nodes.Curve294_1.material} />
          <mesh geometry={nodes.Curve294_2.geometry} material={nodes.Curve294_2.material} />
          <mesh geometry={nodes.Curve294_3.geometry} material={nodes.Curve294_3.material} />
        </group>
        <group
          name="AliensGreenRight"
          position={[-1.68, 0.2, -2.17]}
          rotation={[3.14, -0.29, -3.14]}
          scale={[3, 0.18, 4.57]}>
          <mesh geometry={nodes.Curve009.geometry} material={nodes.Curve009.material} />
          <mesh geometry={nodes.Curve009_1.geometry} material={nodes.Curve009_1.material} />
          <mesh geometry={nodes.Curve009_2.geometry} material={nodes.Curve009_2.material} />
          <mesh geometry={nodes.Curve009_3.geometry} material={nodes.Curve009_3.material} />
        </group>
      </group>
      <mesh
        geometry={nodes.UfoPurpleBod1.geometry}
        material={nodes.UfoPurpleBod1.material}
        position={[1.25, -1.16, 0.09]}
        rotation={[1.57, 0, -3.14]}
        scale={[4.88, 0.52, 4.88]}
      />
      <mesh
        geometry={nodes['Cylinder015_02_-_Default_0010'].geometry}
        material={materials['02_-_Default']}
        position={[-0.01, -0.74, -0.28]}
        rotation={[0, -0.01, Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes['Cylinder015_04_-_Default_0'].geometry}
        material={materials['04_-_Default']}
        position={[-0.01, -0.74, -0.28]}
        rotation={[0, -0.01, Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes['Cylinder015_05_-_Default_0012'].geometry}
        material={materials['05_-_Default']}
        position={[-0.01, -0.74, -0.28]}
        rotation={[0, -0.01, Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Object_2008.geometry}
        material={materials.material_0}
        position={[-0.01, -0.87, 0.1]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.pCube1_PistolTrigger_0002.geometry}
        material={materials['PistolTrigger.002']}
        position={[0.21, -0.81, 0.51]}
        rotation={[1.89, 1.54, -1.94]}
        scale={[0.01, 0.04, 0.01]}
      />
      <mesh
        geometry={nodes.pCylinder7_PistolBody_0002.geometry}
        material={materials['PistolBody.002']}
        position={[0.21, -0.78, 0.53]}
        rotation={[1.89, 1.54, -1.94]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.pHelix1_PistolRings_0002.geometry}
        material={materials['PistolRings.002']}
        position={[0.21, -0.72, 0.66]}
        rotation={[1.89, 1.54, 2.77]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.pTorus6_PistolType_0002.geometry}
        material={materials['PistolType.002']}
        position={[0.25, -0.73, 0.47]}
        rotation={[1.52, -0.08, -1.58]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Spinner004.geometry}
        material={materials['material_0.004']}
        position={[-1, -0.76, -0.4]}
        rotation={[1.53, -1.44, 3.12]}
        scale={[0, 0.02, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/UFOgames.glb')
