/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

import { GroupProps } from '@react-three/fiber';

// Define the types for your GLTF model
type GLTFResult = GLTF & {
  nodes: {
    GlassBubble: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_1: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_2: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_3: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_4: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_5: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_6: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_7: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_8: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_9: THREE.Mesh;
    Carnegiea_gigantea_HD_Cactus_spines_01_0_10: THREE.Mesh;
    gravel_inside_0: THREE.Mesh;
    ring_low_robot_2_0_1: THREE.Mesh;
    ring_low_robot_2_0_2: THREE.Mesh;
    SickPlantSteam_0: THREE.SkinnedMesh;
    Armature_rootJoint: THREE.Object3D;
    // Add any additional nodes here
  };
  materials: {
    glass: THREE.MeshStandardMaterial;
    Cactus_spines_01: THREE.MeshStandardMaterial;
    Carnegiea_bark_01: THREE.MeshStandardMaterial;
    Carnegiea_bark_03: THREE.MeshStandardMaterial;
    Carnegiea_petal_01: THREE.MeshStandardMaterial;
    Carnegiea_petal_02: THREE.MeshStandardMaterial;
    Carnegiea_petal_03: THREE.MeshStandardMaterial;
    Carnegiea_sepal_01: THREE.MeshStandardMaterial;
    Carnegiea_stigma: THREE.MeshStandardMaterial;
    Carnegiea_flower_stalk: THREE.MeshStandardMaterial;
    Carnegiea_stamens: THREE.MeshStandardMaterial;
    inside: THREE.MeshStandardMaterial;
    robot_2: THREE.MeshStandardMaterial;
    robot_1: THREE.MeshStandardMaterial;
    SickPlantSteam_Mat: THREE.MeshStandardMaterial;
    // Add any additional materials here
  };
};

export function MeBitTerranium(props: GroupProps) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    'https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitTerranium.glb'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="MeBitTerranium">
        <mesh
          name="GlassBubble"
          castShadow
          receiveShadow
          geometry={nodes.GlassBubble.geometry}
          material={materials.glass}
          position={[-1.284, 58.008, -20.731]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={37.111}
        />
        <group
          name="Carnegiea_gigantea_HD_Cactus_spines_01_0"
          position={[-1.022, 57.8, -30.355]}
          rotation={[-Math.PI / 2, 0, -1.85]}
          scale={[35.22, 44.77, 34.232]}
        >
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_1"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_1.geometry}
            material={materials.Cactus_spines_01}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_2"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_2.geometry}
            material={materials.Carnegiea_bark_01}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_3"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_3.geometry}
            material={materials.Carnegiea_bark_03}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_4"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_4.geometry}
            material={materials.Carnegiea_petal_01}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_5"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_5.geometry}
            material={materials.Carnegiea_petal_02}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_6"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_6.geometry}
            material={materials.Carnegiea_petal_03}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_7"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_7.geometry}
            material={materials.Carnegiea_sepal_01}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_8"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_8.geometry}
            material={materials.Carnegiea_stigma}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_9"
            castShadow
            receiveShadow
            geometry={nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_9.geometry}
            material={materials.Carnegiea_flower_stalk}
          />
          <mesh
            name="Carnegiea_gigantea_HD_Cactus_spines_01_0_10"
            castShadow
            receiveShadow
            geometry={
              nodes.Carnegiea_gigantea_HD_Cactus_spines_01_0_10.geometry
            }
            material={materials.Carnegiea_stamens}
          />
        </group>
        <mesh
          name="gravel_inside_0"
          castShadow
          receiveShadow
          geometry={nodes.gravel_inside_0.geometry}
          material={materials.inside}
          position={[0.807, 39.247, -20.222]}
          rotation={[-1.064, 0.476, -2.15]}
          scale={33.044}
        />
        <group
          name="ring_low_robot_2_0"
          position={[2.985, -7.771, -17.439]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={58.237}
        >
          <mesh
            name="ring_low_robot_2_0_1"
            castShadow
            receiveShadow
            geometry={nodes.ring_low_robot_2_0_1.geometry}
            material={materials.robot_2}
          />
          <mesh
            name="ring_low_robot_2_0_2"
            castShadow
            receiveShadow
            geometry={nodes.ring_low_robot_2_0_2.geometry}
            material={materials.robot_1}
          />
        </group>
        <group
          name="Root"
          position={[2.399, 23.004, -7.575]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={16.467}
        >
          <group
            name="Camera001"
            position={[-2.878, -0.018, 1.792]}
            rotation={[-0.773, 0.738, 1.971]}
          />
          <group name="PlantAimationBalls" position={[-0.202, -0.11, 0.085]}>
            <group name="SickPlantSteam" />
            <skinnedMesh
              name="SickPlantSteam_0"
              geometry={nodes.SickPlantSteam_0.geometry}
              material={materials.SickPlantSteam_Mat}
              skeleton={nodes.SickPlantSteam_0.skeleton}
            />
            <primitive object={nodes.Armature_rootJoint} />
          </group>
        </group>
      </group>
    </group>
  );
}
