/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitBoat.glb --types 
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    MeBoatBitObj: THREE.Mesh;
    MeBoatBitObj001: THREE.Mesh;
    MeBoatBitObj002: THREE.Mesh;
    MeBoatBitObj003: THREE.Mesh;
    MeBoatBitObj004: THREE.Mesh;
    MeBoatBitObj005: THREE.Mesh;
    MeBoatBitObj006: THREE.Mesh;
    MeBoatBitObj007: THREE.Mesh;
    MeBoatBitObj008: THREE.Mesh;
    MeBoatBitObj009: THREE.Mesh;
    MeBoatBitObj010: THREE.Mesh;
    MeBoatBitObj011: THREE.Mesh;
    MeBoatBitObj012: THREE.Mesh;
    MeBoatBitObj013: THREE.Mesh;
    MeBoatBitObj014: THREE.Mesh;
    MeBoatBitObj015: THREE.Mesh;
    MeBoatBitObj016: THREE.Mesh;
    MeBoatBitObj017: THREE.Mesh;
    MeBoatBitObj018: THREE.Mesh;
    MeBoatBitObj019: THREE.Mesh;
    MeBoatBitObj020: THREE.Mesh;
    MeBoatBitObj021: THREE.Mesh;
    MeBoatBitObj022: THREE.Mesh;
    MeBoatBitObj023: THREE.Mesh;
    MeBoatBitObj024: THREE.Mesh;
    MeBoatBitObj025: THREE.Mesh;
    MeBoatBitObj026: THREE.Mesh;
    MeBoatBitObj027: THREE.Mesh;
    MeBoatBitObj028: THREE.Mesh;
    MeBoatBitObj029: THREE.Mesh;
    MeBoatBitObj030: THREE.Mesh;
    MeBoatBitObj031: THREE.Mesh;
    MeBoatBitObj032: THREE.Mesh;
    MeBoatBitObj033: THREE.Mesh;
    MeBoatBitObj034: THREE.Mesh;
    MeBoatBitObj035: THREE.Mesh;
    MeBoatBitObj036: THREE.Mesh;
    MeBoatBitObj037: THREE.Mesh;
    MeBoatBitObj038: THREE.Mesh;
    MeBoatBitObj039: THREE.Mesh;
    MeBoatBitObj040: THREE.Mesh;
    MeBoatBitObj041: THREE.Mesh;
    MeBoatBitObj042: THREE.Mesh;
    MeBoatBitObj043: THREE.Mesh;
    MeBoatBitObj044: THREE.Mesh;
    MeBoatBitObj045: THREE.Mesh;
    MeBoatBitObj046: THREE.Mesh;
    MeBoatBitObj047: THREE.Mesh;
    MeBoatBitObj048: THREE.Mesh;
    MeBoatBitObj049: THREE.Mesh;
    MeBoatBitObj050: THREE.Mesh;
    MeBoatBitObj051: THREE.Mesh;
    MeBoatBitObj052: THREE.Mesh;
    MeBoatBitObj053: THREE.Mesh;
    MeBoatBitObj054: THREE.Mesh;
    MeBoatBitObj055: THREE.Mesh;
    MeBoatBitObj056: THREE.Mesh;
    MeBoatBitObj057: THREE.Mesh;
    MeBoatBitObj058: THREE.Mesh;
    MeBoatBitObj059: THREE.Mesh;
    MeBoatBitObj060: THREE.Mesh;
    MeBoatBitObj061: THREE.Mesh;
    MeBoatBitObj062: THREE.Mesh;
    MeBoatBitObj063: THREE.Mesh;
    MeBoatBitObj064: THREE.Mesh;
    MeBoatBitObj065: THREE.Mesh;
    MeBoatBitObj066: THREE.Mesh;
    MeBoatBitObj067: THREE.Mesh;
    MeBoatBitObj068: THREE.Mesh;
    MeBoatBitObj069: THREE.Mesh;
    MeBoatBitObj070: THREE.Mesh;
    MeBoatBitObj071: THREE.Mesh;
    MeBoatBitObj072: THREE.Mesh;
    MeBoatBitObj073: THREE.Mesh;
    MeBoatBitObj074: THREE.Mesh;
    MeBoatBitObj075: THREE.Mesh;
    MeBoatBitObj076: THREE.Mesh;
    MeBoatBitObj077: THREE.Mesh;
    MeBoatBitObj078: THREE.Mesh;
    MeBoatBitObj079: THREE.Mesh;
    MeBoatBitObj080: THREE.Mesh;
    MeBoatBitObj081: THREE.Mesh;
    MeBoatBitObj082: THREE.Mesh;
    MeBoatBitObj087: THREE.Mesh;
    MeBoatBitObj088: THREE.Mesh;
    MeBoatBitObj089: THREE.Mesh;
    MeBoatBitObj090: THREE.Mesh;
    MeBoatBitObj091: THREE.Mesh;
    MeBoatBitObj094: THREE.Mesh;
    MeBoatBitObj095: THREE.Mesh;
    MeBoatBitObj096: THREE.Mesh;
    MeBoatBitObj097: THREE.Mesh;
    MeBoatBitObj098: THREE.Mesh;
    MeBoatBitObj102: THREE.Mesh;
    MeBoatBitObj103: THREE.Mesh;
    MeBoatBitObj104: THREE.Mesh;
    MeBoatBitObj105: THREE.Mesh;
    MeBoatBitObj109: THREE.Mesh;
    MeBoatBitObj111: THREE.Mesh;
    MeBoatBitObj113: THREE.Mesh;
    MeBoatBitObj114: THREE.Mesh;
    MeBoatBitObj117: THREE.Mesh;
    MeBoatBitObj121: THREE.Mesh;
    MeBoatBitObj122: THREE.Mesh;
    MeBoatBitObj124: THREE.Mesh;
    MeBoatBitObj130: THREE.Mesh;
    MeBoatBitObj131: THREE.Mesh;
    MeBoatBitObj132: THREE.Mesh;
    MeBoatBitObj133: THREE.Mesh;
    MeBoatBitObj134: THREE.Mesh;
    MeBoatBitObj135: THREE.Mesh;
    MeBoatBitObj136: THREE.Mesh;
    MeBoatBitObj142: THREE.Mesh;
    MeBoatBitObj143: THREE.Mesh;
    MeBoatBitObj148: THREE.Mesh;
    MeBoatBitObj150: THREE.Mesh;
    MeBoatBitObj151: THREE.Mesh;
    MeBoatBitObj154: THREE.Mesh;
    MeBoatBitObj158: THREE.Mesh;
    MeBoatBitObj160: THREE.Mesh;
    MeBoatBitObj161: THREE.Mesh;
    MeBoatBitObj162: THREE.Mesh;
    MeBoatBitObj163: THREE.Mesh;
    MeBoatBitObj164: THREE.Mesh;
    MeBoatBitObj165: THREE.Mesh;
    MeBoatBitObj166: THREE.Mesh;
    MeBoatBitObj167: THREE.Mesh;
    MeBoatBitObj168: THREE.Mesh;
    MeBoatBitObj169: THREE.Mesh;
    MeBoatBitObj172: THREE.Mesh;
    MeBoatBitObj175: THREE.Mesh;
    MeBoatBitObj177: THREE.Mesh;
    MeBoatBitObj178: THREE.Mesh;
    MeBoatBitObj179: THREE.Mesh;
    MeBoatBitObj180: THREE.Mesh;
    MeBoatBitObj181: THREE.Mesh;
    MeBoatBitObj183: THREE.Mesh;
    MeBoatBitObj186: THREE.Mesh;
    MeBoatBitObj187: THREE.Mesh;
    MeBoatBitObj188: THREE.Mesh;
    MeBoatBitObj189: THREE.Mesh;
    MeBoatBitObj190: THREE.Mesh;
    MeBoatBitObj191: THREE.Mesh;
    MeBoatBitObj192: THREE.Mesh;
    MeBoatBitObj194: THREE.Mesh;
    MeBoatBitObj196: THREE.Mesh;
    MeBoatBitObj197: THREE.Mesh;
    MeBoatBitObj198: THREE.Mesh;
    MeBoatBitObj199: THREE.Mesh;
    MeBoatBitObj200: THREE.Mesh;
    MeBoatBitObj201: THREE.Mesh;
    MeBoatBitObj202: THREE.Mesh;
    MeBoatBitObj203: THREE.Mesh;
    MeBoatBitObj204: THREE.Mesh;
    MeBoatBitObj218: THREE.Mesh;
    MeBoatBitObj220: THREE.Mesh;
    MeBoatBitObj221: THREE.Mesh;
    MeBoatBitObj222: THREE.Mesh;
    MeBoatBitObj224: THREE.Mesh;
    MeBoatBitObj225: THREE.Mesh;
    MeBoatBitObj226: THREE.Mesh;
    MeBoatBitObj228: THREE.Mesh;
    MeBoatBitObj229: THREE.Mesh;
    MeBoatBitObj235: THREE.Mesh;
    MeBoatBitObj240: THREE.Mesh;
    MeBoatBitObj249: THREE.Mesh;
    Arm: THREE.Mesh;
    MeBoatBitObj258: THREE.Mesh;
    MeBoatBitObj260: THREE.Mesh;
    MeBoatBitObj262: THREE.Mesh;
    MeBoatBitObj263: THREE.Mesh;
    MeBoatBitObj264: THREE.Mesh;
    MeBoatBitObj265: THREE.Mesh;
    MeBoatBitObj266: THREE.Mesh;
    MeBoatBitObj267: THREE.Mesh;
    MeBoatBitObj268: THREE.Mesh;
    MeBoatBitObj269: THREE.Mesh;
    MeBoatBitObj270: THREE.Mesh;
    MeBoatBitObj271: THREE.Mesh;
    MeBoatBitObj272: THREE.Mesh;
    MeBoatBitObj273: THREE.Mesh;
    MeBoatBitObj274: THREE.Mesh;
    MeBoatBitObj275: THREE.Mesh;
    MeBoatBitObj276: THREE.Mesh;
    MeBoatBitObj277: THREE.Mesh;
    MeBoatBitObj278: THREE.Mesh;
    MeBoatBitObj279: THREE.Mesh;
    MeBoatBitObj282: THREE.Mesh;
    MeBoatBitObj283: THREE.Mesh;
    MeBoatBitObj284: THREE.Mesh;
    MeBoatBitObj285: THREE.Mesh;
    MeBoatBitObj286: THREE.Mesh;
    MeBoatBitObj322: THREE.Mesh;
    MeBoatBitObj361: THREE.Mesh;
    MeBoatBitObj377: THREE.Mesh;
    MeBoatBitObj408: THREE.Mesh;
    MeBoatBitObj465: THREE.Mesh;
    MeBoatBitObj467: THREE.Mesh;
    MeBoatBitObj468: THREE.Mesh;
    MeBoatBitObj469: THREE.Mesh;
    MeBoatBitObj470: THREE.Mesh;
    MeBoatBitObj471: THREE.Mesh;
    MeBoatBitObj472: THREE.Mesh;
    MeBoatBitObj473: THREE.Mesh;
    MeBoatBitObj475: THREE.Mesh;
    MeBoatBitObj476: THREE.Mesh;
    MeBoatBitObj477: THREE.Mesh;
    MeBoatBitObj478: THREE.Mesh;
    MeBoatBitObj480: THREE.Mesh;
    MeBoatBitObj481: THREE.Mesh;
    MeBoatBitObj482: THREE.Mesh;
    MeBoatBitObj483: THREE.Mesh;
    MeBoatBitObj484: THREE.Mesh;
    MeBoatBitObj487: THREE.Mesh;
    MeBoatBitObj488: THREE.Mesh;
    MeBoatBitObj489: THREE.Mesh;
    MeBoatBitObj490: THREE.Mesh;
    MeBoatBitObj491: THREE.Mesh;
    MeBoatBitObj492: THREE.Mesh;
    MeBoatBitObj493: THREE.Mesh;
    MeBoatBitObj494: THREE.Mesh;
    MeBoatBitObj495: THREE.Mesh;
    MeBoatBitObj496: THREE.Mesh;
    MeBoatBitObj497: THREE.Mesh;
    MeBoatBitObj498: THREE.Mesh;
    MeBoatBitObj499: THREE.Mesh;
    MeBoatBitObj500: THREE.Mesh;
    MeBoatBitObj501: THREE.Mesh;
    MeBoatBitObj502: THREE.Mesh;
    MeBoatBitObj503: THREE.Mesh;
    MeBoatBitObj504: THREE.Mesh;
    MeBoatBitObj505: THREE.Mesh;
    MeBoatBitObj506: THREE.Mesh;
    MeBoatBitObj507: THREE.Mesh;
    MeBoatBitObj508: THREE.Mesh;
    MeBoatBitObj509: THREE.Mesh;
    MeBoatBitObj510: THREE.Mesh;
    MeBoatBitObj511: THREE.Mesh;
    MeBoatBitObj512: THREE.Mesh;
    MeBoatBitObj513: THREE.Mesh;
    MeBoatBitObj514: THREE.Mesh;
    MeBoatBitObj515: THREE.Mesh;
    MeBoatBitObj516: THREE.Mesh;
    MeBoatBitObj517: THREE.Mesh;
    MeBoatBitObj518: THREE.Mesh;
    MeBoatBitObj519: THREE.Mesh;
    MeBoatBitObj520: THREE.Mesh;
    MeBoatBitObj521: THREE.Mesh;
    MeBoatBitObj522: THREE.Mesh;
    MeBoatBitObj523: THREE.Mesh;
    MeBoatBitObj524: THREE.Mesh;
    MeBoatBitObj525: THREE.Mesh;
    MeBoatBitObj526: THREE.Mesh;
    MeBoatBitObj527: THREE.Mesh;
    MeBoatBitObj528: THREE.Mesh;
    MeBoatBitObj529: THREE.Mesh;
    MeBoatBitObj530: THREE.Mesh;
    MeBoatBitObj531: THREE.Mesh;
    MeBoatBitObj532: THREE.Mesh;
    MeBoatBitObj533: THREE.Mesh;
    MeBoatBitObj534: THREE.Mesh;
    MeBoatBitObj535: THREE.Mesh;
    MeBoatBitObj536: THREE.Mesh;
    MeBoatBitObj537: THREE.Mesh;
    MeBoatBitObj538: THREE.Mesh;
    MeBoatBitObj539: THREE.Mesh;
    MeBoatBitObj540: THREE.Mesh;
    MeBoatBitObj545: THREE.Mesh;
    MeBoatBitObj546: THREE.Mesh;
    MeBoatBitObj584: THREE.Mesh;
    MeBoatBitObj755: THREE.Mesh;
    MeBoatBitObj784: THREE.Mesh;
    MeBoatBitObj816: THREE.Mesh;
    MeBoatBitObj847: THREE.Mesh;
    MeBoatBitObj849: THREE.Mesh;
    MeBoatBitObj890: THREE.Mesh;
    MeBoatBitObj1086: THREE.Mesh;
    MeBoatBitObj1088: THREE.Mesh;
    MeBoatBitObj1089: THREE.Mesh;
    MeBoatBitObj1097: THREE.Mesh;
    MeBoatBitObj1207: THREE.Mesh;
    MeBoatBitObj1207_1: THREE.Mesh;
    MeBoatBitObj1488: THREE.Mesh;
    MeBoatBitObj1635: THREE.Mesh;
    MeBoatBitObj1715: THREE.Mesh;
    MeBoatBitObj1794: THREE.Mesh;
    MeBoatBitObj1843: THREE.Mesh;
    MeBoatBitObj2184: THREE.Mesh;
    MeBoatBitObj2185: THREE.Mesh;
    MeBoatBitObj2226: THREE.Mesh;
    MeBoatBitObj2363: THREE.Mesh;
    MeBoatBitObj2618: THREE.Mesh;
    MeBoatBitObj2769: THREE.Mesh;
    MeBoatBitObj2775: THREE.Mesh;
    MeBoatBitObj2779: THREE.Mesh;
    MeBoatBitObj2780: THREE.Mesh;
    MeBoatBitObj2781: THREE.Mesh;
    MeBoatBitObj3148: THREE.Mesh;
    MeBoatBitObj3275: THREE.Mesh;
    MeBoatBitObj3332: THREE.Mesh;
    MeBoatBitObj3512: THREE.Mesh;
    MeBoatBitObj3611: THREE.Mesh;
    MeBoatBitObj3615: THREE.Mesh;
    MeBoatBitObj3632: THREE.Mesh;
    MeBoatBitObj3770: THREE.Mesh;
    MeBoatBitObj3900: THREE.Mesh;
    MeBoatBitObj3904: THREE.Mesh;
    MeBoatBitObj3906: THREE.Mesh;
    MeBoatBitObj3907: THREE.Mesh;
    MeBoatBitObj3908: THREE.Mesh;
    MeBoatBitObj3909: THREE.Mesh;
    MeBoatBitObj3911: THREE.Mesh;
    MeBoatBitObj3912: THREE.Mesh;
    MeBoatBitObj3913: THREE.Mesh;
    MeBoatBitObj3914: THREE.Mesh;
    MeBoatBitObj3915: THREE.Mesh;
    MeBoatBitObj3916: THREE.Mesh;
    MeBoatBitObj3917: THREE.Mesh;
    MeBoatBitObj3918: THREE.Mesh;
    MeBoatBitObj3919: THREE.Mesh;
    MeBoatBitObj3920: THREE.Mesh;
    MeBoatBitObj3921: THREE.Mesh;
    MeBoatBitObj3922: THREE.Mesh;
    MeBoatBitObj3923: THREE.Mesh;
    MeBoatBitObj3924: THREE.Mesh;
    MeBoatBitObj3926: THREE.Mesh;
    MeBoatBitObj3927: THREE.Mesh;
    MeBoatBitObj3929: THREE.Mesh;
    MeBoatBitObj3931: THREE.Mesh;
    MeBoatBitObj3935: THREE.Mesh;
    MeBoatBitObj3936: THREE.Mesh;
    MeBoatBitObj3940: THREE.Mesh;
    MeBoatBitObj3941: THREE.Mesh;
    MeBoatBitObj3942: THREE.Mesh;
    MeBoatBitObj3982: THREE.Mesh;
    MeBoatBitObj3984: THREE.Mesh;
    MeBoatBitObj3988: THREE.Mesh;
    MeBoatBitObj3989: THREE.Mesh;
    MeBoatBitObj3990: THREE.Mesh;
    MeBoatBitObj3991: THREE.Mesh;
    MeBoatBitObj3992: THREE.Mesh;
    MeBoatBitObj3994: THREE.Mesh;
    MeBoatBitObj4002: THREE.Mesh;
    MeBoatBitObj4009: THREE.Mesh;
    MeBoatBitObj4022: THREE.Mesh;
    MeBoatBitObj4023: THREE.Mesh;
    MeBoatBitObj4024: THREE.Mesh;
    MeBoatBitObj4025: THREE.Mesh;
    MeBoatBitObj4026: THREE.Mesh;
    MeBoatBitObj4027: THREE.Mesh;
  };
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    ['SVGMat.029']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function MeBitBoat(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitBoat.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.MeBoatBitObj.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj001.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj002.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj003.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj004.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj005.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj006.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj007.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj008.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj009.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj010.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj011.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj012.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj013.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj014.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj015.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj016.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj017.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj018.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj019.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj020.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj021.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj022.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj023.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj024.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj025.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj026.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj027.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj028.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj029.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj030.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj031.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj032.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj033.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj034.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj035.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj036.geometry}
        material={materials['Material.005']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj037.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj038.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj039.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj040.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj041.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj042.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj043.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj044.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj045.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj046.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj047.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj048.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj049.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj050.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj051.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj052.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj053.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj054.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj055.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj056.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj057.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj058.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj059.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj060.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj061.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj062.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj063.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj064.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj065.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj066.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj067.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj068.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj069.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj070.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj071.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj072.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj073.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj074.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj075.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj076.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj077.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj078.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj079.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj080.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj081.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj082.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj087.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj088.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj089.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj090.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj091.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj094.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj095.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj096.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj097.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj098.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj102.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj103.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj104.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj105.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj109.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj111.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj113.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj114.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj117.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj121.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj122.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj124.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj130.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj131.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj132.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj133.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj134.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj135.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj136.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj142.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj143.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj148.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj150.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj151.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj154.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj158.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj160.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj161.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj162.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj163.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj164.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj165.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj166.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj167.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj168.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj169.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj172.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj175.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj177.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj178.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj179.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj180.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj181.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj183.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj186.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj187.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj188.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj189.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj190.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj191.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj192.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj194.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj196.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj197.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj198.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj199.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj200.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj201.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj202.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj203.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj204.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj218.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj220.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj221.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj222.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj224.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj225.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj226.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj228.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj229.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj235.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj240.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj249.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Arm.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj258.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj260.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj262.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj263.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj264.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj265.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj266.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj267.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj268.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj269.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj270.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj271.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj272.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj273.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj274.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj275.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj276.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj277.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj278.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj279.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj282.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj283.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj284.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj285.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj286.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj322.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj361.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj377.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj408.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj465.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj467.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj468.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj469.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj470.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj471.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj472.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj473.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj475.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj476.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj477.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj478.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj480.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj481.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj482.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj483.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj484.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj487.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj488.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj489.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj490.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj491.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj492.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj493.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj494.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj495.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj496.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj497.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj498.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj499.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj500.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj501.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj502.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj503.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj504.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj505.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj506.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj507.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj508.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj509.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj510.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj511.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj512.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj513.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj514.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj515.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj516.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj517.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj518.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj519.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj520.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj521.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj522.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj523.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj524.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj525.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj526.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj527.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj528.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj529.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj530.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj531.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj532.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj533.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj534.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj535.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj536.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj537.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj538.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj539.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj540.geometry}
        material={materials['Material.002']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj545.geometry}
        material={materials['Material.002']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj546.geometry}
        material={materials['Material.002']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj584.geometry}
        material={materials['Material.002']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj755.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj784.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj816.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj847.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj849.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj890.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj1086.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj1088.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj1089.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj1097.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.MeBoatBitObj1207.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.MeBoatBitObj1207_1.geometry}
          material={materials['Material.006']}
        />
      </group>
      <mesh
        geometry={nodes.MeBoatBitObj1488.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj1635.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj1715.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj1794.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj1843.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2184.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2185.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2226.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2363.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2618.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2769.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2775.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2779.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2780.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj2781.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3148.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3275.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3332.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3512.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3611.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3615.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3632.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3770.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3900.geometry}
        material={materials['Material.006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3904.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3906.geometry}
        material={materials['SVGMat.029']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3907.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3908.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3909.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3911.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3912.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3913.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3914.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3915.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3916.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3917.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3918.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3919.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3920.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3921.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3922.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3923.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3924.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3926.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3927.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3929.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3931.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3935.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3936.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3940.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3941.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3942.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3982.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3984.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3988.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3989.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3990.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3991.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3992.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj3994.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj4002.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj4009.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj4022.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj4023.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj4024.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj4025.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj4026.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.MeBoatBitObj4027.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
