/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitSub.glb --types 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2001: THREE.Mesh
    Object_2002: THREE.Mesh
    Object_2003: THREE.Mesh
    Object_2004: THREE.Mesh
    Object_2005: THREE.Mesh
    Object_2006: THREE.Mesh
    Object_2007: THREE.Mesh
    Object_2008: THREE.Mesh
    Object_2009: THREE.Mesh
    Object_2010: THREE.Mesh
    Object_2011: THREE.Mesh
    Object_2012: THREE.Mesh
    Object_2013: THREE.Mesh
    Object_2014: THREE.Mesh
    Object_2015: THREE.Mesh
    Object_2016: THREE.Mesh
    Object_2017: THREE.Mesh
    Object_2018: THREE.Mesh
    Object_2019: THREE.Mesh
    Object_2020: THREE.Mesh
    Object_2021: THREE.Mesh
    Object_2022: THREE.Mesh
    Object_2023: THREE.Mesh
    Object_2024: THREE.Mesh
    Object_2025: THREE.Mesh
    Object_2026: THREE.Mesh
    Object_2027: THREE.Mesh
    Object_2028: THREE.Mesh
    Object_2029: THREE.Mesh
    MeBitHead: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function MeBitSub(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitSub.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2001.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2002.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_2003.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2004.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2005.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2006.geometry} material={materials['Material.001']} position={[0, -22.61, -11.307]} rotation={[0.561, 0, 0]} scale={[1, 0.601, 0.601]} />
        <mesh geometry={nodes.Object_2007.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2008.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2009.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2010.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2011.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2012.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2013.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2014.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2015.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2016.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2017.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2018.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2019.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2020.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2021.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2022.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2023.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2024.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2025.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2026.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2027.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2028.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_2029.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.MeBitHead.geometry} material={materials.PaletteMaterial001} position={[152.351, -107.046, 76.21]} rotation={[1.281, 0, -3.141]} scale={[575.136, 23.364, 575.172]} />
    </group>
  )
}

