/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitCar.glb --types 
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    UfoPurpleBod1014: THREE.Mesh;
    Hair: THREE.Mesh;
    forMayaAOfaraz1_forMayaAOrear_lights_0: THREE.Mesh;
    forMayaAOnomer_forMayaAOnumber_0: THREE.Mesh;
    forMayaAOpCube1_forMayaAOlambert15_0: THREE.Mesh;
    forMayaAOpCube4_forMayaAOlambert16_0: THREE.Mesh;
    forMayaAOpCylinder11_forMayaAOblinn6_0: THREE.Mesh;
    forMayaAOpolySurface148_forMayaAOblinn11_0: THREE.Mesh;
    forMayaAOpolySurface200_forMayaAOGrill2_0: THREE.Mesh;
    forMayaAOpolySurface83_Chrome_2_0_1: THREE.Mesh;
    forMayaAOpolySurface83_Chrome_2_0_2: THREE.Mesh;
    Pelota_Pixar_Mat_0: THREE.Mesh;
  };
  materials: {
    PaletteMaterial005: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    forMayaAOrear_lights: THREE.MeshBasicMaterial;
    forMayaAOnumber: THREE.MeshBasicMaterial;
    forMayaAOlambert15: THREE.MeshStandardMaterial;
    forMayaAOlambert16: THREE.MeshStandardMaterial;
    forMayaAOblinn6: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshPhysicalMaterial;
    forMayaAOGrill2: THREE.MeshBasicMaterial;
    Chrome_2: THREE.MeshBasicMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function MeBitCar(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitCar.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.UfoPurpleBod1014.geometry}
        material={materials.PaletteMaterial005}
        position={[2.044, 0.039, 7.009]}
        rotation={[0, 0, -3.141]}
        scale={[7.63, 1, 7.63]}
      />
      <mesh
        geometry={nodes.Hair.geometry}
        material={materials.PaletteMaterial001}
        position={[0.817, 0.603, 0.314]}
        rotation={[1.57, 0, -3.141]}
        scale={[14.683, 0.719, 14.683]}
      />
      <mesh
        geometry={nodes.forMayaAOfaraz1_forMayaAOrear_lights_0.geometry}
        material={materials.forMayaAOrear_lights}
        position={[0.006, -0.203, 0.243]}
        scale={[0.123, 0.114, 0.123]}
      />
      <mesh
        geometry={nodes.forMayaAOnomer_forMayaAOnumber_0.geometry}
        material={materials.forMayaAOnumber}
        position={[0.006, -0.203, 0.243]}
        scale={[0.123, 0.114, 0.123]}
      />
      <mesh
        geometry={nodes.forMayaAOpCube1_forMayaAOlambert15_0.geometry}
        material={materials.forMayaAOlambert15}
        position={[0.006, -0.203, 0.243]}
        scale={[0.123, 0.114, 0.123]}
      />
      <mesh
        geometry={nodes.forMayaAOpCube4_forMayaAOlambert16_0.geometry}
        material={materials.forMayaAOlambert16}
        position={[0.006, -0.203, 0.243]}
        scale={[0.123, 0.114, 0.123]}
      />
      <mesh
        geometry={nodes.forMayaAOpCylinder11_forMayaAOblinn6_0.geometry}
        material={materials.forMayaAOblinn6}
        position={[0.006, -0.203, 0.243]}
        scale={[0.123, 0.114, 0.123]}
      />
      <mesh
        geometry={nodes.forMayaAOpolySurface148_forMayaAOblinn11_0.geometry}
        material={materials.PaletteMaterial002}
        position={[0.006, -0.203, 0.243]}
        scale={[0.123, 0.114, 0.123]}
      />
      <mesh
        geometry={nodes.forMayaAOpolySurface200_forMayaAOGrill2_0.geometry}
        material={materials.forMayaAOGrill2}
        position={[0.006, -0.203, 0.243]}
        scale={[0.123, 0.114, 0.123]}
      />
      <group position={[0.006, -0.203, 0.243]} scale={[0.123, 0.114, 0.123]}>
        <mesh
          geometry={nodes.forMayaAOpolySurface83_Chrome_2_0_1.geometry}
          material={materials.Chrome_2}
        />
        <mesh
          geometry={nodes.forMayaAOpolySurface83_Chrome_2_0_2.geometry}
          material={materials.PaletteMaterial003}
        />
      </group>
      <mesh
        geometry={nodes.Pelota_Pixar_Mat_0.geometry}
        material={materials.material}
        position={[-0.824, 0.223, -1.006]}
        rotation={[0, 0.016, 0]}
        scale={0.004}
      />
    </group>
  );
}
