/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitSanta.glb --types 
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

// Define the types for your GLTF model
type GLTFResult = GLTF & {
  nodes: {
    Cylinder_Mat1_0: THREE.Mesh
    Polygon_Reduction_1_Material_0_0_1: THREE.Mesh
    Polygon_Reduction_1_Material_0_0_2: THREE.Mesh
    Polygon_Reduction_1_Material_0_0_3: THREE.Mesh
    Polygon_Reduction_1_Material_0_0_4: THREE.Mesh
    Polygon_Reduction_1_Material_0_0001: THREE.Mesh
    ['2_Mat_0']: THREE.Mesh
    AN_NPC_Sarara_SK_2__0: THREE.Mesh
    Object_87: THREE.SkinnedMesh
    Object_88: THREE.SkinnedMesh
    Object_89: THREE.SkinnedMesh
    ['2_2_Mat_0']: THREE.Mesh
    AN_NPC_Sarara_SK_2_3__0: THREE.Mesh
    Object_229: THREE.SkinnedMesh
    Object_230: THREE.SkinnedMesh
    Object_231: THREE.SkinnedMesh
    Sweep_1_2_Mat_0: THREE.Mesh
    AN_NPC_Sarara_SK__0: THREE.Mesh
    Object_16: THREE.SkinnedMesh
    Object_17: THREE.SkinnedMesh
    Object_18: THREE.SkinnedMesh
    Sweep_1_2_2_Mat_0: THREE.Mesh
    AN_NPC_Sarara_SK_2_2__0: THREE.Mesh
    Object_158: THREE.SkinnedMesh
    Object_159: THREE.SkinnedMesh
    Object_160: THREE.SkinnedMesh
    model_default002_0001_1: THREE.Mesh
    model_default002_0001_2: THREE.Mesh
    Object_39: THREE.Mesh
    Object_37: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13001: THREE.Mesh
    Object_17001: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_15001: THREE.Mesh
    Object_5001: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_35: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_50: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_4: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16001: THREE.Mesh
    Object_18001: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_34: THREE.Mesh
    model_default002_0_1: THREE.Mesh
    model_default002_0_2: THREE.Mesh
    _rootJoint: THREE.Bone
    _rootJoint_1: THREE.Bone
    _rootJoint_2: THREE.Bone
    _rootJoint_3: THREE.Bone
  }
  materials: {
    ['Mat.1']: THREE.MeshStandardMaterial
    Material_0: THREE.MeshStandardMaterial
    MeditationSanta_Model_9_u1_v1: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    AN_NPC_Sarara_SK__0: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_MI_PJH.1']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_Eyelash_PJH.1']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_EyeBall_MI_PJH.1']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_MI_PJH.3']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_Eyelash_PJH.3']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_EyeBall_MI_PJH.3']: THREE.MeshStandardMaterial
    CH_NPC_Pig_MI_PJH: THREE.MeshStandardMaterial
    CH_NPC_Pig_Eyelash_PJH: THREE.MeshStandardMaterial
    CH_NPC_Pig_EyeBall_MI_PJH: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_MI_PJH.2']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_Eyelash_PJH.2']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_EyeBall_MI_PJH.2']: THREE.MeshStandardMaterial
    ['default.001']: THREE.MeshStandardMaterial
    ['01_-_Default.001']: THREE.MeshPhysicalMaterial
    M_Bake: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    christmas_tree: THREE.MeshBasicMaterial
    ['default.002']: THREE.MeshStandardMaterial
    ['01_-_Default']: THREE.MeshPhysicalMaterial
  }
}

// Define the action names based on your GLTF animations
type ActionName = 'run' | 'Animation'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function MeBitSanta(props: GroupProps) {
  // Initialize the group ref with null for proper typing
  const group = useRef<THREE.Group>(null)

  // Load the GLTF model
  const { nodes, materials, animations } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitSanta.glb') as GLTFResult

  // Use animations without specifying a generic type
  const { actions } = useAnimations(animations, group)

  // Cast actions to GLTFActions for type safety
  const typedActions = actions as unknown as GLTFActions

  // Control animations using useEffect
  useEffect(() => {
    // Play the 'run' and 'Animation' animations when the component mounts
    typedActions['run']?.play()
    typedActions['Animation']?.play()

    // Cleanup: Stop the animations when the component unmounts
    return () => {
      typedActions['run']?.stop()
      typedActions['Animation']?.stop()
    }
  }, [typedActions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-17.821, -59.272, -6.797]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.169, 0.222, 0.323]}>
          <group name="fogat_fxfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Null" position={[-62.989, 175.826, 10.923]} rotation={[0.002, 0.106, 0.015]}>
                  <group name="Polygon_Reduction_1" position={[-41.897, 18.25, -1.215]} rotation={[-0.004, -0.106, -0.015]}>
                    <group name="Cylinder" position={[64.822, -3.513, 2.236]} rotation={[0, 0, 1.596]} scale={[1, 1.867, 1]}>
                      <mesh name="Cylinder_Mat1_0" geometry={nodes.Cylinder_Mat1_0.geometry} material={materials['Mat.1']} />
                    </group>
                    <group name="Polygon_Reduction_1_Material_0_0" position={[0, -6.132, 0]}>
                      <mesh name="Polygon_Reduction_1_Material_0_0_1" geometry={nodes.Polygon_Reduction_1_Material_0_0_1.geometry} material={materials.Material_0} />
                      <mesh name="Polygon_Reduction_1_Material_0_0_2" geometry={nodes.Polygon_Reduction_1_Material_0_0_2.geometry} material={materials.MeditationSanta_Model_9_u1_v1} />
                      <mesh name="Polygon_Reduction_1_Material_0_0_3" geometry={nodes.Polygon_Reduction_1_Material_0_0_3.geometry} material={materials.PaletteMaterial001} />
                      <mesh name="Polygon_Reduction_1_Material_0_0_4" geometry={nodes.Polygon_Reduction_1_Material_0_0_4.geometry} material={materials.material_0} />
                    </group>
                    <mesh name="Polygon_Reduction_1_Material_0_0001" geometry={nodes.Polygon_Reduction_1_Material_0_0001.geometry} material={materials.Material_0} />
                  </group>
                  <group name="Null_1" position={[10.152, -1.829, 16.351]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_84">
                      <primitive object={nodes._rootJoint} />
                      <group name="Object_86" rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh name="AN_NPC_Sarara_SK_2__0" geometry={nodes.AN_NPC_Sarara_SK_2__0.geometry} material={materials.AN_NPC_Sarara_SK__0} />
                      </group>
                      <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials['CH_NPC_Pig_MI_PJH.1']} skeleton={nodes.Object_87.skeleton} />
                      <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.1']} skeleton={nodes.Object_88.skeleton} />
                      <skinnedMesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials['CH_NPC_Pig_EyeBall_MI_PJH.1']} skeleton={nodes.Object_89.skeleton} />
                    </group>
                  </group>
                  <group name="Null_1_2" position={[46.743, -1.829, 21.441]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_226">
                      <primitive object={nodes._rootJoint_1} />
                      <group name="Object_228" rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh name="AN_NPC_Sarara_SK_2_3__0" geometry={nodes.AN_NPC_Sarara_SK_2_3__0.geometry} material={materials.AN_NPC_Sarara_SK__0} />
                      </group>
                      <skinnedMesh name="Object_229" geometry={nodes.Object_229.geometry} material={materials['CH_NPC_Pig_MI_PJH.3']} skeleton={nodes.Object_229.skeleton} />
                      <skinnedMesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.3']} skeleton={nodes.Object_230.skeleton} />
                      <skinnedMesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials['CH_NPC_Pig_EyeBall_MI_PJH.3']} skeleton={nodes.Object_231.skeleton} />
                    </group>
                  </group>
                  <group name="Null_2" position={[13.632, -1.829, -4.072]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_13">
                      <primitive object={nodes._rootJoint_2} />
                      <group name="Object_15" rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh name="AN_NPC_Sarara_SK__0" geometry={nodes.AN_NPC_Sarara_SK__0.geometry} material={materials.AN_NPC_Sarara_SK__0} />
                      </group>
                      <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.CH_NPC_Pig_MI_PJH} skeleton={nodes.Object_16.skeleton} />
                      <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.CH_NPC_Pig_Eyelash_PJH} skeleton={nodes.Object_17.skeleton} />
                      <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.CH_NPC_Pig_EyeBall_MI_PJH} skeleton={nodes.Object_18.skeleton} />
                    </group>
                  </group>
                  <group name="Null_2_2" position={[50.223, -1.829, 1.019]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Object_155">
                      <primitive object={nodes._rootJoint_3} />
                      <group name="Object_157" rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh name="AN_NPC_Sarara_SK_2_2__0" geometry={nodes.AN_NPC_Sarara_SK_2_2__0.geometry} material={materials.AN_NPC_Sarara_SK__0} />
                      </group>
                      <skinnedMesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials['CH_NPC_Pig_MI_PJH.2']} skeleton={nodes.Object_158.skeleton} />
                      <skinnedMesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.2']} skeleton={nodes.Object_159.skeleton} />
                      <skinnedMesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials['CH_NPC_Pig_EyeBall_MI_PJH.2']} skeleton={nodes.Object_160.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model006" position={[-38.783, 16.686, 2.672]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.75, 0.712, 0.931]}>
          <group name="snowman_animadoFBX001" rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
            <group name="Object_2002">
              <group name="RootNode002">
                <group name="model001" position={[0, 9.726, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={38.26}>
                  <group name="model_default002_0001" position={[0, -0.005, 0]} scale={[2.411, 2.411, 2.012]}>
                    <mesh name="model_default002_0001_1" geometry={nodes.model_default002_0001_1.geometry} material={materials['default.001']} />
                    <mesh name="model_default002_0001_2" geometry={nodes.model_default002_0001_2.geometry} material={materials['01_-_Default.001']} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[-38.562, 17.067, 2.596]} rotation={[-Math.PI / 2, 0, 1.566]} scale={[0.429, 0.359, 0.339]}>
          <group name="root002">
            <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Bake001_18">
                <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.M_Bake} />
              </group>
              <group name="Bake_17">
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.M_Bake} />
              </group>
              <group name="NeonTree_16">
                <group name="Cylinder001_3" position={[0, 4.828, -0.021]} scale={0.862}>
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material.016']} />
                </group>
                <group name="Cylinder002_4">
                  <mesh name="Object_13001" geometry={nodes.Object_13001.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane001_6" position={[-1.634, 3.713, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.16}>
                  <mesh name="Object_17001" geometry={nodes.Object_17001.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane002_7" position={[1.389, 4.408, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.163}>
                  <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane003_8" position={[-1.828, 1.671, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.118}>
                  <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane004_9" position={[-0.742, 4.681, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.127}>
                  <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane005_10" position={[3.055, 2.912, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.105}>
                  <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane006_11" position={[-2.211, 0.886, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.147}>
                  <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane007_12" position={[-1.959, 3.019, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.163}>
                  <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane008_13" position={[2.516, 1.125, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.118}>
                  <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane009_14" position={[1.776, 3.347, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.127}>
                  <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials['Material.016']} />
                </group>
                <group name="Plane_5" position={[1.655, 1.948, -0.273]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={0.147}>
                  <mesh name="Object_15001" geometry={nodes.Object_15001.geometry} material={materials['Material.016']} />
                </group>
                <group name="BezierCircle_0">
                  <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['Material.016']} />
                </group>
                <group name="BezierCurve014_1">
                  <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Material.016']} />
                </group>
                <group name="BezierCurve016_2">
                  <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.016']} />
                </group>
                <group name="Sphere002_15">
                  <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials['Material.016']} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model003" position={[-38.124, 17.732, -11.68]} rotation={[-Math.PI / 2, -0.112, 1.601]} scale={[0.563, 1.172, 0.677]}>
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="gifts001_24" position={[1.205, -0.566, 0]} rotation={[0, Math.PI / 4, 0]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.christmas_tree} />
              </group>
              <group name="gifts002_25" position={[-1.51, -0.564, 0]} rotation={[0, 0, 0.004]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.christmas_tree} />
              </group>
              <group name="gifts003_26" position={[-0.743, -0.566, -0.282]} rotation={[0, Math.PI / 4, 0]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.christmas_tree} />
              </group>
              <group name="gifts_23" position={[0.289, -0.566, 0.14]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings001_1" position={[-0.521, 3.021, -0.107]} rotation={[0, -0.126, 0]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings002_2" position={[0.681, 2.828, 0.223]} rotation={[0, 0.126, 0]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings003_3" position={[1.05, 2.177, -0.065]} rotation={[0, -0.126, 0]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings004_4" position={[0.793, 1.751, 0.267]} rotation={[0, 0.126, 0]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings005_0" position={[-0.685, 2.368, 0.283]} rotation={[0, 0.126, 0]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings006_5" position={[1.236, 1.374, 0.048]} rotation={[0, -0.126, 0]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings007_6" position={[1.628, 1.056, -0.216]} rotation={[0, 0.126, 0]}>
                <mesh name="Object_16001" geometry={nodes.Object_16001.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings008_7" position={[1.661, 0.289, -0.164]} rotation={[0, -0.126, 0]}>
                <mesh name="Object_18001" geometry={nodes.Object_18001.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings009_8" position={[1.438, -0.138, 0.236]} rotation={[0, 0.063, 0]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings010_9" position={[0.891, -0.248, -0.311]} rotation={[0, -0.063, 0]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings011_10" position={[-1.201, -0.064, 0.476]} rotation={[0, -0.126, 0]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings012_11" position={[-1.67, -0.066, 0.048]} rotation={[0, 0.126, 0]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings013_12" position={[-1.761, 0.725, -0.239]} rotation={[0, -0.126, 0]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings014_13" position={[-1.189, 1.401, 0.645]} rotation={[0, 0.126, 0]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.christmas_tree} />
              </group>
              <group name="rings015_14" position={[-1.363, 2.006, -0.185]} rotation={[0, -0.126, 0]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.christmas_tree} />
              </group>
              <group name="star001_19" position={[0.28, 2.608, 0]} scale={0.999}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.christmas_tree} />
              </group>
              <group name="star002_20" position={[0.195, 2.957, 0]} scale={0.999}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.christmas_tree} />
              </group>
              <group name="star003_21" position={[-0.195, 2.957, 0]} scale={0.999}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.christmas_tree} />
              </group>
              <group name="star004_22" position={[-0.28, 2.608, 0]} scale={0.999}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.christmas_tree} />
              </group>
              <group name="base_16">
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.christmas_tree} />
              </group>
              <group name="star_17" position={[0, 2.726, 0]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.christmas_tree} />
              </group>
              <group name="tree001_18" position={[-0.04, 0.057, -0.005]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.christmas_tree} />
              </group>
              <group name="tree_15">
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.christmas_tree} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[-38.164, 16.543, -11.669]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="snowman_animadoFBX" rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
            <group name="Object_2001">
              <group name="RootNode001">
                <group name="model" position={[0, 9.726, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={38.26}>
                  <group name="model_default002_0" position={[0, -0.005, 0]} scale={[2.411, 2.491, 2.736]}>
                    <mesh name="model_default002_0_1" geometry={nodes.model_default002_0_1.geometry} material={materials['default.002']} />
                    <mesh name="model_default002_0_2" geometry={nodes.model_default002_0_2.geometry} material={materials['01_-_Default']} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

