/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitUFO.glb --types 
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

// Define the types for your GLTF model
type GLTFResult = GLTF & {
  nodes: {
    Mball001: THREE.Mesh
    UfoPurpleBod1: THREE.Mesh
    UFOPurpSides: THREE.Mesh
    Curve123: THREE.Mesh
    Curve123_1: THREE.Mesh
    Curve123_2: THREE.Mesh
    Curve123_3: THREE.Mesh
    Curve123_4: THREE.Mesh
    Curve123_5: THREE.Mesh
    Curve123_6: THREE.Mesh
    Curve123_7: THREE.Mesh
    Curve123_8: THREE.Mesh
    Curve123_9: THREE.Mesh
    Curve123_10: THREE.Mesh
    Curve123_11: THREE.Mesh
    Curve123_12: THREE.Mesh
    Curve123_13: THREE.Mesh
    Curve123_14: THREE.Mesh
    Curve123_15: THREE.Mesh
    Curve123_16: THREE.Mesh
    Curve123_17: THREE.Mesh
    Curve123_18: THREE.Mesh
    Curve123_19: THREE.Mesh
    Curve123_20: THREE.Mesh
    Curve123_21: THREE.Mesh
    Curve123_22: THREE.Mesh
    Curve123_23: THREE.Mesh
    Curve123_24: THREE.Mesh
    Curve123_25: THREE.Mesh
    Curve123_26: THREE.Mesh
    Curve123_27: THREE.Mesh
    Curve123_28: THREE.Mesh
    Curve123_29: THREE.Mesh
    Curve123_30: THREE.Mesh
    Curve123_31: THREE.Mesh
    Curve123_32: THREE.Mesh
    Curve391: THREE.Mesh
    Curve391_1: THREE.Mesh
    Curve391_2: THREE.Mesh
    Curve391_3: THREE.Mesh
    Curve063: THREE.Mesh
    Curve063_1: THREE.Mesh
    Curve063_2: THREE.Mesh
    Curve063_3: THREE.Mesh
    Curve011: THREE.Mesh
    Curve011_1: THREE.Mesh
    Curve011_2: THREE.Mesh
    Curve011_3: THREE.Mesh
    Curve125: THREE.Mesh
    Curve125_1: THREE.Mesh
    Curve125_2: THREE.Mesh
    Curve125_3: THREE.Mesh
    Curve009: THREE.Mesh
    Curve009_1: THREE.Mesh
    Curve009_2: THREE.Mesh
    Curve009_3: THREE.Mesh
    Curve127: THREE.Mesh
    Curve127_1: THREE.Mesh
    Curve127_2: THREE.Mesh
    Curve127_3: THREE.Mesh
    Curve294: THREE.Mesh
    Curve294_1: THREE.Mesh
    Curve294_2: THREE.Mesh
    Curve294_3: THREE.Mesh
  }
  materials: {
    PaletteMaterial004: THREE.MeshPhysicalMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    PaletteMaterial009: THREE.MeshStandardMaterial
    PaletteMaterial010: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial011: THREE.MeshStandardMaterial
    PaletteMaterial012: THREE.MeshStandardMaterial
  }
}

// Define the action names based on your GLTF animations
type ActionName =
  | 'Curve.071Action'
  | 'AlienPurple'
  | 'AlienOrange'
  | 'AlienRLeft'
  | 'AlienRMiddle'
  | 'AlienRRight'
  | 'AliensGreenFront.005Action'
  | 'AliensGreenFront.018Action'
  | 'AliensGreenLeft.001Action.003'

// Define the actions type
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function MeBitUfo(props: GroupProps) {
  // Initialize the group ref with null for proper typing
  const group = useRef<THREE.Group>(null)

  // Load the GLTF model
  const { nodes, materials, animations } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitUFO.glb') as GLTFResult

  // Use animations without specifying a generic type
  const { actions } = useAnimations(animations, group)

  // Cast actions to GLTFActions for type safety
  const typedActions = actions as unknown as GLTFActions

  // Control animations using useEffect
  useEffect(() => {
    // Play all defined animations when the component mounts
    Object.values(typedActions).forEach(action => action.play())

    // Cleanup: Stop all animations when the component unmounts
    return () => {
      Object.values(typedActions).forEach(action => action.stop())
    }
  }, [typedActions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Mball001" geometry={nodes.Mball001.geometry} material={materials.PaletteMaterial004} position={[-1.701, -0.387, -1.975]} rotation={[Math.PI, -0.016, Math.PI]} scale={[0.635, 0.866, 0.425]} />
        <mesh name="UfoPurpleBod1" geometry={nodes.UfoPurpleBod1.geometry} material={materials.PaletteMaterial005} position={[0.306, 0.039, 0.019]} rotation={[0, 0, -3.141]} scale={[7.63, 1, 7.63]} />
        <mesh name="UFOPurpSides" geometry={nodes.UFOPurpSides.geometry} material={materials.PaletteMaterial005} position={[0.306, 0.039, 0.019]} rotation={[0, 0, -3.141]} scale={[7.63, 1, 7.63]} />
        <group name="AlienPurple" position={[-0.744, 0.011, -1.588]} rotation={[0, 0, -3.141]} scale={[7.63, 1, 7.63]}>
          <mesh name="Curve123" geometry={nodes.Curve123.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_1" geometry={nodes.Curve123_1.geometry} material={materials.PaletteMaterial006} />
          <mesh name="Curve123_2" geometry={nodes.Curve123_2.geometry} material={materials.PaletteMaterial007} />
          <mesh name="Curve123_3" geometry={nodes.Curve123_3.geometry} material={materials.PaletteMaterial006} />
          <mesh name="Curve123_4" geometry={nodes.Curve123_4.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_5" geometry={nodes.Curve123_5.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_6" geometry={nodes.Curve123_6.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_7" geometry={nodes.Curve123_7.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_8" geometry={nodes.Curve123_8.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_9" geometry={nodes.Curve123_9.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_10" geometry={nodes.Curve123_10.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_11" geometry={nodes.Curve123_11.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_12" geometry={nodes.Curve123_12.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_13" geometry={nodes.Curve123_13.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_14" geometry={nodes.Curve123_14.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_15" geometry={nodes.Curve123_15.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_16" geometry={nodes.Curve123_16.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_17" geometry={nodes.Curve123_17.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_18" geometry={nodes.Curve123_18.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_19" geometry={nodes.Curve123_19.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_20" geometry={nodes.Curve123_20.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_21" geometry={nodes.Curve123_21.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_22" geometry={nodes.Curve123_22.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_23" geometry={nodes.Curve123_23.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_24" geometry={nodes.Curve123_24.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_25" geometry={nodes.Curve123_25.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_26" geometry={nodes.Curve123_26.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_27" geometry={nodes.Curve123_27.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_28" geometry={nodes.Curve123_28.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_29" geometry={nodes.Curve123_29.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_30" geometry={nodes.Curve123_30.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_31" geometry={nodes.Curve123_31.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve123_32" geometry={nodes.Curve123_32.geometry} material={materials.PaletteMaterial005} />
        </group>
        <group name="AlienOrange" position={[-2.652, 0.039, -1.468]} rotation={[0, 0, -Math.PI]} scale={[7.63, 1, 7.63]}>
          <mesh name="Curve391" geometry={nodes.Curve391.geometry} material={materials.PaletteMaterial006} />
          <mesh name="Curve391_1" geometry={nodes.Curve391_1.geometry} material={materials.PaletteMaterial008} />
          <mesh name="Curve391_2" geometry={nodes.Curve391_2.geometry} material={materials.PaletteMaterial006} />
          <mesh name="Curve391_3" geometry={nodes.Curve391_3.geometry} material={materials.PaletteMaterial005} />
        </group>
        <group name="AlienRLeft" position={[-1.656, -0.184, -2.157]} rotation={[0, 0, -3.141]} scale={[4.695, 0.215, 4.695]}>
          <mesh name="Curve063" geometry={nodes.Curve063.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve063_1" geometry={nodes.Curve063_1.geometry} material={materials.PaletteMaterial009} />
          <mesh name="Curve063_2" geometry={nodes.Curve063_2.geometry} material={materials.PaletteMaterial010} />
          <mesh name="Curve063_3" geometry={nodes.Curve063_3.geometry} material={materials.PaletteMaterial002} />
        </group>
        <group name="AlienRMiddle" position={[-1.656, -0.184, -2.157]} rotation={[0, 0, Math.PI]} scale={[4.695, 0.215, 4.695]}>
          <mesh name="Curve011" geometry={nodes.Curve011.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve011_1" geometry={nodes.Curve011_1.geometry} material={materials.PaletteMaterial009} />
          <mesh name="Curve011_2" geometry={nodes.Curve011_2.geometry} material={materials.PaletteMaterial010} />
          <mesh name="Curve011_3" geometry={nodes.Curve011_3.geometry} material={materials.PaletteMaterial002} />
        </group>
        <group name="AlienRRight" position={[-1.656, -0.184, -2.157]} rotation={[0, 0, -Math.PI]} scale={[4.695, 0.215, 4.695]}>
          <mesh name="Curve125" geometry={nodes.Curve125.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve125_1" geometry={nodes.Curve125_1.geometry} material={materials.PaletteMaterial009} />
          <mesh name="Curve125_2" geometry={nodes.Curve125_2.geometry} material={materials.PaletteMaterial010} />
          <mesh name="Curve125_3" geometry={nodes.Curve125_3.geometry} material={materials.PaletteMaterial002} />
        </group>
        <group name="AliensGreenRight" position={[-1.678, 0.204, -2.166]} rotation={[0, -0.262, -3.141]} scale={[7.783, 0.6, 7.783]}>
          <mesh name="Curve009" geometry={nodes.Curve009.geometry} material={materials.PaletteMaterial011} />
          <mesh name="Curve009_1" geometry={nodes.Curve009_1.geometry} material={materials.PaletteMaterial012} />
          <mesh name="Curve009_2" geometry={nodes.Curve009_2.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve009_3" geometry={nodes.Curve009_3.geometry} material={materials.PaletteMaterial005} />
        </group>
        <group name="AliensGreenLeft" position={[-1.678, 0.204, -2.166]} rotation={[0, -0.262, -3.141]} scale={[7.783, 0.6, 7.783]}>
          <mesh name="Curve127" geometry={nodes.Curve127.geometry} material={materials.PaletteMaterial011} />
          <mesh name="Curve127_1" geometry={nodes.Curve127_1.geometry} material={materials.PaletteMaterial012} />
          <mesh name="Curve127_2" geometry={nodes.Curve127_2.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve127_3" geometry={nodes.Curve127_3.geometry} material={materials.PaletteMaterial005} />
        </group>
        <group name="AliensGreenMiddle" position={[-1.665, 0.169, -2.243]} rotation={[0, -Math.PI / 4, -3.142]} scale={[7.783, 0.6, 7.783]}>
          <mesh name="Curve294" geometry={nodes.Curve294.geometry} material={materials.PaletteMaterial011} />
          <mesh name="Curve294_1" geometry={nodes.Curve294_1.geometry} material={materials.PaletteMaterial012} />
          <mesh name="Curve294_2" geometry={nodes.Curve294_2.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Curve294_3" geometry={nodes.Curve294_3.geometry} material={materials.PaletteMaterial005} />
        </group>
      </group>
    </group>
  )
}

