/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitPlant.glb --types 
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    MeBitHead: THREE.Mesh;
    armHoles_LP_UV_checker_0: THREE.Mesh;
  };
  materials: {
    ['PaletteMaterial001.034']: THREE.MeshStandardMaterial;
    UV_checker: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function MeBitPlant(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitPlant.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.MeBitHead.geometry}
        material={materials['PaletteMaterial001.034']}
        position={[0.076, 1.221, 0.121]}
        rotation={[1.592, 0, -3.141]}
        scale={[4.724, 0.192, 4.724]}
      />
      <mesh
        geometry={nodes.armHoles_LP_UV_checker_0.geometry}
        material={materials.UV_checker}
        position={[0.208, 0.769, 0.114]}
        rotation={[-1.477, Math.PI / 2, 0]}
        scale={[2.584, 2.584, 6.578]}
      />
    </group>
  );
}
