/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitCthulu.glb --types 
*/

import { useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import React, { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

// Define the types for your GLTF model
type GLTFResult = GLTF & {
  nodes: {
    HeadBack001: THREE.Mesh;
    Curve014: THREE.Mesh;
    Curve017: THREE.Mesh;
    Curve034: THREE.Mesh;
    Curve037: THREE.Mesh;
    Curve044: THREE.InstancedMesh;
    Curve048: THREE.InstancedMesh;
    Curve049: THREE.InstancedMesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function MeBitCthulu(props: GroupProps) {
  const { nodes, materials } = useGLTF(
    'https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitCthulu.glb'
  ) as GLTFResult;
  const instancedRef1 = useRef<THREE.InstancedMesh>(null);
  const instancedRef2 = useRef<THREE.InstancedMesh>(null);
  const instancedRef3 = useRef<THREE.InstancedMesh>(null);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.HeadBack001.geometry}
        material={materials.PaletteMaterial001}
        position={[0.111, -0.015, -0.051]}
        rotation={[0.027, 0.01, 3.135]}
        scale={[0.263, 0.022, 0.229]}
      />
      <mesh
        geometry={nodes.Curve014.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Curve017.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Curve034.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Curve037.geometry}
        material={materials.PaletteMaterial001}
      />
      <instancedMesh
        ref={instancedRef1}
        geometry={nodes.Curve044.geometry}
        material={materials.PaletteMaterial001}
        args={[nodes.Curve044.geometry, materials.PaletteMaterial001, 2]}
        instanceMatrix={nodes.Curve044.instanceMatrix}
      />
      <instancedMesh
        ref={instancedRef2}
        geometry={nodes.Curve048.geometry}
        material={materials.PaletteMaterial001}
        args={[nodes.Curve048.geometry, materials.PaletteMaterial001, 2]}
        instanceMatrix={nodes.Curve048.instanceMatrix}
      />
      <instancedMesh
        ref={instancedRef3}
        geometry={nodes.Curve049.geometry}
        material={materials.PaletteMaterial001}
        args={[nodes.Curve049.geometry, materials.PaletteMaterial001, 2]}
        instanceMatrix={nodes.Curve049.instanceMatrix}
      />
    </group>
  );
}
