/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitEnderman.glb --types 
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

import { GroupProps } from '@react-three/fiber';

// Define the types for your GLTF model
type GLTFResult = GLTF & {
  nodes: {
    Mesh_Skin_0: THREE.SkinnedMesh;
    Mesh_Skin_0_1: THREE.SkinnedMesh;
    Object_15001: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
    neutral_bone: THREE.Bone;
  };
  materials: {
    Skin: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
  };
};

type ActionName = 'Armature|Idle' | 'Armature|Walk' | 'Armature|Yell';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function MeBitEnderman(props: GroupProps) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    'https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitEnderman.glb'
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  // Cast actions to GLTFActions for type safety
  const typedActions = actions as unknown as GLTFActions;

  // Example usage of actions (optional)
  // You can control animations using typedActions
  // For example:
  // React.useEffect(() => {
  //   typedActions['Armature|Idle']?.play()
  //   return () => {
  //     typedActions['Armature|Idle']?.stop()
  //   }
  // }, [typedActions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.018}
        >
          <group
            name="3339e04691e7494cb6323f98e276e43afbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode001">
                <group
                  name="Armature"
                  position={[0, 17.068, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_11">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_13001"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <primitive object={nodes.neutral_bone} />
                    <group name="Object_14001">
                      <skinnedMesh
                        name="Mesh_Skin_0"
                        geometry={nodes.Mesh_Skin_0.geometry}
                        material={materials.Skin}
                        skeleton={nodes.Mesh_Skin_0.skeleton}
                      />
                      <skinnedMesh
                        name="Mesh_Skin_0_1"
                        geometry={nodes.Mesh_Skin_0_1.geometry}
                        material={materials.PaletteMaterial001}
                        skeleton={nodes.Mesh_Skin_0_1.skeleton}
                      />
                    </group>
                    <skinnedMesh
                      name="Object_15001"
                      geometry={nodes.Object_15001.geometry}
                      material={materials.Eyes}
                      skeleton={nodes.Object_15001.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="Camera001"
                  position={[794.567, 182.179, 3639.037]}
                  rotation={[-2.988, 1.34, 2.913]}
                  scale={100}
                >
                  <group name="Object_9" />
                </group>
                <group
                  name="Light"
                  position={[307.625, 190.386, 299.455]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100}
                >
                  <group name="Object_6001" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_7" />
                  </group>
                </group>
                <group
                  name="Mesh"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
