/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitBalloon.glb --types 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ball001_baloon001_0: THREE.Mesh
    basket001_baloon_0: THREE.Mesh
    MeBitHead001: THREE.Mesh
  }
  materials: {
    ['baloon.001']: THREE.MeshStandardMaterial
    baloon: THREE.MeshStandardMaterial
    ['PaletteMaterial001.022']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function MeBitBalloon(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitBalloon.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ball001_baloon001_0.geometry} material={materials['baloon.001']} position={[-0.603, 0.172, 0.788]} rotation={[Math.PI, -0.175, Math.PI]} scale={1.98} />
      <mesh geometry={nodes.basket001_baloon_0.geometry} material={materials.baloon} position={[-0.603, 0.751, 0.788]} rotation={[Math.PI, -0.175, Math.PI]} scale={[1.98, 1.366, 1.98]} />
      <mesh geometry={nodes.MeBitHead001.geometry} material={materials['PaletteMaterial001.022']} position={[2.714, 0.456, 0.926]} rotation={[1.286, 0.056, 2.952]} scale={[12.266, 0.567, 12.352]} />
    </group>
  )
}

