/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MeBitHelmet.glb --types 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MeBitHelmet_1: THREE.Mesh
    MeBitHelmet_2: THREE.Mesh
    MeBitHelmet_3: THREE.Mesh
  }
  materials: {
    ['soft.002']: THREE.MeshStandardMaterial
    ['PaletteMaterial005.044']: THREE.MeshStandardMaterial
    ['base.002']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function MeBitHelmet(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitHelmet.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.29, 0.693, 0.392]} scale={1.751}>
        <mesh geometry={nodes.MeBitHelmet_1.geometry} material={materials['soft.002']} />
        <mesh geometry={nodes.MeBitHelmet_2.geometry} material={materials['PaletteMaterial005.044']} />
        <mesh geometry={nodes.MeBitHelmet_3.geometry} material={materials['base.002']} />
      </group>
    </group>
  )
}

