/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useAnimations, useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

import { GroupProps } from '@react-three/fiber'

// Define the types for your GLTF model
type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh
    MeBitHead: THREE.Mesh
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    bikini_bottom_strawberry_0: THREE.Mesh
    GLTF_created_0_rootJoint: THREE.Object3D
    // Add any additional nodes here
    // Example:
    polySurface60: THREE.Group
    Scene: THREE.Group
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    'PaletteMaterial001.001': THREE.MeshStandardMaterial
    Carpet: THREE.MeshStandardMaterial
    Tassels: THREE.MeshStandardMaterial
    // Add any additional materials here
  }
}

export function MeBitFatty(props: GroupProps) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/meBits/MeBitFatty.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="polySurface60" position={[0.543, 5.991, 0.898]} scale={[0.998, 1, 1]} />
        <group name="GLTF_created_0" position={[0, -8.498, -3.769]} scale={[1.484, 1, 1.484]}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
        </group>
        <mesh
          name="Body"
          castShadow
          receiveShadow
          geometry={nodes.Body.geometry}
          material={materials.PaletteMaterial001}
          position={[23.536, -1.453, -1.928]}
          rotation={[-1.861, 0.001, -0.004]}
          scale={[-89.88, -4.219, -49.974]}
        />
        <mesh
          name="MeBitHead"
          castShadow
          receiveShadow
          geometry={nodes.MeBitHead.geometry}
          material={materials['PaletteMaterial001.001']}
          position={[-5.877, 1.847, -4.846]}
          rotation={[1.861, -0.003, -0.009]}
          scale={[23.445, 1.73, 17.616]}
        />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.Carpet}
          skeleton={nodes.Object_7.skeleton}
          position={[0, -8.498, -3.769]}
          scale={[1.484, 1, 1.484]}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.Tassels}
          skeleton={nodes.Object_9.skeleton}
          position={[0, -8.498, -3.769]}
          scale={[1.484, 1, 1.484]}
        />
        <mesh
          name="bikini_bottom_strawberry_0"
          castShadow
          receiveShadow
          geometry={nodes.bikini_bottom_strawberry_0.geometry}
          material={materials.Tassels}
          position={[0.253, 0, -3.683]}
          rotation={[Math.PI, 0.024, -Math.PI]}
        />
      </group>
    </group>
  )
}

