export const OCTA_SURGE_TITLE = 'Octa Surge';

export const STORAGE_KEYS = {
  bestScore: 'rachos-fun-octasurge-best-score-v3',
  bestClassic: 'rachos-fun-octasurge-best-classic-v3',
  bestDaily: 'rachos-fun-octasurge-best-daily-v3',
  totalGems: 'rachos-fun-octasurge-total-gems-v3',
  totalBoost: 'rachos-fun-octasurge-total-boost-v3',
  totalShield: 'rachos-fun-octasurge-total-shield-v3',
  totalMagnet: 'rachos-fun-octasurge-total-magnet-v3',
  totalPrism: 'rachos-fun-octasurge-total-prism-v3',
  totalPhase: 'rachos-fun-octasurge-total-phase-v3',
  fxLevel: 'rachos-fun-octasurge-fx-level-v3',
};

export const GAME = {
  faces: 8,
  bottomFace: 6,
  faceStep: (Math.PI * 2) / 8,

  radius: 3.18,
  ringSpacing: 2.05,
  ringDepth: 0.92,
  tileThickness: 0.16,
  bumpHeight: 0.38,
  crusherHeight: 0.68,
  speedPadHeight: 0.08,

  ringBuffer: 80,
  spawnStartZ: -18,
  despawnWorldZ: 4.2,

  playerDepth: 0.56,
  playerPlaneZ: 0,
  playerRadius: 2.58,

  rotationResponse: 8.2,
  inputBufferMs: 82,
  laneFlipCooldownMs: 124,

  classicRunSeconds: 60,
  dailyRunSeconds: 60,

  baseSpeed: 8.8,
  speedRampPerSecond: 0.22,
  speedRampFromScore: 0.0016,
  maxSpeed: 17.6,
  maxInputRateLanePerSecond: 8.8,

  angularAccel: 12.2,
  angularDrag: 6.4,
  maxAngularVelocity: 4.8,
  laneAssistStrength: 3.6,

  comboWindow: 1.85,
  comboStep: 0.09,
  clearScore: 12,
  nearMissScore: 9,
  gemScore: 22,
  boostScore: 50,
  shieldScore: 42,
  magnetScore: 48,
  prismScore: 56,
  phaseScore: 60,
  speedPadScore: 14,

  warmupRings: 14,
  difficultyRampRings: 580,
  densityEarly: 0.2,
  densityMid: 0.48,
  densityLate: 0.78,
  breatherEvery: 9,
  lookaheadRings: 11,
  generatorMaxAttempts: 16,

  collectibleGemChance: 0.3,
  collectibleBoostChance: 0.085,
  collectibleShieldChance: 0.055,
  collectibleMagnetChance: 0.048,
  collectiblePrismChance: 0.04,
  collectiblePhaseChance: 0.032,

  boostDuration: 2.4,
  boostMultiplier: 1.34,
  speedPadDuration: 0.46,
  speedPadMultiplier: 1.22,
  shieldMaxCharges: 2,
  magnetDuration: 4.8,
  magnetLaneReach: 1,
  prismDuration: 5.4,
  prismMultiplier: 1.92,
  phaseDuration: 3.4,

  surgeDrainRate: 44,
  surgeRechargeRate: 14,
  surgeBoostRecharge: 10,
  surgeSlowScale: 0.58,

  cameraBaseFov: 73,
  cameraMaxFovBoost: 10,
  cameraBaseZ: 8.6,
  cameraSpeedZoom: 0.84,
  cameraLookAhead: 22,

  collisionLaneTolerance: 0.22,
  nearMissLaneTolerance: 0.18,
  ringSpinNear: 0.18,
  ringSpinFar: 1.05,
  openWidthNear: 3,
  openWidthFar: 1,
  maxSafeDriftNear: 1,
  maxSafeDriftFar: 2,

  fxPool: 54,
  fxLife: 0.68,
  pulseInterval: 0.52,
};

export const OCTA_PALETTES = [
  {
    id: 'cosmic-cyan',
    bg: '#030913',
    fog: '#09182d',
    tunnelA: '#10294a',
    tunnelB: '#0b1f38',
    rail: '#49e6ff',
    obstacleA: '#f87171',
    obstacleB: '#f97316',
    player: '#f1f7ff',
    playerGlow: '#67e8f9',
  },
  {
    id: 'nova-gold',
    bg: '#140d06',
    fog: '#2d1d0e',
    tunnelA: '#3f2a13',
    tunnelB: '#25190d',
    rail: '#ffd166',
    obstacleA: '#f43f5e',
    obstacleB: '#fb923c',
    player: '#fff8e8',
    playerGlow: '#fbbf24',
  },
  {
    id: 'ion-violet',
    bg: '#0b0718',
    fog: '#1b1138',
    tunnelA: '#2a1e52',
    tunnelB: '#1a1338',
    rail: '#a78bfa',
    obstacleA: '#fb7185',
    obstacleB: '#f472b6',
    player: '#eef2ff',
    playerGlow: '#a78bfa',
  },
  {
    id: 'emerald-vacuum',
    bg: '#04120f',
    fog: '#0f2c25',
    tunnelA: '#18463d',
    tunnelB: '#0e312a',
    rail: '#5eead4',
    obstacleA: '#f87171',
    obstacleB: '#34d399',
    player: '#ecfeff',
    playerGlow: '#2dd4bf',
  },
] as const;
