// src/components/models/Alien.tsx

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Alien.glb --types 
Author: orca_studio (https://sketchfab.com/orca_studio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ugly-face-monster-8c2e666b04f04bcab1e86a2dd3d77ecc
Title: ugly face  monster
*/

import { useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import { useMemo } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial;
  };
};

interface AlienProps extends GroupProps {
  color?: string;
  emissiveIntensity?: number;
}

const DEFAULT_ROTATION: [number, number, number] = [0, -Math.PI / 2, 0];
const TARGET_HEIGHT = 1;

export function Alien({
  color = 'red',
  emissiveIntensity = 0.35,
  rotation,
  scale,
  ...props
}: AlienProps) {
  const { nodes, materials } = useGLTF('/fun/models/alien.glb') as GLTFResult;
  const geometry = nodes.Object_2.geometry;

  const baseScale = useMemo(() => {
    geometry.computeBoundingBox();
    const size = new THREE.Vector3();
    geometry.boundingBox?.getSize(size);
    const height = size.y || 1;
    return TARGET_HEIGHT / height;
  }, [geometry]);

  const resolvedScale = useMemo(() => {
    if (scale == null) return baseScale;
    if (typeof scale === 'number') return scale * baseScale;
    if (Array.isArray(scale)) {
      return [scale[0] * baseScale, scale[1] * baseScale, scale[2] * baseScale] as [number, number, number];
    }
    if (scale instanceof THREE.Vector3) {
      return scale.clone().multiplyScalar(baseScale);
    }
    return baseScale;
  }, [scale, baseScale]);

  // Clone and color the material
  const coloredMaterial = useMemo(() => {
    const mat = materials['Scene_-_Root'].clone() as THREE.MeshStandardMaterial;
    mat.color.set(color);
    mat.emissive.set(color);
    mat.emissiveIntensity = emissiveIntensity;
    mat.needsUpdate = true;
    return mat;
  }, [color, emissiveIntensity, materials]);

  return (
    <group {...props} rotation={rotation ?? DEFAULT_ROTATION} scale={resolvedScale} dispose={null}>
      <mesh geometry={geometry} material={coloredMaterial} />
    </group>
  );
}

useGLTF.preload('/fun/models/alien.glb');
