/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to match working JS version rendering
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';
import * as THREE from 'three';

type ModelProps = JSX.IntrinsicElements['group'];

// Define a type for the GLTF result matching the JS version structure
interface GLTFResult {
  nodes: {
    Bone: THREE.Bone;
    Bone003: THREE.Bone;
    Bone006: THREE.Bone;
    Bone010: THREE.Bone;
    arm: THREE.SkinnedMesh & { skeleton: THREE.Skeleton };
    SM_PingPongPaddle_M_PingPongPaddle_0: THREE.Mesh;
    SM_PingPongPaddle_M_PingPongPaddle_0001: THREE.Mesh;
  };
  materials: {
    glove: THREE.Material;
    'M_PingPongPaddle.001': THREE.Material;
    'M_PingPongPaddle.002': THREE.Material;
  };
}

const PaddlePath = '/fun/models/PaddleHand.glb';

const Model: React.FC<ModelProps> = (props) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(PaddlePath) as unknown as GLTFResult;

  // Render without transforms - matches the working JS version
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <primitive object={nodes.Bone003} />
      <primitive object={nodes.Bone006} />
      <primitive object={nodes.Bone010} />
      <skinnedMesh
        geometry={nodes.arm.geometry}
        material={materials.glove}
        skeleton={nodes.arm.skeleton}
      />
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0.geometry}
        material={materials['M_PingPongPaddle.001']}
      />
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0001.geometry}
        material={materials['M_PingPongPaddle.002']}
      />
    </group>
  );
};

useGLTF.preload(PaddlePath);

export default Model;
