/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';
import * as THREE from 'three';

type ModelProps = JSX.IntrinsicElements['group'];

// Define a type for the GLTF result if you'd like type safety on nodes/materials
// Adjust according to the actual glTF structure of the GLB
interface GLTFResult extends THREE.Group {
  nodes: {
    Bone: THREE.Bone;
    Bone003: THREE.Bone;
    Bone006: THREE.Bone;
    Bone010: THREE.Bone;
    arm: THREE.SkinnedMesh & { skeleton: THREE.Skeleton };
    SM_PingPongPaddle_M_PingPongPaddle_0: THREE.Mesh;
    SM_PingPongPaddle_M_PingPongPaddle_0001: THREE.Mesh;
  };
  materials: {
    glove: THREE.Material;
    M_PingPongPaddle?: THREE.Material;
    'M_PingPongPaddle.001'?: THREE.Material;
    'M_PingPongPaddle.002'?: THREE.Material;
  };
}

const Paddle = '/fun/models/PaddleHand.glb';

const Model: React.FC<ModelProps> = (props) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(Paddle) as unknown as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <primitive object={nodes.Bone003} />
      <primitive object={nodes.Bone006} />
      <primitive object={nodes.Bone010} />
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0.geometry}
        material={materials['M_PingPongPaddle.001'] ?? materials.M_PingPongPaddle}
        position={[-0.37, -0.93, 6.16]}
        rotation={[-1.57, 0, -0.05]}
        scale={[151.73, 151.73, 143.51]}
      />
      <skinnedMesh
        geometry={nodes.arm.geometry}
        material={materials.glove}
        skeleton={nodes.arm.skeleton}
        rotation={[1.88, -0.35, 2.32]}
        scale={[2.97, 2.97, 2.97]}
      />
      <mesh
        geometry={nodes.SM_PingPongPaddle_M_PingPongPaddle_0001.geometry}
        material={materials['M_PingPongPaddle.002'] ?? materials.M_PingPongPaddle}
        position={[-0.37, -0.93, 6.16]}
        rotation={[-1.57, 0, -0.05]}
        scale={[151.73, 151.73, 143.51]}
      />
    </group>
  );
};

useGLTF.preload(Paddle);

export default Model;
