// src/components/models/UFOGames.tsx
/**
 * UFO Ship model for SkyBlitz game
 * Auto-generated by gltfjsx, then manually adjusted for proper orientation
 */

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    UfoPurpleBod1: THREE.Mesh;
    Curve391: THREE.Mesh;
    Curve391_1: THREE.Mesh;
    Curve391_2: THREE.Mesh;
    Curve391_3: THREE.Mesh;
    Curve123: THREE.Mesh;
    Curve123_1: THREE.Mesh;
    Curve123_2: THREE.Mesh;
    Curve123_3: THREE.Mesh;
    Curve123_4: THREE.Mesh;
    Curve123_5: THREE.Mesh;
    Curve123_6: THREE.Mesh;
    Curve123_7: THREE.Mesh;
    Curve123_8: THREE.Mesh;
    Curve123_9: THREE.Mesh;
    Curve123_10: THREE.Mesh;
    Curve123_11: THREE.Mesh;
    Curve123_12: THREE.Mesh;
    Curve123_13: THREE.Mesh;
    Curve123_14: THREE.Mesh;
    Curve123_15: THREE.Mesh;
    Curve123_16: THREE.Mesh;
    Curve123_17: THREE.Mesh;
    Curve123_18: THREE.Mesh;
    Curve123_19: THREE.Mesh;
    Curve123_20: THREE.Mesh;
    Curve123_21: THREE.Mesh;
    Curve123_22: THREE.Mesh;
    Curve123_23: THREE.Mesh;
    Curve123_24: THREE.Mesh;
    Curve123_25: THREE.Mesh;
    Curve123_26: THREE.Mesh;
    Curve123_27: THREE.Mesh;
    Curve123_28: THREE.Mesh;
    Curve123_29: THREE.Mesh;
    Curve123_30: THREE.Mesh;
    Curve123_31: THREE.Mesh;
    Curve123_32: THREE.Mesh;
    Curve063: THREE.Mesh;
    Curve063_1: THREE.Mesh;
    Curve063_2: THREE.Mesh;
    Curve063_3: THREE.Mesh;
    Curve011: THREE.Mesh;
    Curve011_1: THREE.Mesh;
    Curve011_2: THREE.Mesh;
    Curve011_3: THREE.Mesh;
    Curve125: THREE.Mesh;
    Curve125_1: THREE.Mesh;
    Curve125_2: THREE.Mesh;
    Curve125_3: THREE.Mesh;
    Curve127: THREE.Mesh;
    Curve127_1: THREE.Mesh;
    Curve127_2: THREE.Mesh;
    Curve127_3: THREE.Mesh;
    Curve294: THREE.Mesh;
    Curve294_1: THREE.Mesh;
    Curve294_2: THREE.Mesh;
    Curve294_3: THREE.Mesh;
    Curve009: THREE.Mesh;
    Curve009_1: THREE.Mesh;
    Curve009_2: THREE.Mesh;
    Curve009_3: THREE.Mesh;
    ['Cylinder015_02_-_Default_0010']: THREE.Mesh;
    ['Cylinder015_04_-_Default_0']: THREE.Mesh;
    ['Cylinder015_05_-_Default_0012']: THREE.Mesh;
    Object_2008: THREE.Mesh;
    pCube1_PistolTrigger_0002: THREE.Mesh;
    pCylinder7_PistolBody_0002: THREE.Mesh;
    pHelix1_PistolRings_0002: THREE.Mesh;
    pTorus6_PistolType_0002: THREE.Mesh;
    Spinner004: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshStandardMaterial;
    PaletteMaterial005: THREE.MeshStandardMaterial;
    PaletteMaterial006: THREE.MeshStandardMaterial;
    PaletteMaterial007: THREE.MeshStandardMaterial;
    PaletteMaterial008: THREE.MeshStandardMaterial;
    ['02_-_Default']: THREE.MeshStandardMaterial;
    ['04_-_Default']: THREE.MeshStandardMaterial;
    ['05_-_Default']: THREE.MeshStandardMaterial;
    ['PistolTrigger.002']: THREE.MeshStandardMaterial;
    ['PistolBody.002']: THREE.MeshStandardMaterial;
    ['PistolRings.002']: THREE.MeshStandardMaterial;
    ['PistolType.002']: THREE.MeshStandardMaterial;
    material_0: THREE.MeshBasicMaterial;
    ['material_0.004']: THREE.MeshBasicMaterial;
    [key: string]: THREE.Material | undefined;
  };
};

type UfoShipProps = JSX.IntrinsicElements['group'] & {
  playerRef: React.MutableRefObject<THREE.Group | null>;
  bodyRef?: React.MutableRefObject<THREE.Group | null>;
};

const UfoShip: React.FC<UfoShipProps> = ({ playerRef, bodyRef, ...props }) => {
  const localBodyRef = useRef<THREE.Group>(null);
  const actualBodyRef = bodyRef || localBodyRef;
  const { nodes, materials } = useGLTF('/fun/models/UFOgames.glb') as GLTFResult;

  // Crosshair materials
  const crossMaterial = new THREE.MeshBasicMaterial({ color: 'hotpink', fog: false });
  const laserMaterial = new THREE.MeshBasicMaterial({ color: 'lightgreen' });

  return (
    <group ref={playerRef} {...props} dispose={null}>
      {/* Rotate 180 degrees on Y axis so UFO faces forward (into -Z direction) */}
      <group ref={actualBodyRef} rotation={[0, Math.PI, 0]}>
        {/* Crosshair */}
        <group scale={0.005} position={[0, 0, -2]}>
          <mesh renderOrder={1000} material={crossMaterial}>
            <boxGeometry args={[20, 2, 2]} />
          </mesh>
          <mesh renderOrder={1000} material={crossMaterial}>
            <boxGeometry args={[2, 20, 2]} />
          </mesh>
        </group>

        {/* Target reticle */}
        <group scale={0.005} position={[0, 0, -3]}>
          <mesh position={[0, 20, 0]} renderOrder={1000} material={crossMaterial}>
            <boxGeometry args={[40, 2, 2]} />
          </mesh>
          <mesh position={[0, -20, 0]} renderOrder={1000} material={crossMaterial}>
            <boxGeometry args={[40, 2, 2]} />
          </mesh>
          <mesh position={[20, 0, 0]} renderOrder={1000} material={crossMaterial}>
            <boxGeometry args={[2, 40, 2]} />
          </mesh>
          <mesh position={[-20, 0, 0]} renderOrder={1000} material={crossMaterial}>
            <boxGeometry args={[2, 40, 2]} />
          </mesh>
        </group>

        {/* UFO Model - matching original UFOgames.js positions and rotations */}
        <group position={[0.94, -1.01, 0.12]} rotation={[1.57, 0, 0]} scale={[0.57, 0.94, 0.57]}>
          {/* AlienOrange */}
          <group name="AlienOrange" position={[-2.65, 0.04, -1.47]} rotation={[0, 0, -Math.PI]} scale={[7.63, 1, 7.63]}>
            <mesh geometry={nodes.Curve391.geometry} material={nodes.Curve391.material} />
            <mesh geometry={nodes.Curve391_1.geometry} material={materials.PaletteMaterial002} />
            <mesh geometry={nodes.Curve391_2.geometry} material={nodes.Curve391_2.material} />
            <mesh geometry={nodes.Curve391_3.geometry} material={nodes.Curve391_3.material} />
          </group>
          
          {/* AlienPurple */}
          <group name="AlienPurple" position={[-0.74, 0.01, -1.59]} rotation={[0, 0, -3.14]} scale={[7.63, 1, 7.63]}>
            <mesh geometry={nodes.Curve123.geometry} material={nodes.Curve123.material} />
            <mesh geometry={nodes.Curve123_1.geometry} material={nodes.Curve123_1.material} />
            <mesh geometry={nodes.Curve123_2.geometry} material={materials.PaletteMaterial003} />
            <mesh geometry={nodes.Curve123_3.geometry} material={nodes.Curve123_3.material} />
            <mesh geometry={nodes.Curve123_4.geometry} material={nodes.Curve123_4.material} />
            <mesh geometry={nodes.Curve123_5.geometry} material={nodes.Curve123_5.material} />
            <mesh geometry={nodes.Curve123_6.geometry} material={nodes.Curve123_6.material} />
            <mesh geometry={nodes.Curve123_7.geometry} material={nodes.Curve123_7.material} />
            <mesh geometry={nodes.Curve123_8.geometry} material={nodes.Curve123_8.material} />
            <mesh geometry={nodes.Curve123_9.geometry} material={nodes.Curve123_9.material} />
            <mesh geometry={nodes.Curve123_10.geometry} material={nodes.Curve123_10.material} />
            <mesh geometry={nodes.Curve123_11.geometry} material={nodes.Curve123_11.material} />
            <mesh geometry={nodes.Curve123_12.geometry} material={nodes.Curve123_12.material} />
            <mesh geometry={nodes.Curve123_13.geometry} material={nodes.Curve123_13.material} />
            <mesh geometry={nodes.Curve123_14.geometry} material={nodes.Curve123_14.material} />
            <mesh geometry={nodes.Curve123_15.geometry} material={nodes.Curve123_15.material} />
            <mesh geometry={nodes.Curve123_16.geometry} material={nodes.Curve123_16.material} />
            <mesh geometry={nodes.Curve123_17.geometry} material={nodes.Curve123_17.material} />
            <mesh geometry={nodes.Curve123_18.geometry} material={nodes.Curve123_18.material} />
            <mesh geometry={nodes.Curve123_19.geometry} material={nodes.Curve123_19.material} />
            <mesh geometry={nodes.Curve123_20.geometry} material={nodes.Curve123_20.material} />
            <mesh geometry={nodes.Curve123_21.geometry} material={nodes.Curve123_21.material} />
            <mesh geometry={nodes.Curve123_22.geometry} material={nodes.Curve123_22.material} />
            <mesh geometry={nodes.Curve123_23.geometry} material={nodes.Curve123_23.material} />
            <mesh geometry={nodes.Curve123_24.geometry} material={nodes.Curve123_24.material} />
            <mesh geometry={nodes.Curve123_25.geometry} material={nodes.Curve123_25.material} />
            <mesh geometry={nodes.Curve123_26.geometry} material={nodes.Curve123_26.material} />
            <mesh geometry={nodes.Curve123_27.geometry} material={nodes.Curve123_27.material} />
            <mesh geometry={nodes.Curve123_28.geometry} material={nodes.Curve123_28.material} />
            <mesh geometry={nodes.Curve123_29.geometry} material={nodes.Curve123_29.material} />
            <mesh geometry={nodes.Curve123_30.geometry} material={nodes.Curve123_30.material} />
            <mesh geometry={nodes.Curve123_31.geometry} material={nodes.Curve123_31.material} />
            <mesh geometry={nodes.Curve123_32.geometry} material={nodes.Curve123_32.material} />
          </group>
          
          {/* AlienRLeft */}
          <group name="AlienRLeft" position={[-1.66, -0.18, -2.16]} rotation={[1.57, 0, -3.14]} scale={[3, 0.11, 3]}>
            <mesh geometry={nodes.Curve063.geometry} material={nodes.Curve063.material} />
            <mesh geometry={nodes.Curve063_1.geometry} material={nodes.Curve063_1.material} />
            <mesh geometry={nodes.Curve063_2.geometry} material={nodes.Curve063_2.material} />
            <mesh geometry={nodes.Curve063_3.geometry} material={nodes.Curve063_3.material} />
          </group>
          
          {/* AlienRMiddle */}
          <group name="AlienRMiddle" position={[-1.66, -0.18, -2.16]} rotation={[0, 0, Math.PI]} scale={[3, 0.11, 3]}>
            <mesh geometry={nodes.Curve011.geometry} material={nodes.Curve011.material} />
            <mesh geometry={nodes.Curve011_1.geometry} material={nodes.Curve011_1.material} />
            <mesh geometry={nodes.Curve011_2.geometry} material={nodes.Curve011_2.material} />
            <mesh geometry={nodes.Curve011_3.geometry} material={nodes.Curve011_3.material} />
          </group>
          
          {/* AlienRRight */}
          <group name="AlienRRight" position={[-1.66, -0.18, -2.16]} rotation={[0, 0, -Math.PI]} scale={[3, 0.11, 3]}>
            <mesh geometry={nodes.Curve125.geometry} material={nodes.Curve125.material} />
            <mesh geometry={nodes.Curve125_1.geometry} material={nodes.Curve125_1.material} />
            <mesh geometry={nodes.Curve125_2.geometry} material={nodes.Curve125_2.material} />
            <mesh geometry={nodes.Curve125_3.geometry} material={nodes.Curve125_3.material} />
          </group>
        </group>
        
        {/* Green aliens group */}
        <group position={[1.66, 2.46, 0.02]} rotation={[-1.69, 0, 0]}>
          {/* AliensGreenLeft */}
          <group name="AliensGreenLeft" position={[-1.68, 0.2, -2.17]} rotation={[0, -0.26, -3.14]} scale={[2.85, 0.29, 2.84]}>
            <mesh geometry={nodes.Curve127.geometry} material={nodes.Curve127.material} />
            <mesh geometry={nodes.Curve127_1.geometry} material={nodes.Curve127_1.material} />
            <mesh geometry={nodes.Curve127_2.geometry} material={nodes.Curve127_2.material} />
            <mesh geometry={nodes.Curve127_3.geometry} material={nodes.Curve127_3.material} />
          </group>
          
          {/* AliensGreenMiddle */}
          <group name="AliensGreenMiddle" position={[-1.67, 0.17, -2.24]} rotation={[0, -Math.PI / 4, -3.14]} scale={[3.88, 0.24, 2.84]}>
            <mesh geometry={nodes.Curve294.geometry} material={nodes.Curve294.material} />
            <mesh geometry={nodes.Curve294_1.geometry} material={nodes.Curve294_1.material} />
            <mesh geometry={nodes.Curve294_2.geometry} material={nodes.Curve294_2.material} />
            <mesh geometry={nodes.Curve294_3.geometry} material={nodes.Curve294_3.material} />
          </group>
          
          {/* AliensGreenRight */}
          <group name="AliensGreenRight" position={[-1.68, 0.2, -2.17]} rotation={[3.14, -0.29, -3.14]} scale={[3, 0.18, 4.57]}>
            <mesh geometry={nodes.Curve009.geometry} material={nodes.Curve009.material} />
            <mesh geometry={nodes.Curve009_1.geometry} material={nodes.Curve009_1.material} />
            <mesh geometry={nodes.Curve009_2.geometry} material={nodes.Curve009_2.material} />
            <mesh geometry={nodes.Curve009_3.geometry} material={nodes.Curve009_3.material} />
          </group>
        </group>
        
        {/* UFO Body */}
        <mesh
          geometry={nodes.UfoPurpleBod1.geometry}
          material={nodes.UfoPurpleBod1.material}
          position={[1.25, -1.16, 0.09]}
          rotation={[1.57, 0, -3.14]}
          scale={[4.88, 0.52, 4.88]}
        />
        
        {/* Engine/Detail parts */}
        <mesh
          geometry={nodes['Cylinder015_02_-_Default_0010'].geometry}
          material={materials['02_-_Default']}
          position={[-0.01, -0.74, -0.28]}
          rotation={[0, -0.01, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          geometry={nodes['Cylinder015_04_-_Default_0'].geometry}
          material={materials['04_-_Default']}
          position={[-0.01, -0.74, -0.28]}
          rotation={[0, -0.01, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          geometry={nodes['Cylinder015_05_-_Default_0012'].geometry}
          material={materials['05_-_Default']}
          position={[-0.01, -0.74, -0.28]}
          rotation={[0, -0.01, Math.PI / 2]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          geometry={nodes.Object_2008.geometry}
          material={materials.material_0 || materials.PaletteMaterial001}
          position={[-0.01, -0.87, 0.1]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[0.03, 0.02, 0.03]}
        />
        
        {/* Pistol/Weapon parts */}
        <mesh
          geometry={nodes.pCube1_PistolTrigger_0002.geometry}
          material={materials['PistolTrigger.002']}
          position={[0.21, -0.81, 0.51]}
          rotation={[1.89, 1.54, -1.94]}
          scale={[0.01, 0.04, 0.01]}
        />
        <mesh
          geometry={nodes.pCylinder7_PistolBody_0002.geometry}
          material={materials['PistolBody.002']}
          position={[0.21, -0.78, 0.53]}
          rotation={[1.89, 1.54, -1.94]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          geometry={nodes.pHelix1_PistolRings_0002.geometry}
          material={materials['PistolRings.002']}
          position={[0.21, -0.72, 0.66]}
          rotation={[1.89, 1.54, 2.77]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          geometry={nodes.pTorus6_PistolType_0002.geometry}
          material={materials['PistolType.002']}
          position={[0.25, -0.73, 0.47]}
          rotation={[1.52, -0.08, -1.58]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          geometry={nodes.Spinner004.geometry}
          material={materials['material_0.004']}
          position={[-1, -0.76, -0.4]}
          rotation={[1.53, -1.44, 3.12]}
          scale={[0, 0.02, 0.01]}
        />
      </group>
    </group>
  );
};

useGLTF.preload('/fun/models/UFOgames.glb');

export default UfoShip;
