/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Kitchen.glb --types 
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Kitchen_1: THREE.Mesh;
    Cube117_muro_0001: THREE.Mesh;
    Cube117_muro_0001_1: THREE.Mesh;
    Cube117_muro_0001_2: THREE.Mesh;
    Cube117_muro_0001_3: THREE.Mesh;
    Cube117_muro_0001_4: THREE.Mesh;
    Cube117_muro_0001_5: THREE.Mesh;
    Cube117_muro_0001_6: THREE.Mesh;
    Cube117_muro_0001_7: THREE.Mesh;
    Cube117_muro_0001_8: THREE.Mesh;
  };
  materials: {
    ['Material.030']: THREE.MeshStandardMaterial;
    ['basic_1.002']: THREE.MeshStandardMaterial;
    ['Material.023']: THREE.MeshStandardMaterial;
    ['darck.002']: THREE.MeshStandardMaterial;
    ['darck_whitr.002']: THREE.MeshStandardMaterial;
    ['glosi.002']: THREE.MeshStandardMaterial;
    ['other_1.002']: THREE.MeshStandardMaterial;
    ['other_2.002']: THREE.MeshStandardMaterial;
    ['basic_2.002']: THREE.MeshStandardMaterial;
    ['bread.002']: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function KitchenSet(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/mainInterest/Kitchen.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Kitchen_1.geometry}
        material={materials['Material.030']}
        position={[-10.988, 3.688, 29.51]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[30.591, 34.534, 43.537]}
      >
        <group position={[0.359, -1.277, -0.085]} scale={2.561}>
          <mesh
            geometry={nodes.Cube117_muro_0001.geometry}
            material={materials['basic_1.002']}
          />
          <mesh
            geometry={nodes.Cube117_muro_0001_1.geometry}
            material={materials['Material.023']}
          />
          <mesh
            geometry={nodes.Cube117_muro_0001_2.geometry}
            material={materials['darck.002']}
          />
          <mesh
            geometry={nodes.Cube117_muro_0001_3.geometry}
            material={materials['darck_whitr.002']}
          />
          <mesh
            geometry={nodes.Cube117_muro_0001_4.geometry}
            material={materials['glosi.002']}
          />
          <mesh
            geometry={nodes.Cube117_muro_0001_5.geometry}
            material={materials['other_1.002']}
          />
          <mesh
            geometry={nodes.Cube117_muro_0001_6.geometry}
            material={materials['other_2.002']}
          />
          <mesh
            geometry={nodes.Cube117_muro_0001_7.geometry}
            material={materials['basic_2.002']}
          />
          <mesh
            geometry={nodes.Cube117_muro_0001_8.geometry}
            material={materials['bread.002']}
          />
        </group>
      </mesh>
    </group>
  );
}
