/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 PricklyPearCactus.glb --types 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_0: THREE.Mesh
    Object_0_1: THREE.Mesh
    Object_0_2: THREE.Mesh
  }
  materials: {
    main: THREE.MeshBasicMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function PricklyPearCactus(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/mainInterest/PricklyPearCactus.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.025, 0.109]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.259, 1.481, 2.167]}>
        <mesh geometry={nodes.Object_0.geometry} material={materials.main} />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Object_0_2.geometry} material={materials['Material.040']} />
      </group>
    </group>
  )
}

