/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 PuzzleShelf.glb --types 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    PuzzleShelf001: THREE.Mesh
    PuzzleShelf001_1: THREE.Mesh
    PuzzleShelf001_2: THREE.Mesh
    PuzzleShelf001_3: THREE.Mesh
    PuzzleShelf001_4: THREE.Mesh
    PuzzleShelf001_5: THREE.Mesh
    PuzzleShelf001_6: THREE.Mesh
  }
  materials: {
    ['Sticker_SPC-SG.001']: THREE.MeshStandardMaterial
    ['baked.001']: THREE.MeshStandardMaterial
    ['RubixCube.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    ['Mtl2.001']: THREE.MeshStandardMaterial
    ['material.004']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function PuzzleShelf(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/mainInterest/PuzzleShelf.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[48.953, -16.783, 26.652]} rotation={[-Math.PI / 2, 0, 0]} scale={[109.552, 123.675, 155.915]}>
        <mesh geometry={nodes.PuzzleShelf001.geometry} material={materials['Sticker_SPC-SG.001']} />
        <mesh geometry={nodes.PuzzleShelf001_1.geometry} material={materials['baked.001']} />
        <mesh geometry={nodes.PuzzleShelf001_2.geometry} material={materials['RubixCube.001']} />
        <mesh geometry={nodes.PuzzleShelf001_3.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.PuzzleShelf001_4.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.PuzzleShelf001_5.geometry} material={materials['Mtl2.001']} />
        <mesh geometry={nodes.PuzzleShelf001_6.geometry} material={materials['material.004']} />
      </group>
    </group>
  )
}

