import type { Arena } from './types';

export const ARENAS: Arena[] = [
  {
    id: 'classic',
    name: 'Classic Green',
    background: '#f4f4f4',
    skyTop: '#f8f8f8',
    skyBottom: '#efefef',
    skyGlow: '#ffffff',
    fog: { color: '#f0f0f0', near: 8, far: 40 },
    lights: { ambient: 0.84, directional: 1.1, point: 0.25 },
    pathHue: 0.33,
    pathSat: 0.72,
    pathLight: 0.61,
    gemHue: 0.1,
    spikeHue: 0.08,
    spikeSat: 0.85,
    spikeLight: 0.5,
    cubeColor: '#d9f3df',
    cubeEmissive: '#e8f8eb',
    playerColor: '#222126',
  },
  {
    id: 'mint',
    name: 'Mint Pop',
    background: '#eefcf7',
    skyTop: '#f6fffd',
    skyBottom: '#e9fbf4',
    skyGlow: '#f8fff4',
    fog: { color: '#ebf8f2', near: 7, far: 42 },
    lights: { ambient: 0.82, directional: 1.06, point: 0.24 },
    pathHue: 0.43,
    pathSat: 0.62,
    pathLight: 0.62,
    gemHue: 0.1,
    spikeHue: 0.08,
    spikeSat: 0.85,
    spikeLight: 0.5,
    cubeColor: '#d7f6ea',
    cubeEmissive: '#e3fff7',
    playerColor: '#25302f',
  },
  {
    id: 'aqua',
    name: 'Aqua Pop',
    background: '#eff8ff',
    skyTop: '#f5fbff',
    skyBottom: '#e7f4ff',
    skyGlow: '#f0ffff',
    fog: { color: '#e7f2ff', near: 7, far: 44 },
    lights: { ambient: 0.8, directional: 1.02, point: 0.22 },
    pathHue: 0.54,
    pathSat: 0.68,
    pathLight: 0.6,
    gemHue: 0.11,
    spikeHue: 0.08,
    spikeSat: 0.85,
    spikeLight: 0.5,
    cubeColor: '#d2ebff',
    cubeEmissive: '#e5f7ff',
    playerColor: '#0f1a24',
  },
  {
    id: 'lemon',
    name: 'Lemon',
    background: '#fcfbe9',
    skyTop: '#fffef2',
    skyBottom: '#f4f2d8',
    skyGlow: '#fffde8',
    fog: { color: '#f7f5e0', near: 7, far: 42 },
    lights: { ambient: 0.83, directional: 1.04, point: 0.22 },
    pathHue: 0.17,
    pathSat: 0.65,
    pathLight: 0.64,
    gemHue: 0.09,
    spikeHue: 0.08,
    spikeSat: 0.85,
    spikeLight: 0.5,
    cubeColor: '#f2f0c8',
    cubeEmissive: '#fff5ca',
    playerColor: '#292622',
  },
  {
    id: 'coral',
    name: 'Coral',
    background: '#fff3ee',
    skyTop: '#fff9f7',
    skyBottom: '#ffece1',
    skyGlow: '#fff8ef',
    fog: { color: '#ffece5', near: 7, far: 42 },
    lights: { ambient: 0.82, directional: 1.05, point: 0.22 },
    pathHue: 0.02,
    pathSat: 0.71,
    pathLight: 0.62,
    gemHue: 0.5,
    spikeHue: 0.08,
    spikeSat: 0.85,
    spikeLight: 0.5,
    cubeColor: '#ffe1d3',
    cubeEmissive: '#ffeed7',
    playerColor: '#2a2321',
  },
  {
    id: 'violet',
    name: 'Violet',
    background: '#f5f0ff',
    skyTop: '#fbf7ff',
    skyBottom: '#eee5ff',
    skyGlow: '#fff8ff',
    fog: { color: '#eee7ff', near: 7, far: 42 },
    lights: { ambient: 0.82, directional: 1.0, point: 0.22 },
    pathHue: 0.76,
    pathSat: 0.6,
    pathLight: 0.62,
    gemHue: 0.11,
    spikeHue: 0.08,
    spikeSat: 0.85,
    spikeLight: 0.5,
    cubeColor: '#e4d9ff',
    cubeEmissive: '#efe8ff',
    playerColor: '#25212d',
  },
];
