import type { Arena } from './types';

export const ARENAS: Arena[] = [
  {
    id: 'cotton',
    name: 'Cotton Candy',
    background: '#f9f1ff',
    skyTop: '#b8f6ff',
    skyBottom: '#ffd5f3',
    skyGlow: '#fff4c9',
    fog: { color: '#f8e9ff', near: 8, far: 44 },
    lights: { ambient: 0.7, directional: 1.05, point: 0.45 },
    pathHue: 0.92,
    pathSat: 0.62,
    pathLight: 0.6,
    gemHue: 0.12,
    spikeHue: 0.02,
    spikeSat: 0.75,
    spikeLight: 0.5,
    cubeColor: '#a8f0ff',
    cubeEmissive: '#ffe0f4',
    playerColor: '#1b1b1d',
  },
  {
    id: 'sunset',
    name: 'Sunset Run',
    background: '#ffe6da',
    skyTop: '#ffd6a5',
    skyBottom: '#ff8dc4',
    skyGlow: '#fff1d0',
    fog: { color: '#ffd6d6', near: 7, far: 40 },
    lights: { ambient: 0.65, directional: 1.0, point: 0.4 },
    pathHue: 0.96,
    pathSat: 0.58,
    pathLight: 0.52,
    gemHue: 0.1,
    spikeHue: 0.0,
    spikeSat: 0.75,
    spikeLight: 0.5,
    cubeColor: '#ffc6b5',
    cubeEmissive: '#ffb0d4',
    playerColor: '#2a1b24',
  },
  {
    id: 'aqua',
    name: 'Aqua Drift',
    background: '#e8fbff',
    skyTop: '#bafce1',
    skyBottom: '#88b9ff',
    skyGlow: '#d5fff2',
    fog: { color: '#d9f3ff', near: 7, far: 46 },
    lights: { ambient: 0.62, directional: 0.92, point: 0.35 },
    pathHue: 0.52,
    pathSat: 0.5,
    pathLight: 0.56,
    gemHue: 0.13,
    spikeHue: 0.02,
    spikeSat: 0.7,
    spikeLight: 0.52,
    cubeColor: '#aee8ff',
    cubeEmissive: '#b9ffe5',
    playerColor: '#0f1a24',
  },
  {
    id: 'violet',
    name: 'Violet Halo',
    background: '#1b0d3c',
    skyTop: '#7f7bff',
    skyBottom: '#1b0d3c',
    skyGlow: '#b9a0ff',
    fog: { color: '#2a1b52', near: 6, far: 36 },
    lights: { ambient: 0.45, directional: 0.85, point: 0.6 },
    pathHue: 0.74,
    pathSat: 0.55,
    pathLight: 0.45,
    gemHue: 0.15,
    spikeHue: 0.02,
    spikeSat: 0.7,
    spikeLight: 0.5,
    cubeColor: '#6f6cff',
    cubeEmissive: '#b094ff',
    playerColor: '#f7f2ff',
  },
  {
    id: 'ember',
    name: 'Ember Forge',
    background: '#2a0b0d',
    skyTop: '#ffb199',
    skyBottom: '#2a0b0d',
    skyGlow: '#ffcf91',
    fog: { color: '#2a0b0d', near: 5, far: 34 },
    lights: { ambient: 0.38, directional: 0.85, point: 0.65 },
    pathHue: 0.03,
    pathSat: 0.68,
    pathLight: 0.44,
    gemHue: 0.52,
    spikeHue: 0.02,
    spikeSat: 0.75,
    spikeLight: 0.5,
    cubeColor: '#ff9f8a',
    cubeEmissive: '#ffcb7d',
    playerColor: '#f3efe6',
  },
  {
    id: 'mint',
    name: 'Mint Bloom',
    background: '#e9fff7',
    skyTop: '#d6fff3',
    skyBottom: '#b9f0ff',
    skyGlow: '#f2ffe5',
    fog: { color: '#defbf0', near: 7, far: 44 },
    lights: { ambient: 0.66, directional: 0.95, point: 0.35 },
    pathHue: 0.44,
    pathSat: 0.5,
    pathLight: 0.58,
    gemHue: 0.12,
    spikeHue: 0.02,
    spikeSat: 0.7,
    spikeLight: 0.52,
    cubeColor: '#b8ffd9',
    cubeEmissive: '#c2f0ff',
    playerColor: '#132026',
  },
];
