export const CFG = {
  STEPS_PER_CHUNK: 48,
  KEEP_CHUNKS_BEHIND: 2,
  KEEP_CHUNKS_AHEAD: 5,
  FIXED_DT: 1 / 120,
  MAX_FRAME_STEPS: 8,

  STEP: {
    width: 2.24,
    thickness: 0.62,
    riseCalmMin: 0.14,
    riseCalmMax: 0.22,
    riseTensionMin: 0.3,
    riseTensionMax: 0.44,
    lengthMin: 1.25,
    lengthMax: 2.18,
    turnChanceCalm: 0.05,
    turnChanceTension: 0.14,
    turnSegmentMin: 3,
    turnSegmentMax: 8,
    turnGentleRange: 0.08,
    turnHardRange: 0.26,
    hardTurnChance: 0.12,
    headingJitter: 0.012,
    calmRunMin: 12,
    calmRunMax: 22,
    tensionRunMin: 3,
    tensionRunMax: 6,
    gapChance: 0.075,
    gapChanceCalmMultiplier: 0.3,
    gapChanceTensionBoost: 0.09,
    gapLengthMin: 0.72,
    gapLengthMax: 1.28,
    demandingRiseThreshold: 0.22,
    safeRiseMaxAfterDemanding: 0.18,
    demandingCooldownMin: 2,
    demandingCooldownMax: 4,
    gemChance: 0.2,
    pathRadiusMin: 4.1,
    pathRadiusMax: 5.9,
    pathSoftRadiusRatio: 0.82,
    radialPull: 0.24,
    curvedTurnRate: 0.06,
    curvedBoundaryGain: 0.42,
    spiralTurnRate: 0.9,
    spiralInwardDrift: 0.26,
    spiralOutwardDrift: 0.2,
    spiralMinRadius: 3.5,
    spiralMaxRadius: 8.2,
  },

  OBSTACLES: {
    chanceMin: 0.12,
    chanceMax: 0.33,
    minSpacingMin: 2,
    minSpacingMax: 5,
    hitWindow: 0.3,
    nearMissEpsilon: 0.14,
    wallHeightMin: 0.9,
    wallHeightMax: 1.4,
    spikeHeightMin: 0.45,
    spikeHeightMax: 0.75,
    barHeightMin: 0.48,
    barHeightMax: 0.9,
    barThicknessMin: 0.2,
    barThicknessMax: 0.32,
  },

  PLAYER: {
    radius: 0.28,
    forwardSpeed: 3.8,
    jumpVel: 6.6,
    gravity: -18.0,
    landingSlack: 0.16,
    coyoteMs: 90,
    bufferMs: 90,
    fallKillOffset: 6.0,
  },

  DIFFICULTY: {
    speedPer100Steps: 0.35,
    maxSpeed: 6.5,
    gapChanceMax: 0.14,
  },

  CAMERA: {
    sideDistance: 5.8,
    backDistance: 2.9,
    minOrbitRadius: 8.2,
    maxOrbitRadius: 11.8,
    yOffset: 5.9,
    lookAhead: 3.6,
    lookOffset: 0.52,
    followSharpness: 8.8,
    turnSharpness: 8.0,
    fovDesktop: 46,
    fovMobile: 52,
    occlusionRadius: 5.0,
    occlusionLift: 2.25,
    occlusionPushOut: 2.15,
    lookCenterBias: 0.22,
  },

  RENDER: {
    tube: {
      radiusScale: 0.44,
      radiusScaleHybrid: 0.2,
      radialSegmentsLow: 8,
      radialSegmentsHigh: 12,
      stepsPerPointLow: 4,
      stepsPerPointHigh: 8,
    },
    ribbon: {
      cornerRadius: 0.18,
      stepsPerPointLow: 5,
      stepsPerPointHigh: 9,
    },
  },

  COMBO: {
    windowMs: 2100,
    stepEvery: 3,
    maxMultiplier: 6,
    gapBonus: 24,
    obstacleBonus: 32,
    nearMissBonus: 14,
    gemBonus: 8,
  },

  ARENA: {
    swapMinSteps: 65,
    swapMaxSteps: 110,
  },

  GEM: {
    pickupRadius: 0.62,
  },
} as const;
