export const CFG = {
  STEPS_PER_CHUNK: 48,
  KEEP_CHUNKS_BEHIND: 2,
  KEEP_CHUNKS_AHEAD: 5,
  FIXED_DT: 1 / 120,
  MAX_FRAME_STEPS: 8,

  STEP: {
    width: 2.24,
    riseCalmMin: 0.14,
    riseCalmMax: 0.22,
    riseTensionMin: 0.3,
    riseTensionMax: 0.44,
    lengthMin: 1.25,
    lengthMax: 2.18,
    turnChanceCalm: 0.09,
    turnChanceTension: 0.21,
    turnSegmentMin: 2,
    turnSegmentMax: 7,
    turnGentleRange: 0.12,
    turnHardRange: 0.48,
    hardTurnChance: 0.2,
    headingJitter: 0.028,
    calmRunMin: 12,
    calmRunMax: 22,
    tensionRunMin: 3,
    tensionRunMax: 6,
    gapChance: 0.075,
    gapChanceCalmMultiplier: 0.3,
    gapChanceTensionBoost: 0.09,
    gapLengthMin: 0.72,
    gapLengthMax: 1.28,
    spikeChanceCalm: 0.03,
    spikeChanceTension: 0.12,
    spikeClearance: 0.34,
    spikeAlongMin: 0.44,
    spikeAlongMax: 0.72,
    demandingRiseThreshold: 0.22,
    safeRiseMaxAfterDemanding: 0.18,
    demandingCooldownMin: 2,
    demandingCooldownMax: 4,
    spikeBlockRiseFromPrev: 0.2,
    spikeMaxRiseWithNext: 0.16,
    spikeCooldownMin: 2,
    spikeCooldownMax: 5,
    gemChance: 0.2,
    pathRadiusMin: 4.1,
    pathRadiusMax: 5.9,
    radialPull: 0.24,
  },

  PLAYER: {
    radius: 0.28,
    forwardSpeed: 3.8,
    jumpVel: 6.6,
    gravity: -18.0,
    landingSlack: 0.16,
    coyoteMs: 90,
    bufferMs: 90,
    fallKillOffset: 6.0,
  },

  DIFFICULTY: {
    speedPer100Steps: 0.35,
    maxSpeed: 6.5,
    gapChanceMax: 0.14,
  },

  CAMERA: {
    sideDistance: 8.8,
    backDistance: 2.2,
    minOrbitRadius: 8.4,
    maxOrbitRadius: 12.4,
    yOffset: 5.2,
    lookAhead: 3.6,
    lookOffset: 0.42,
    followSharpness: 8.8,
    turnSharpness: 8.0,
    fovDesktop: 46,
    fovMobile: 52,
    occlusionRadius: 3.6,
    occlusionLift: 1.7,
    occlusionPushOut: 1.4,
    lookCenterBias: 0.22,
  },

  ARENA: {
    swapMinSteps: 65,
    swapMaxSteps: 110,
  },

  GEM: {
    pickupRadius: 0.62,
  },
} as const;
