/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/RachosRoomMain.glb --types -o src/app/myRoom/components/RachosRoomMainGenerated.tsx 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Mesh_40001: THREE.Mesh;
    Mesh_40002: THREE.Mesh;
    Mesh_41001: THREE.Mesh;
    Mesh_42001_1: THREE.Mesh;
    Mesh_42001_2: THREE.Mesh;
    Mesh_42001_3: THREE.Mesh;
    Mesh_42001_4: THREE.Mesh;
    Mesh_42001_5: THREE.Mesh;
    Mesh_42001_6: THREE.Mesh;
    Mesh_43001: THREE.Mesh;
    Mesh_43002: THREE.Mesh;
    Mesh_43003: THREE.Mesh;
    Mesh_43004: THREE.Mesh;
    MeBitSanta002_1: THREE.Mesh;
    MeBitSanta002_2: THREE.Mesh;
    MeBitSanta002_3: THREE.Mesh;
    Mesh_0001: THREE.Mesh;
    Mesh_0001_1: THREE.Mesh;
    Mesh_0001_2: THREE.Mesh;
    Mesh_0001_3: THREE.Mesh;
    Mesh_0001_4: THREE.Mesh;
    Mesh_0001_5: THREE.Mesh;
    Mesh_0001_6: THREE.Mesh;
    Mesh_0001_7: THREE.Mesh;
    Mesh_89005: THREE.Mesh;
    Mesh_89005_1: THREE.Mesh;
    Mesh_89005_2: THREE.Mesh;
    Mesh_89005_3: THREE.Mesh;
    Mesh_89005_4: THREE.Mesh;
    Mesh_36001: THREE.Mesh;
    Mesh_36001_1: THREE.Mesh;
    Mesh_36001_2: THREE.Mesh;
    Mesh_36001_3: THREE.Mesh;
    Mesh_36001_4: THREE.Mesh;
    Mesh_36001_5: THREE.Mesh;
    Mesh_36001_6: THREE.Mesh;
    Mesh_36001_7: THREE.Mesh;
    Mesh_36001_8: THREE.Mesh;
    Mesh_36001_9: THREE.Mesh;
    Mesh_36001_10: THREE.Mesh;
    Mesh_36001_11: THREE.Mesh;
    Mesh_36001_12: THREE.Mesh;
    Mesh_36001_13: THREE.Mesh;
    Mesh_36001_14: THREE.Mesh;
    Mesh_36001_15: THREE.Mesh;
    Mesh_36001_16: THREE.Mesh;
    Mesh_36001_17: THREE.Mesh;
    Mesh_36001_18: THREE.Mesh;
    Mesh_36001_19: THREE.Mesh;
    Mesh_36001_20: THREE.Mesh;
    Mesh_36001_21: THREE.Mesh;
    Mesh_36001_22: THREE.Mesh;
    Mesh_36001_23: THREE.Mesh;
    Mesh_36001_24: THREE.Mesh;
    Mesh_36001_25: THREE.Mesh;
    RoomFloor: THREE.Mesh;
    TVMonitor: THREE.Mesh;
    Computer_Monitor: THREE.Mesh;
    KitchenSet: THREE.Mesh;
    Mesh_36017: THREE.Mesh;
    Mesh_36017_1: THREE.Mesh;
    Mesh_36017_2: THREE.Mesh;
    Mesh_44002: THREE.Mesh;
    Mesh_44002_1: THREE.Mesh;
    Mesh_44002_2: THREE.Mesh;
    Mesh_39002: THREE.Mesh;
    Mesh_39002_1: THREE.Mesh;
    Mesh_39002_2: THREE.Mesh;
    Mesh_39002_3: THREE.Mesh;
    Mesh_39002_4: THREE.Mesh;
    Mesh_39002_5: THREE.Mesh;
    Mesh_39002_6: THREE.Mesh;
    Mesh_39002_7: THREE.Mesh;
    Mesh_39002_8: THREE.Mesh;
    Mesh_39002_9: THREE.Mesh;
    Mesh_39002_10: THREE.Mesh;
    armHoles_LP_UV_checker_0002: THREE.Mesh;
    armHoles_LP_UV_checker_0002_1: THREE.Mesh;
    Mesh_89006: THREE.Mesh;
    Mesh_89006_1: THREE.Mesh;
    Mesh_89006_2: THREE.Mesh;
    Mesh_89006_3: THREE.Mesh;
    Mesh_89006_4: THREE.Mesh;
    RoomWall: THREE.Mesh;
    MeBitCthulu: THREE.Mesh;
    Curve001: THREE.Mesh;
    Curve001_1: THREE.Mesh;
    Curve001_2: THREE.Mesh;
    Curve001_3: THREE.Mesh;
    MeBitHelmet001: THREE.Mesh;
    MeBitHelmet001_1: THREE.Mesh;
    MeBitHelmet001_2: THREE.Mesh;
    MeBitSanta002: THREE.Mesh;
    MeBitSanta003: THREE.Mesh;
    MeBitSanta004: THREE.Mesh;
    MeBitSanta005: THREE.Mesh;
    Mesh_54001: THREE.Mesh;
    Mesh_54001_1: THREE.Mesh;
    Mesh_54001_2: THREE.Mesh;
    Mesh_54001_3: THREE.Mesh;
    Mesh_54001_4: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube005_1: THREE.Mesh;
    glas_low_glass_0002: THREE.Mesh;
    glas_low_glass_0002_1: THREE.Mesh;
    glas_low_glass_0002_2: THREE.Mesh;
    glas_low_glass_0002_3: THREE.Mesh;
    glas_low_glass_0002_4: THREE.Mesh;
    glas_low_glass_0002_5: THREE.Mesh;
    glas_low_glass_0002_6: THREE.Mesh;
    glas_low_glass_0002_7: THREE.Mesh;
    glas_low_glass_0002_8: THREE.Mesh;
    glas_low_glass_0002_9: THREE.Mesh;
    glas_low_glass_0002_10: THREE.Mesh;
    glas_low_glass_0002_11: THREE.Mesh;
    glas_low_glass_0002_12: THREE.Mesh;
    glas_low_glass_0002_13: THREE.Mesh;
    glas_low_glass_0002_14: THREE.Mesh;
    glas_low_glass_0002_15: THREE.Mesh;
    glas_low_glass_0002_16: THREE.Mesh;
    glas_low_glass_0002_17: THREE.Mesh;
    Middle_Chandelier: THREE.Mesh;
    TrackPad: THREE.Mesh;
    Mesh_36058: THREE.Mesh;
    Mesh_36058_1: THREE.Mesh;
    Mesh_36351: THREE.Mesh;
    Mesh_36351_1: THREE.Mesh;
    Mesh_36351_2: THREE.Mesh;
    Mesh_36351_3: THREE.Mesh;
    Mesh_36389: THREE.Mesh;
    Mesh_36389_1: THREE.Mesh;
    Right_Blank_Frame: THREE.Mesh;
    HEADPHONES: THREE.Mesh;
    Mesh_36439: THREE.Mesh;
    Mesh_36439_1: THREE.Mesh;
    Middle_Blank_Frsme: THREE.Mesh;
    Mesh_36456: THREE.Mesh;
    Mesh_36456_1: THREE.Mesh;
    TV_Stand: THREE.Mesh;
    Computer_Stand: THREE.Mesh;
    TV_Frame: THREE.Mesh;
    Computer_Desk_Drawer: THREE.Mesh;
    Computer_Table: THREE.Mesh;
    Remote: THREE.Mesh;
    Cup: THREE.Mesh;
    Left_Chandelier: THREE.Mesh;
    Right_Chandelier: THREE.Mesh;
    Middle_Console: THREE.Mesh;
    Mesh_36700: THREE.Mesh;
    Mesh_36700_1: THREE.Mesh;
    Graphic_Left_Plants: THREE.Mesh;
    Graphic_Middle_Cats: THREE.Mesh;
    Graphic_Right_Puzzles: THREE.Mesh;
    Fancy_Lights: THREE.Mesh;
    Chandelier_Lights: THREE.Mesh;
    Mesh_37003: THREE.Mesh;
    Mesh_37003_1: THREE.Mesh;
    Mesh_37003_2: THREE.Mesh;
    Couch: THREE.Mesh;
    PuzzleShelf012: THREE.Mesh;
    PuzzleShelf012_1: THREE.Mesh;
    PuzzleShelf012_2: THREE.Mesh;
    PuzzleShelf012_3: THREE.Mesh;
    PuzzleShelf012_4: THREE.Mesh;
    PuzzleShelf012_5: THREE.Mesh;
    PuzzleShelf012_6: THREE.Mesh;
    PuzzleShelf012_7: THREE.Mesh;
    PuzzleShelf012_8: THREE.Mesh;
    PuzzleShelf012_9: THREE.Mesh;
    PuzzleShelf012_10: THREE.Mesh;
    PuzzleShelf012_11: THREE.Mesh;
    PuzzleShelf012_12: THREE.Mesh;
    PuzzleShelf012_13: THREE.Mesh;
    RoomDisplayOne003: THREE.Mesh;
    RoomDisplayOne003_1: THREE.Mesh;
    RoomDisplayOne003_2: THREE.Mesh;
    RoomDisplayOne003_3: THREE.Mesh;
    RoomDisplayOne003_4: THREE.Mesh;
    RoomDisplayOne003_5: THREE.Mesh;
    RoomDisplayOne003_6: THREE.Mesh;
    RoomDisplayOne003_7: THREE.Mesh;
    RoomDisplayOne003_8: THREE.Mesh;
    RoomDisplayOne003_9: THREE.Mesh;
    RoomDisplayOne003_10: THREE.Mesh;
    RoomDisplayOne003_11: THREE.Mesh;
    RoomDisplayOne003_12: THREE.Mesh;
    RoomDisplayOne003_13: THREE.Mesh;
    RoomDisplayOne003_14: THREE.Mesh;
    RoomDisplayOne003_15: THREE.Mesh;
    RoomDisplayOne003_16: THREE.Mesh;
    RoomDisplayOne003_17: THREE.Mesh;
    RoomDisplayOne003_18: THREE.Mesh;
    RoomDisplayOne003_19: THREE.Mesh;
    RoomDisplayOne003_20: THREE.Mesh;
    RoomDisplayOne003_21: THREE.Mesh;
    RoomDisplayOne003_22: THREE.Mesh;
    RoomDisplayOne003_23: THREE.Mesh;
    RoomDisplayOne003_24: THREE.Mesh;
    RoomDisplayOne003_25: THREE.Mesh;
    RoomDisplayOne003_26: THREE.Mesh;
    RoomDisplayOne003_27: THREE.Mesh;
    RoomDisplayOne003_28: THREE.Mesh;
    RoomDisplayOne003_29: THREE.Mesh;
    RoomDisplayOne003_30: THREE.Mesh;
    RoomDisplayOne003_31: THREE.Mesh;
    RoomDisplayOne003_32: THREE.Mesh;
    RoomDisplayOne003_33: THREE.Mesh;
    RoomDisplayOne003_34: THREE.Mesh;
    RoomDisplayOne003_35: THREE.Mesh;
    RoomDisplayOne003_36: THREE.Mesh;
    RoomDisplayOne003_37: THREE.Mesh;
    RoomDisplayOne003_38: THREE.Mesh;
    RoomDisplayOne003_39: THREE.Mesh;
    RoomDisplayOne003_40: THREE.Mesh;
    Mesh_36021: THREE.Mesh;
    Mesh_36021_1: THREE.Mesh;
    Mesh_36021_2: THREE.Mesh;
    Mesh_36021_3: THREE.Mesh;
    Mesh_36021_4: THREE.Mesh;
    Cable_Box: THREE.Mesh;
    Mesh_36668: THREE.Mesh;
    Mesh_36668_1: THREE.Mesh;
    PS5: THREE.Mesh;
    Right_Speaker: THREE.Mesh;
    Left_Speaker: THREE.Mesh;
    Mouse: THREE.Mesh;
    Main_Keyboard: THREE.Mesh;
    RoomDisplayOne004: THREE.Mesh;
    RoomDisplayOne004_1: THREE.Mesh;
    RoomDisplayOne004_2: THREE.Mesh;
    RoomDisplayOne004_3: THREE.Mesh;
    RoomDisplayOne004_4: THREE.Mesh;
    RoomDisplayOne004_5: THREE.Mesh;
    RoomDisplayOne004_6: THREE.Mesh;
    RoomDisplayOne004_7: THREE.Mesh;
    RoomDisplayOne004_8: THREE.Mesh;
    RoomDisplayOne004_9: THREE.Mesh;
    RoomDisplayOne004_10: THREE.Mesh;
    RoomDisplayOne004_11: THREE.Mesh;
    RoomDisplayOne004_12: THREE.Mesh;
    RoomDisplayOne004_13: THREE.Mesh;
    RoomDisplayOne004_14: THREE.Mesh;
    RoomDisplayOne004_15: THREE.Mesh;
    RoomDisplayOne004_16: THREE.Mesh;
    RoomDisplayOne004_17: THREE.Mesh;
    RoomDisplayOne004_18: THREE.Mesh;
    RoomDisplayOne004_19: THREE.Mesh;
    RoomDisplayOne004_20: THREE.Mesh;
    RoomDisplayOne004_21: THREE.Mesh;
    RoomDisplayOne004_22: THREE.Mesh;
    RoomDisplayOne004_23: THREE.Mesh;
    RoomDisplayOne004_24: THREE.Mesh;
    RoomDisplayOne004_25: THREE.Mesh;
    RoomDisplayOne004_26: THREE.Mesh;
    RoomDisplayOne004_27: THREE.Mesh;
    RoomDisplayOne004_28: THREE.Mesh;
    RoomDisplayOne004_29: THREE.Mesh;
    RoomDisplayOne004_30: THREE.Mesh;
    RoomDisplayOne004_31: THREE.Mesh;
    RoomDisplayOne004_32: THREE.Mesh;
    RoomDisplayOne004_33: THREE.Mesh;
    RoomDisplayOne004_34: THREE.Mesh;
    RoomDisplayOne004_35: THREE.Mesh;
    RoomDisplayOne004_36: THREE.Mesh;
    RoomDisplayOne004_37: THREE.Mesh;
    RoomDisplayOne004_38: THREE.Mesh;
    RoomDisplayOne004_39: THREE.Mesh;
    RoomDisplayOne004_40: THREE.Mesh;
    RoomDisplayOne004_41: THREE.Mesh;
    RoomDisplayOne004_42: THREE.Mesh;
    RoomDisplayOne004_43: THREE.Mesh;
    RoomDisplayOne004_44: THREE.Mesh;
    RoomDisplayOne004_45: THREE.Mesh;
    RoomDisplayOne004_46: THREE.Mesh;
    RoomDisplayOne004_47: THREE.Mesh;
    RoomDisplayOne004_48: THREE.Mesh;
    RoomDisplayOne004_49: THREE.Mesh;
    RoomDisplayOne004_50: THREE.Mesh;
    RoomDisplayOne004_51: THREE.Mesh;
    RoomDisplayOne004_52: THREE.Mesh;
    RoomDisplayOne004_53: THREE.Mesh;
    RoomDisplayOne004_54: THREE.Mesh;
    RoomDisplayOne004_55: THREE.Mesh;
    RoomDisplayOne004_56: THREE.Mesh;
    RoomDisplayOne004_57: THREE.Mesh;
    RoomDisplayOne004_58: THREE.Mesh;
    RoomDisplayOne004_59: THREE.Mesh;
    RoomDisplayOne004_60: THREE.Mesh;
    RoomDisplayOne004_61: THREE.Mesh;
    RoomDisplayOne004_62: THREE.Mesh;
    RoomDisplayOne004_63: THREE.Mesh;
    RoomDisplayOne004_64: THREE.Mesh;
    RoomDisplayOne004_65: THREE.Mesh;
    RoomDisplayOne004_66: THREE.Mesh;
    RoomDisplayOne004_67: THREE.Mesh;
    RoomDisplayOne004_68: THREE.Mesh;
    RoomDisplayOne004_69: THREE.Mesh;
    RoomDisplayOne004_70: THREE.Mesh;
    RoomDisplayOne004_71: THREE.Mesh;
    RoomDisplayOne004_72: THREE.Mesh;
    RoomDisplayOne004_73: THREE.Mesh;
    RoomDisplayOne004_74: THREE.Mesh;
    RoomDisplayOne004_75: THREE.Mesh;
    RoomDisplayOne004_76: THREE.Mesh;
    RoomDisplayOne004_77: THREE.Mesh;
    RoomDisplayOne004_78: THREE.Mesh;
    RoomDisplayOne004_79: THREE.Mesh;
    RoomDisplayOne004_80: THREE.Mesh;
    RoomDisplayOne004_81: THREE.Mesh;
    RoomDisplayOne004_82: THREE.Mesh;
    RoomDisplayOne004_83: THREE.Mesh;
    RoomDisplayOne004_84: THREE.Mesh;
    RoomDisplayOne004_85: THREE.Mesh;
    RoomDisplayOne004_86: THREE.Mesh;
    RoomDisplayOne004_87: THREE.Mesh;
    RoomDisplayOne004_88: THREE.Mesh;
    RoomDisplayOne004_89: THREE.Mesh;
    RoomDisplayOne004_90: THREE.Mesh;
    RoomDisplayOne004_91: THREE.Mesh;
    RoomDisplayOne004_92: THREE.Mesh;
    RoomDisplayOne004_93: THREE.Mesh;
    RoomDisplayOne004_94: THREE.Mesh;
    RoomDisplayOne004_95: THREE.Mesh;
    RoomDisplayOne004_96: THREE.Mesh;
    Shelf_Keyboard: THREE.Mesh;
  };
  materials: {
    ['PaletteMaterial001.032']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial002.015']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.031']: THREE.MeshStandardMaterial;
    ['Glass.005']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial003.010']: THREE.MeshStandardMaterial;
    ['PaletteMaterial004.008']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial005.009']: THREE.MeshPhysicalMaterial;
    ['default.001']: THREE.MeshStandardMaterial;
    ['M_Bake.001']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.002']: THREE.MeshStandardMaterial;
    ['blackInternal.001']: THREE.MeshStandardMaterial;
    ['frontColor.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial003.001']: THREE.MeshPhysicalMaterial;
    ['blackFabric.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial004.001']: THREE.MeshPhysicalMaterial;
    ['equalizer.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['lambert1.001']: THREE.MeshStandardMaterial;
    ['cactus_04_mat.001']: THREE.MeshStandardMaterial;
    ['cactus_04_spike_mat.001']: THREE.MeshStandardMaterial;
    ['cactus_ground_mat.001']: THREE.MeshStandardMaterial;
    ['cactus_stone_mat.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial003.003']: THREE.MeshBasicMaterial;
    ['GameBoy.001']: THREE.MeshStandardMaterial;
    ['bButton.001']: THREE.MeshStandardMaterial;
    ['TT_checker_1024x1024_UV_GRID.001']: THREE.MeshStandardMaterial;
    ['ARCADE.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial003.004']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.007']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.003']: THREE.MeshStandardMaterial;
    ['PaletteMaterial004.003']: THREE.MeshStandardMaterial;
    ['Stick.001']: THREE.MeshStandardMaterial;
    ['lowpoly.001']: THREE.MeshStandardMaterial;
    ['GamepadStuff.001']: THREE.MeshStandardMaterial;
    ['gamepadMain.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial005.002']: THREE.MeshStandardMaterial;
    ['TT_checker_1024x1024_UV_GRID.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial006.001']: THREE.MeshPhysicalMaterial;
    ['controllerbody.001']: THREE.MeshStandardMaterial;
    ['material.001']: THREE.MeshStandardMaterial;
    ['ANALOG.001']: THREE.MeshStandardMaterial;
    ['dpad.001']: THREE.MeshStandardMaterial;
    ['cstick.001']: THREE.MeshStandardMaterial;
    ['abutton.001']: THREE.MeshStandardMaterial;
    ['zbutton.001']: THREE.MeshStandardMaterial;
    ['bumpers.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.008']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.009']: THREE.MeshStandardMaterial;
    ['baloon.001']: THREE.MeshStandardMaterial;
    ['baloon.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.003']: THREE.MeshStandardMaterial;
    ['Glass.002']: THREE.MeshPhysicalMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.010']: THREE.MeshStandardMaterial;
    ['forMayaAOrear_lights.001']: THREE.MeshBasicMaterial;
    ['forMayaAOnumber.001']: THREE.MeshBasicMaterial;
    ['forMayaAOlambert15.001']: THREE.MeshStandardMaterial;
    ['forMayaAOlambert16.001']: THREE.MeshStandardMaterial;
    ['forMayaAOblinn6.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.004']: THREE.MeshPhysicalMaterial;
    ['forMayaAOGrill2.001']: THREE.MeshBasicMaterial;
    ['Chrome_2.001']: THREE.MeshBasicMaterial;
    ['PaletteMaterial003.005']: THREE.MeshStandardMaterial;
    ['material.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.013']: THREE.MeshStandardMaterial;
    ['UV_checker.001']: THREE.MeshStandardMaterial;
    ['Material.008']: THREE.MeshStandardMaterial;
    ['SVGMat.001']: THREE.MeshStandardMaterial;
    ['Material.009']: THREE.MeshStandardMaterial;
    ['Material.010']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.014']: THREE.MeshStandardMaterial;
    ['Material.012']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.015']: THREE.MeshStandardMaterial;
    ['PaletteMaterial005.004']: THREE.MeshStandardMaterial;
    ['constant1.002']: THREE.MeshPhysicalMaterial;
    ['constant2.002']: THREE.MeshStandardMaterial;
    ['HoloFillDark.002']: THREE.MeshStandardMaterial;
    ['soft.001']: THREE.MeshStandardMaterial;
    ['base.001']: THREE.MeshStandardMaterial;
    ['CH_NPC_Pig_MI_PJH.001']: THREE.MeshStandardMaterial;
    ['MeditationSanta_Model_9_u1_v1.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.005']: THREE.MeshStandardMaterial;
    ['material_0.001']: THREE.MeshStandardMaterial;
    ['Material_0.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.017']: THREE.MeshStandardMaterial;
    ['Material.014']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.016']: THREE.MeshStandardMaterial;
    ['glass.001']: THREE.MeshPhysicalMaterial;
    ['robot_2.001']: THREE.MeshStandardMaterial;
    ['robot_1.001']: THREE.MeshStandardMaterial;
    ['Cactus_spines_01.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_bark_01.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_bark_03.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_petal_01.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_petal_02.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_petal_03.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_sepal_01.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_stigma.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_flower_stalk.001']: THREE.MeshStandardMaterial;
    ['Carnegiea_stamens.001']: THREE.MeshStandardMaterial;
    ['SickPlantSteam_Mat.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.029']: THREE.MeshStandardMaterial;
    ['SickPlantFlower_Mat.001']: THREE.MeshStandardMaterial;
    ['SickPlantFlowerIside_Mat.001']: THREE.MeshStandardMaterial;
    ['inside.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial008.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.006']: THREE.MeshStandardMaterial;
    ['PaletteMaterial006.003']: THREE.MeshStandardMaterial;
    ['PaletteMaterial007.002']: THREE.MeshPhysicalMaterial;
    ['Material.011']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
    ['Skin.001']: THREE.MeshStandardMaterial;
    ['Eyes.001']: THREE.MeshStandardMaterial;
    ['Material.018']: THREE.MeshStandardMaterial;
    ['Sticker_SPC-SG.006']: THREE.MeshStandardMaterial;
    ['baked.006']: THREE.MeshStandardMaterial;
    ['RubixCube.006']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.034']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.017']: THREE.MeshPhysicalMaterial;
    ['Mtl2.006']: THREE.MeshStandardMaterial;
    ['material.012']: THREE.MeshStandardMaterial;
    ['Sticker_B-P']: THREE.MeshStandardMaterial;
    ['Sticker_Y-P']: THREE.MeshStandardMaterial;
    ['Sticker_O-P']: THREE.MeshStandardMaterial;
    ['Sticker_W-P']: THREE.MeshStandardMaterial;
    ['Sticker_R-P']: THREE.MeshStandardMaterial;
    ['Sticker_G-P']: THREE.MeshStandardMaterial;
    Base: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.018']: THREE.MeshStandardMaterial;
    ['lambert7SG.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial008.003']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial009.002']: THREE.MeshStandardMaterial;
    ['equalizer.002']: THREE.MeshStandardMaterial;
    ['blackInternal.002']: THREE.MeshStandardMaterial;
    ['blackFabric.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial010.002']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial007.003']: THREE.MeshPhysicalMaterial;
    ['frontColor.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial005.005']: THREE.MeshStandardMaterial;
    ['TT_checker_1024x1024_UV_GRID.003']: THREE.MeshStandardMaterial;
    ['ARCADE.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.007']: THREE.MeshStandardMaterial;
    ['PaletteMaterial003.006']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.019']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.008']: THREE.MeshStandardMaterial;
    ['PaletteMaterial003.007']: THREE.MeshBasicMaterial;
    ['Stick.002']: THREE.MeshStandardMaterial;
    ['GameBoy.002']: THREE.MeshStandardMaterial;
    ['lowpoly.002']: THREE.MeshStandardMaterial;
    ['GamepadStuff.002']: THREE.MeshStandardMaterial;
    ['gamepadMain.002']: THREE.MeshStandardMaterial;
    ['Sticker_SPC-SG.002']: THREE.MeshStandardMaterial;
    ['baked.002']: THREE.MeshStandardMaterial;
    ['RubixCube.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial005.006']: THREE.MeshStandardMaterial;
    ['TT_checker_1024x1024_UV_GRID.004']: THREE.MeshStandardMaterial;
    ['PaletteMaterial006.004']: THREE.MeshPhysicalMaterial;
    ['controllerbody.002']: THREE.MeshStandardMaterial;
    ['material.003']: THREE.MeshStandardMaterial;
    ['ANALOG.002']: THREE.MeshStandardMaterial;
    ['dpad.002']: THREE.MeshStandardMaterial;
    ['cstick.002']: THREE.MeshStandardMaterial;
    ['bumpers.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.009']: THREE.MeshPhysicalMaterial;
    ['Mtl2.002']: THREE.MeshStandardMaterial;
    ['material.005']: THREE.MeshStandardMaterial;
    ['PaletteMaterial004.005']: THREE.MeshStandardMaterial;
    ['blinn4SG.001']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial004.006']: THREE.MeshStandardMaterial;
    ['Tassels.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.011']: THREE.MeshStandardMaterial;
    ['Carpet.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.018']: THREE.MeshStandardMaterial;
    ['OfficeChair.001']: THREE.MeshStandardMaterial;
    ['Tables.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial007.004']: THREE.MeshStandardMaterial;
    ['Papers.001']: THREE.MeshStandardMaterial;
    ['Pipe.001']: THREE.MeshStandardMaterial;
    ['Plant.001']: THREE.MeshStandardMaterial;
    ['Material_0.002']: THREE.MeshStandardMaterial;
    ['MeditationSanta_Model_9_u1_v1.002']: THREE.MeshStandardMaterial;
    ['material_0.002']: THREE.MeshStandardMaterial;
    ['material.006']: THREE.MeshStandardMaterial;
    ['Sticker_SPC-SG.003']: THREE.MeshStandardMaterial;
    ['baked.003']: THREE.MeshStandardMaterial;
    ['RubixCube.003']: THREE.MeshStandardMaterial;
    ['PaletteMaterial005.007']: THREE.MeshPhysicalMaterial;
    ['Mtl2.003']: THREE.MeshStandardMaterial;
    ['material.007']: THREE.MeshStandardMaterial;
    ['Glass.003']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial003.008']: THREE.MeshStandardMaterial;
    ['Sofa.001']: THREE.MeshStandardMaterial;
    ['Camera.001']: THREE.MeshStandardMaterial;
    ['Walls.001']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial001.020']: THREE.MeshPhysicalMaterial;
    ['lambert7SG.002']: THREE.MeshStandardMaterial;
    ['Airlock.001']: THREE.MeshStandardMaterial;
    ['AirPipe.001']: THREE.MeshStandardMaterial;
    ['AmmoBox.001']: THREE.MeshStandardMaterial;
    ['GameBoy.003']: THREE.MeshStandardMaterial;
    ['TT_checker_1024x1024_UV_GRID.005']: THREE.MeshStandardMaterial;
    ['ARCADE.003']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.010']: THREE.MeshStandardMaterial;
    ['PaletteMaterial003.009']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.021']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.011']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.012']: THREE.MeshBasicMaterial;
    ['Stick.003']: THREE.MeshStandardMaterial;
    ['lowpoly.003']: THREE.MeshStandardMaterial;
    ['GamepadStuff.003']: THREE.MeshStandardMaterial;
    ['gamepadMain.003']: THREE.MeshStandardMaterial;
    ['TT_checker_1024x1024_UV_GRID.006']: THREE.MeshStandardMaterial;
    ['PaletteMaterial004.007']: THREE.MeshPhysicalMaterial;
    ['controllerbody.003']: THREE.MeshStandardMaterial;
    ['material.008']: THREE.MeshStandardMaterial;
    ['ANALOG.003']: THREE.MeshStandardMaterial;
    ['cstick.003']: THREE.MeshStandardMaterial;
    ['bumpers.003']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.022']: THREE.MeshStandardMaterial;
    ['baloon.003']: THREE.MeshStandardMaterial;
    ['baloon.004']: THREE.MeshStandardMaterial;
    ['BedFrame.001']: THREE.MeshStandardMaterial;
    ['BedFabrics.001']: THREE.MeshStandardMaterial;
    ['CeillingLamp.001']: THREE.MeshStandardMaterial;
    ['Chair.001']: THREE.MeshStandardMaterial;
    ['ChairMetal.001']: THREE.MeshStandardMaterial;
    ['ChineseSoldier.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.023']: THREE.MeshStandardMaterial;
    ['02_-_Default.001']: THREE.MeshStandardMaterial;
    ['04_-_Default.001']: THREE.MeshStandardMaterial;
    ['DecorativePanels.001']: THREE.MeshStandardMaterial;
    ['Door.001']: THREE.MeshStandardMaterial;
    ['Ventilation.001']: THREE.MeshStandardMaterial;
    ['Material.015']: THREE.MeshStandardMaterial;
    ['PaletteMaterial005.008']: THREE.MeshStandardMaterial;
    ['PaletteMaterial006.005']: THREE.MeshPhysicalMaterial;
    ['Keyboard.001']: THREE.MeshStandardMaterial;
    ['VentLeder.001']: THREE.MeshStandardMaterial;
    ['MonitorMouse.001']: THREE.MeshStandardMaterial;
    ['forMayaAOlambert16.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial010.003']: THREE.MeshPhysicalMaterial;
    ['Chrome_2.002']: THREE.MeshBasicMaterial;
    ['forMayaAOrear_lights.002']: THREE.MeshBasicMaterial;
    ['PaletteMaterial011.002']: THREE.MeshStandardMaterial;
    ['material.009']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.024']: THREE.MeshStandardMaterial;
    ['Tassels.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.025']: THREE.MeshStandardMaterial;
    ['Material.016']: THREE.MeshStandardMaterial;
    ['Glass.004']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial001.026']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial002.013']: THREE.MeshStandardMaterial;
    ['SVGMat.002']: THREE.MeshStandardMaterial;
    ['Material.017']: THREE.MeshStandardMaterial;
    ['default.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial012.002']: THREE.MeshPhysicalMaterial;
    ['equalizer.003']: THREE.MeshStandardMaterial;
    ['material_0.003']: THREE.MeshBasicMaterial;
    ['PaletteMaterial008.004']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial009.003']: THREE.MeshPhysicalMaterial;
    ['blackFabric.003']: THREE.MeshStandardMaterial;
    ['frontColor.003']: THREE.MeshStandardMaterial;
    ['blackInternal.003']: THREE.MeshStandardMaterial;
    ['Skin.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.027']: THREE.MeshStandardMaterial;
    ['Eyes.002']: THREE.MeshStandardMaterial;
    ['CH_NPC_Pig_MI_PJH.002']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.028']: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/RachosRoomMain.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[3.084, 0.506, 0.16]}
        rotation={[-Math.PI, 1.566, -Math.PI]}
        scale={[0.006, 0.006, 0.007]}
      >
        <group
          position={[0, 0.615, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <group position={[-0.723, 0, 2.015]} rotation={[0, 0, -Math.PI]}>
            <group position={[-0.723, 0, -1.963]}>
              <group position={[0.894, -0.002, 1.418]} scale={0.491}>
                <mesh
                  geometry={nodes.Mesh_40001.geometry}
                  material={materials['PaletteMaterial001.032']}
                  position={[-5.999, -1, -3.995]}
                  scale={0.001}
                />
              </group>
            </group>
          </group>
          <group position={[0.723, 0, 2.015]}>
            <group position={[-0.723, 0, -1.963]}>
              <group position={[0.894, -0.002, 1.418]} scale={0.491}>
                <mesh
                  geometry={nodes.Mesh_40002.geometry}
                  material={materials['PaletteMaterial001.032']}
                  position={[-5.999, -1, -3.995]}
                  scale={0.001}
                />
              </group>
            </group>
          </group>
          <group position={[0, 0, 0.051]}>
            <group position={[0.001, -0.132, 1.329]} scale={0.778}>
              <mesh
                geometry={nodes.Mesh_41001.geometry}
                material={materials['PaletteMaterial002.015']}
                position={[-5.999, -1, -3.995]}
                scale={0.001}
              />
            </group>
            <group position={[0.069, 0.004, 3.25]} scale={2.845}>
              <group position={[-5.999, -1, -3.995]} scale={0.001}>
                <mesh
                  geometry={nodes.Mesh_42001_1.geometry}
                  material={materials['PaletteMaterial001.031']}
                />
                <mesh
                  geometry={nodes.Mesh_42001_2.geometry}
                  material={materials['Glass.005']}
                />
                <mesh
                  geometry={nodes.Mesh_42001_3.geometry}
                  material={materials['PaletteMaterial001.032']}
                />
                <mesh
                  geometry={nodes.Mesh_42001_4.geometry}
                  material={materials['PaletteMaterial003.010']}
                />
                <mesh
                  geometry={nodes.Mesh_42001_5.geometry}
                  material={materials['PaletteMaterial004.008']}
                />
                <mesh
                  geometry={nodes.Mesh_42001_6.geometry}
                  material={materials['PaletteMaterial005.009']}
                />
              </group>
            </group>
          </group>
          <group position={[0, 0, 0.05]} scale={[1, 1, 0.128]}>
            <group position={[0.001, -0.002, -0.002]} scale={0.506}>
              <mesh
                geometry={nodes.Mesh_43001.geometry}
                material={materials['PaletteMaterial002.015']}
                position={[-5.999, -1, -3.995]}
                scale={0.001}
              />
            </group>
          </group>
          <group position={[0, 0, 0.819]} scale={[1, 1, 0.834]}>
            <group position={[0.001, -0.002, -0.002]} scale={0.506}>
              <mesh
                geometry={nodes.Mesh_43002.geometry}
                material={materials['PaletteMaterial002.015']}
                position={[-5.999, -1, -3.995]}
                scale={0.001}
              />
            </group>
          </group>
          <group position={[0, 0, 0.427]} scale={[1, 1, 0.474]}>
            <group position={[0.001, -0.002, -0.002]} scale={0.506}>
              <mesh
                geometry={nodes.Mesh_43003.geometry}
                material={materials['PaletteMaterial002.015']}
                position={[-5.999, -1, -3.995]}
                scale={0.001}
              />
            </group>
          </group>
          <group position={[0, 0, 1]}>
            <group position={[0.001, -0.002, -0.002]} scale={0.506}>
              <mesh
                geometry={nodes.Mesh_43004.geometry}
                material={materials['PaletteMaterial002.015']}
                position={[-5.999, -1, -3.995]}
                scale={0.001}
              />
            </group>
          </group>
        </group>
      </group>
      <group position={[-5.999, -1.039, -4.064]} scale={0.001}>
        <mesh
          geometry={nodes.MeBitSanta002_1.geometry}
          material={materials['default.001']}
        />
        <mesh
          geometry={nodes.MeBitSanta002_2.geometry}
          material={materials['M_Bake.001']}
        />
        <mesh
          geometry={nodes.MeBitSanta002_3.geometry}
          material={materials['Material.001']}
        />
      </group>
      <group
        position={[-3.372, -4.12, 6.032]}
        rotation={[Math.PI, -0.775, -Math.PI / 2]}
        scale={0.001}
      >
        <mesh
          geometry={nodes.Mesh_0001.geometry}
          material={materials['PaletteMaterial001.002']}
        />
        <mesh
          geometry={nodes.Mesh_0001_1.geometry}
          material={materials['blackInternal.001']}
        />
        <mesh
          geometry={nodes.Mesh_0001_2.geometry}
          material={materials['frontColor.001']}
        />
        <mesh
          geometry={nodes.Mesh_0001_3.geometry}
          material={materials['PaletteMaterial003.001']}
        />
        <mesh
          geometry={nodes.Mesh_0001_4.geometry}
          material={materials['blackFabric.001']}
        />
        <mesh
          geometry={nodes.Mesh_0001_5.geometry}
          material={materials['PaletteMaterial004.001']}
        />
        <mesh
          geometry={nodes.Mesh_0001_6.geometry}
          material={materials['equalizer.001']}
        />
        <mesh
          geometry={nodes.Mesh_0001_7.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_89005.geometry}
          material={materials['lambert1.001']}
        />
        <mesh
          geometry={nodes.Mesh_89005_1.geometry}
          material={materials['cactus_04_mat.001']}
        />
        <mesh
          geometry={nodes.Mesh_89005_2.geometry}
          material={materials['cactus_04_spike_mat.001']}
        />
        <mesh
          geometry={nodes.Mesh_89005_3.geometry}
          material={materials['cactus_ground_mat.001']}
        />
        <mesh
          geometry={nodes.Mesh_89005_4.geometry}
          material={materials['cactus_stone_mat.001']}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36001.geometry}
          material={materials['PaletteMaterial003.003']}
        />
        <mesh
          geometry={nodes.Mesh_36001_1.geometry}
          material={materials['GameBoy.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_2.geometry}
          material={materials['bButton.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_3.geometry}
          material={materials['TT_checker_1024x1024_UV_GRID.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_4.geometry}
          material={materials['ARCADE.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_5.geometry}
          material={materials['PaletteMaterial002.002']}
        />
        <mesh
          geometry={nodes.Mesh_36001_6.geometry}
          material={materials['PaletteMaterial003.004']}
        />
        <mesh
          geometry={nodes.Mesh_36001_7.geometry}
          material={materials['PaletteMaterial001.007']}
        />
        <mesh
          geometry={nodes.Mesh_36001_8.geometry}
          material={materials['PaletteMaterial002.003']}
        />
        <mesh
          geometry={nodes.Mesh_36001_9.geometry}
          material={materials['PaletteMaterial004.003']}
        />
        <mesh
          geometry={nodes.Mesh_36001_10.geometry}
          material={materials['Stick.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_11.geometry}
          material={materials['lowpoly.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_12.geometry}
          material={materials['GamepadStuff.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_13.geometry}
          material={materials['gamepadMain.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_14.geometry}
          material={materials['PaletteMaterial005.002']}
        />
        <mesh
          geometry={nodes.Mesh_36001_15.geometry}
          material={materials['TT_checker_1024x1024_UV_GRID.002']}
        />
        <mesh
          geometry={nodes.Mesh_36001_16.geometry}
          material={materials['PaletteMaterial006.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_17.geometry}
          material={materials['controllerbody.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_18.geometry}
          material={materials['material.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_19.geometry}
          material={materials['ANALOG.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_20.geometry}
          material={materials['dpad.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_21.geometry}
          material={materials['cstick.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_22.geometry}
          material={materials['abutton.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_23.geometry}
          material={materials['zbutton.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_24.geometry}
          material={materials['bumpers.001']}
        />
        <mesh
          geometry={nodes.Mesh_36001_25.geometry}
          material={materials['PaletteMaterial001.008']}
        />
      </group>
      <mesh
        geometry={nodes.RoomFloor.geometry}
        material={materials['Material.003']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.TVMonitor.geometry}
        material={materials['Material.004']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Computer_Monitor.geometry}
        material={materials['Material.005']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.KitchenSet.geometry}
        material={materials['PaletteMaterial001.009']}
        position={[-5.999, -0.966, -3.995]}
        scale={0.001}
      />
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36017.geometry}
          material={materials['baloon.001']}
        />
        <mesh
          geometry={nodes.Mesh_36017_1.geometry}
          material={materials['baloon.002']}
        />
        <mesh
          geometry={nodes.Mesh_36017_2.geometry}
          material={materials['PaletteMaterial001.003']}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_44002.geometry}
          material={materials['Glass.002']}
        />
        <mesh
          geometry={nodes.Mesh_44002_1.geometry}
          material={materials['Material.007']}
        />
        <mesh
          geometry={nodes.Mesh_44002_2.geometry}
          material={materials['PaletteMaterial001.003']}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_39002.geometry}
          material={materials['PaletteMaterial001.010']}
        />
        <mesh
          geometry={nodes.Mesh_39002_1.geometry}
          material={materials['forMayaAOrear_lights.001']}
        />
        <mesh
          geometry={nodes.Mesh_39002_2.geometry}
          material={materials['forMayaAOnumber.001']}
        />
        <mesh
          geometry={nodes.Mesh_39002_3.geometry}
          material={materials['forMayaAOlambert15.001']}
        />
        <mesh
          geometry={nodes.Mesh_39002_4.geometry}
          material={materials['forMayaAOlambert16.001']}
        />
        <mesh
          geometry={nodes.Mesh_39002_5.geometry}
          material={materials['forMayaAOblinn6.001']}
        />
        <mesh
          geometry={nodes.Mesh_39002_6.geometry}
          material={materials['PaletteMaterial002.004']}
        />
        <mesh
          geometry={nodes.Mesh_39002_7.geometry}
          material={materials['forMayaAOGrill2.001']}
        />
        <mesh
          geometry={nodes.Mesh_39002_8.geometry}
          material={materials['Chrome_2.001']}
        />
        <mesh
          geometry={nodes.Mesh_39002_9.geometry}
          material={materials['PaletteMaterial003.005']}
        />
        <mesh
          geometry={nodes.Mesh_39002_10.geometry}
          material={materials['material.002']}
        />
      </group>
      <group
        position={[-1.018, 1.437, -2.908]}
        rotation={[-1.477, 1.571, 0]}
        scale={[0.352, 0.352, 0.896]}
      >
        <mesh
          geometry={nodes.armHoles_LP_UV_checker_0002.geometry}
          material={materials['PaletteMaterial001.013']}
        />
        <mesh
          geometry={nodes.armHoles_LP_UV_checker_0002_1.geometry}
          material={materials['UV_checker.001']}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_89006.geometry}
          material={materials['Material.008']}
        />
        <mesh
          geometry={nodes.Mesh_89006_1.geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          geometry={nodes.Mesh_89006_2.geometry}
          material={materials['Material.009']}
        />
        <mesh
          geometry={nodes.Mesh_89006_3.geometry}
          material={materials['Material.010']}
        />
        <mesh
          geometry={nodes.Mesh_89006_4.geometry}
          material={materials['PaletteMaterial001.014']}
        />
      </group>
      <mesh
        geometry={nodes.RoomWall.geometry}
        material={materials['Material.012']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.MeBitCthulu.geometry}
        material={materials['PaletteMaterial001.015']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group
        position={[0.163, 6.558, 0.312]}
        rotation={[1.505, 0, -3.141]}
        scale={[2.208, 0.261, 2.212]}
      >
        <mesh
          geometry={nodes.Curve001.geometry}
          material={materials['PaletteMaterial005.004']}
        />
        <mesh
          geometry={nodes.Curve001_1.geometry}
          material={materials['constant1.002']}
        />
        <mesh
          geometry={nodes.Curve001_2.geometry}
          material={materials['constant2.002']}
        />
        <mesh
          geometry={nodes.Curve001_3.geometry}
          material={materials['HoloFillDark.002']}
        />
      </group>
      <group position={[-5.089, 3.661, -3.47]} scale={0.325}>
        <mesh
          geometry={nodes.MeBitHelmet001.geometry}
          material={materials['soft.001']}
        />
        <mesh
          geometry={nodes.MeBitHelmet001_1.geometry}
          material={materials['base.001']}
        />
        <mesh
          geometry={nodes.MeBitHelmet001_2.geometry}
          material={materials['PaletteMaterial005.004']}
        />
      </group>
      <mesh
        geometry={nodes.MeBitSanta002.geometry}
        material={materials['CH_NPC_Pig_MI_PJH.001']}
        position={[-5.196, 4.443, -3.22]}
        rotation={[0, 0, 1.63]}
        scale={0.005}
      />
      <mesh
        geometry={nodes.MeBitSanta003.geometry}
        material={materials['CH_NPC_Pig_MI_PJH.001']}
        position={[-5.285, 4.443, -3.305]}
        rotation={[0, 0, 1.635]}
        scale={0.005}
      />
      <mesh
        geometry={nodes.MeBitSanta004.geometry}
        material={materials['CH_NPC_Pig_MI_PJH.001']}
        position={[-5.285, 4.443, -3.22]}
        rotation={[0, 0, 1.635]}
        scale={0.005}
      />
      <mesh
        geometry={nodes.MeBitSanta005.geometry}
        material={materials['CH_NPC_Pig_MI_PJH.001']}
        position={[-5.196, 4.443, -3.305]}
        rotation={[0, 0, 1.63]}
        scale={0.005}
      />
      <group
        position={[-4.44, 4.369, -4.53]}
        rotation={[-2.041, -1.559, -2.039]}
        scale={0}
      >
        <mesh
          geometry={nodes.Mesh_54001.geometry}
          material={materials['MeditationSanta_Model_9_u1_v1.001']}
        />
        <mesh
          geometry={nodes.Mesh_54001_1.geometry}
          material={materials['PaletteMaterial001.005']}
        />
        <mesh
          geometry={nodes.Mesh_54001_2.geometry}
          material={materials['material_0.001']}
        />
        <mesh
          geometry={nodes.Mesh_54001_3.geometry}
          material={materials['Material_0.001']}
        />
        <mesh
          geometry={nodes.Mesh_54001_4.geometry}
          material={materials['PaletteMaterial001.017']}
        />
      </group>
      <group position={[4.076, 2.23, -2.919]} scale={[0.22, 0.499, 0.499]}>
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials['Material.014']}
        />
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={materials['PaletteMaterial001.016']}
        />
      </group>
      <group
        position={[-3.385, 4.815, -3.536]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.172}
      >
        <mesh
          geometry={nodes.glas_low_glass_0002.geometry}
          material={materials['glass.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_1.geometry}
          material={materials['robot_2.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_2.geometry}
          material={materials['robot_1.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_3.geometry}
          material={materials['Cactus_spines_01.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_4.geometry}
          material={materials['Carnegiea_bark_01.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_5.geometry}
          material={materials['Carnegiea_bark_03.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_6.geometry}
          material={materials['Carnegiea_petal_01.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_7.geometry}
          material={materials['Carnegiea_petal_02.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_8.geometry}
          material={materials['Carnegiea_petal_03.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_9.geometry}
          material={materials['Carnegiea_sepal_01.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_10.geometry}
          material={materials['Carnegiea_stigma.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_11.geometry}
          material={materials['Carnegiea_flower_stalk.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_12.geometry}
          material={materials['Carnegiea_stamens.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_13.geometry}
          material={materials['SickPlantSteam_Mat.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_14.geometry}
          material={materials['PaletteMaterial001.029']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_15.geometry}
          material={materials['SickPlantFlower_Mat.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_16.geometry}
          material={materials['SickPlantFlowerIside_Mat.001']}
        />
        <mesh
          geometry={nodes.glas_low_glass_0002_17.geometry}
          material={materials['inside.001']}
        />
      </group>
      <mesh
        geometry={nodes.Middle_Chandelier.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.TrackPad.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36058.geometry}
          material={materials['PaletteMaterial001.002']}
        />
        <mesh
          geometry={nodes.Mesh_36058_1.geometry}
          material={materials['PaletteMaterial008.002']}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36351.geometry}
          material={materials['PaletteMaterial001.002']}
        />
        <mesh
          geometry={nodes.Mesh_36351_1.geometry}
          material={materials['PaletteMaterial002.006']}
        />
        <mesh
          geometry={nodes.Mesh_36351_2.geometry}
          material={materials['PaletteMaterial006.003']}
        />
        <mesh
          geometry={nodes.Mesh_36351_3.geometry}
          material={materials['PaletteMaterial007.002']}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36389.geometry}
          material={materials['PaletteMaterial001.002']}
        />
        <mesh
          geometry={nodes.Mesh_36389_1.geometry}
          material={materials['Material.011']}
        />
      </group>
      <mesh
        geometry={nodes.Right_Blank_Frame.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.HEADPHONES.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36439.geometry}
          material={materials['PaletteMaterial001.002']}
        />
        <mesh
          geometry={nodes.Mesh_36439_1.geometry}
          material={materials['Material.011']}
        />
      </group>
      <mesh
        geometry={nodes.Middle_Blank_Frsme.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36456.geometry}
          material={materials['PaletteMaterial001.002']}
        />
        <mesh
          geometry={nodes.Mesh_36456_1.geometry}
          material={materials['Material.011']}
        />
      </group>
      <mesh
        geometry={nodes.TV_Stand.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Computer_Stand.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.TV_Frame.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Computer_Desk_Drawer.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Computer_Table.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Remote.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Cup.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.94, -1, -4.074]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Left_Chandelier.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Right_Chandelier.geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Middle_Console.geometry}
        material={materials['Material.006']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36700.geometry}
          material={materials['PaletteMaterial001.002']}
        />
        <mesh
          geometry={nodes.Mesh_36700_1.geometry}
          material={materials['Material.006']}
        />
      </group>
      <mesh
        geometry={nodes.Graphic_Left_Plants.geometry}
        material={materials['Material.011']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Graphic_Middle_Cats.geometry}
        material={materials['Material.011']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Graphic_Right_Puzzles.geometry}
        material={materials['Material.011']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Fancy_Lights.geometry}
        material={materials['PaletteMaterial006.003']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Chandelier_Lights.geometry}
        material={materials['PaletteMaterial002.006']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group
        position={[-4.101, 0.458, -3.473]}
        rotation={[1.641, 0, 0]}
        scale={[0.093, 0.067, 0.093]}
      >
        <mesh
          geometry={nodes.Mesh_37003.geometry}
          material={materials['Skin.001']}
        />
        <mesh
          geometry={nodes.Mesh_37003_1.geometry}
          material={materials['PaletteMaterial001.003']}
        />
        <mesh
          geometry={nodes.Mesh_37003_2.geometry}
          material={materials['Eyes.001']}
        />
      </group>
      <mesh
        geometry={nodes.Couch.geometry}
        material={materials['Material.018']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group
        position={[-5.584, 0.309, -1.968]}
        rotation={[-Math.PI / 2, 0, -1.565]}
        scale={[2.617, 2.955, 3.725]}
      >
        <mesh
          geometry={nodes.PuzzleShelf012.geometry}
          material={materials['Sticker_SPC-SG.006']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_1.geometry}
          material={materials['baked.006']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_2.geometry}
          material={materials['RubixCube.006']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_3.geometry}
          material={materials['PaletteMaterial001.034']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_4.geometry}
          material={materials['PaletteMaterial002.017']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_5.geometry}
          material={materials['Mtl2.006']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_6.geometry}
          material={materials['material.012']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_7.geometry}
          material={materials['Sticker_B-P']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_8.geometry}
          material={materials['Sticker_Y-P']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_9.geometry}
          material={materials['Sticker_O-P']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_10.geometry}
          material={materials['Sticker_W-P']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_11.geometry}
          material={materials['Sticker_R-P']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_12.geometry}
          material={materials['Sticker_G-P']}
        />
        <mesh
          geometry={nodes.PuzzleShelf012_13.geometry}
          material={materials.Base}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.RoomDisplayOne003.geometry}
          material={materials['PaletteMaterial001.018']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_1.geometry}
          material={materials['lambert7SG.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_2.geometry}
          material={materials['PaletteMaterial008.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_3.geometry}
          material={materials['PaletteMaterial009.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_4.geometry}
          material={materials['equalizer.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_5.geometry}
          material={materials['blackInternal.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_6.geometry}
          material={materials['blackFabric.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_7.geometry}
          material={materials['PaletteMaterial010.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_8.geometry}
          material={materials['PaletteMaterial007.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_9.geometry}
          material={materials['frontColor.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_10.geometry}
          material={materials['PaletteMaterial005.005']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_11.geometry}
          material={materials['TT_checker_1024x1024_UV_GRID.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_12.geometry}
          material={materials['ARCADE.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_13.geometry}
          material={materials['PaletteMaterial002.007']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_14.geometry}
          material={materials['PaletteMaterial003.006']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_15.geometry}
          material={materials['PaletteMaterial001.019']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_16.geometry}
          material={materials['PaletteMaterial002.008']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_17.geometry}
          material={materials['PaletteMaterial003.007']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_18.geometry}
          material={materials['Stick.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_19.geometry}
          material={materials['GameBoy.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_20.geometry}
          material={materials['lowpoly.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_21.geometry}
          material={materials['GamepadStuff.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_22.geometry}
          material={materials['gamepadMain.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_23.geometry}
          material={materials['Sticker_SPC-SG.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_24.geometry}
          material={materials['baked.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_25.geometry}
          material={materials['RubixCube.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_26.geometry}
          material={materials['PaletteMaterial005.006']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_27.geometry}
          material={materials['TT_checker_1024x1024_UV_GRID.004']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_28.geometry}
          material={materials['PaletteMaterial006.004']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_29.geometry}
          material={materials['controllerbody.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_30.geometry}
          material={materials['material.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_31.geometry}
          material={materials['ANALOG.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_32.geometry}
          material={materials['dpad.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_33.geometry}
          material={materials['cstick.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_34.geometry}
          material={materials['bumpers.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_35.geometry}
          material={materials['PaletteMaterial002.009']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_36.geometry}
          material={materials['Mtl2.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_37.geometry}
          material={materials['material.005']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_38.geometry}
          material={materials['PaletteMaterial004.005']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_39.geometry}
          material={materials['blinn4SG.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne003_40.geometry}
          material={materials['PaletteMaterial004.006']}
        />
      </group>
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36021.geometry}
          material={materials['PaletteMaterial001.003']}
        />
        <mesh
          geometry={nodes.Mesh_36021_1.geometry}
          material={materials['Tassels.001']}
        />
        <mesh
          geometry={nodes.Mesh_36021_2.geometry}
          material={materials['PaletteMaterial001.011']}
        />
        <mesh
          geometry={nodes.Mesh_36021_3.geometry}
          material={materials['PaletteMaterial001.005']}
        />
        <mesh
          geometry={nodes.Mesh_36021_4.geometry}
          material={materials['Carpet.001']}
        />
      </group>
      <mesh
        geometry={nodes.Cable_Box.geometry}
        material={materials['PaletteMaterial001.016']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.Mesh_36668.geometry}
          material={materials['PaletteMaterial001.016']}
        />
        <mesh
          geometry={nodes.Mesh_36668_1.geometry}
          material={materials['PaletteMaterial001.018']}
        />
      </group>
      <mesh
        geometry={nodes.PS5.geometry}
        material={materials['PaletteMaterial001.016']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Right_Speaker.geometry}
        material={materials['PaletteMaterial001.016']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Left_Speaker.geometry}
        material={materials['PaletteMaterial001.016']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Mouse.geometry}
        material={materials['PaletteMaterial001.016']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Main_Keyboard.geometry}
        material={materials['PaletteMaterial001.016']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
      <group position={[-5.999, -1, -3.995]} scale={0.001}>
        <mesh
          geometry={nodes.RoomDisplayOne004.geometry}
          material={materials['blinn4SG.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_1.geometry}
          material={materials['PaletteMaterial004.006']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_2.geometry}
          material={materials['OfficeChair.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_3.geometry}
          material={materials['Tables.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_4.geometry}
          material={materials['PaletteMaterial007.004']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_5.geometry}
          material={materials['Papers.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_6.geometry}
          material={materials['Pipe.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_7.geometry}
          material={materials['Plant.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_8.geometry}
          material={materials['Material_0.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_9.geometry}
          material={materials['MeditationSanta_Model_9_u1_v1.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_10.geometry}
          material={materials['material_0.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_11.geometry}
          material={materials['material.006']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_12.geometry}
          material={materials['Sticker_SPC-SG.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_13.geometry}
          material={materials['baked.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_14.geometry}
          material={materials['RubixCube.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_15.geometry}
          material={materials['PaletteMaterial005.007']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_16.geometry}
          material={materials['Mtl2.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_17.geometry}
          material={materials['material.007']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_18.geometry}
          material={materials['Glass.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_19.geometry}
          material={materials['PaletteMaterial003.008']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_20.geometry}
          material={materials['Sofa.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_21.geometry}
          material={materials['Camera.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_22.geometry}
          material={materials['Walls.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_23.geometry}
          material={materials['PaletteMaterial001.020']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_24.geometry}
          material={materials['lambert7SG.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_25.geometry}
          material={materials['Airlock.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_26.geometry}
          material={materials['AirPipe.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_27.geometry}
          material={materials['AmmoBox.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_28.geometry}
          material={materials['GameBoy.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_29.geometry}
          material={materials['TT_checker_1024x1024_UV_GRID.005']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_30.geometry}
          material={materials['ARCADE.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_31.geometry}
          material={materials['PaletteMaterial002.010']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_32.geometry}
          material={materials['PaletteMaterial003.009']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_33.geometry}
          material={materials['PaletteMaterial001.021']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_34.geometry}
          material={materials['PaletteMaterial002.011']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_35.geometry}
          material={materials['PaletteMaterial002.012']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_36.geometry}
          material={materials['Stick.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_37.geometry}
          material={materials['lowpoly.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_38.geometry}
          material={materials['GamepadStuff.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_39.geometry}
          material={materials['gamepadMain.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_40.geometry}
          material={materials['TT_checker_1024x1024_UV_GRID.006']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_41.geometry}
          material={materials['PaletteMaterial004.007']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_42.geometry}
          material={materials['controllerbody.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_43.geometry}
          material={materials['material.008']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_44.geometry}
          material={materials['ANALOG.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_45.geometry}
          material={materials['cstick.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_46.geometry}
          material={materials['bumpers.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_47.geometry}
          material={materials['PaletteMaterial001.022']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_48.geometry}
          material={materials['baloon.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_49.geometry}
          material={materials['baloon.004']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_50.geometry}
          material={materials['BedFrame.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_51.geometry}
          material={materials['BedFabrics.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_52.geometry}
          material={materials['CeillingLamp.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_53.geometry}
          material={materials['Chair.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_54.geometry}
          material={materials['ChairMetal.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_55.geometry}
          material={materials['ChineseSoldier.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_56.geometry}
          material={materials['PaletteMaterial001.023']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_57.geometry}
          material={materials['02_-_Default.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_58.geometry}
          material={materials['04_-_Default.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_59.geometry}
          material={materials['DecorativePanels.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_60.geometry}
          material={materials['Door.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_61.geometry}
          material={materials['Ventilation.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_62.geometry}
          material={materials['Material.015']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_63.geometry}
          material={materials['PaletteMaterial005.008']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_64.geometry}
          material={materials['PaletteMaterial006.005']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_65.geometry}
          material={materials['Keyboard.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_66.geometry}
          material={materials['VentLeder.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_67.geometry}
          material={materials['MonitorMouse.001']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_68.geometry}
          material={materials['forMayaAOlambert16.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_69.geometry}
          material={materials['PaletteMaterial010.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_70.geometry}
          material={materials['Chrome_2.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_71.geometry}
          material={materials['forMayaAOrear_lights.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_72.geometry}
          material={materials['PaletteMaterial011.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_73.geometry}
          material={materials['material.009']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_74.geometry}
          material={materials['PaletteMaterial001.024']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_75.geometry}
          material={materials['Tassels.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_76.geometry}
          material={materials['PaletteMaterial001.025']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_77.geometry}
          material={materials['Material.016']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_78.geometry}
          material={materials['Glass.004']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_79.geometry}
          material={materials['PaletteMaterial001.026']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_80.geometry}
          material={materials['PaletteMaterial002.013']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_81.geometry}
          material={materials['SVGMat.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_82.geometry}
          material={materials['Material.017']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_83.geometry}
          material={materials['default.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_84.geometry}
          material={materials['PaletteMaterial012.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_85.geometry}
          material={materials['equalizer.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_86.geometry}
          material={materials['material_0.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_87.geometry}
          material={materials['PaletteMaterial008.004']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_88.geometry}
          material={materials['PaletteMaterial009.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_89.geometry}
          material={materials['blackFabric.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_90.geometry}
          material={materials['frontColor.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_91.geometry}
          material={materials['blackInternal.003']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_92.geometry}
          material={materials['Skin.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_93.geometry}
          material={materials['PaletteMaterial001.027']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_94.geometry}
          material={materials['Eyes.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_95.geometry}
          material={materials['CH_NPC_Pig_MI_PJH.002']}
        />
        <mesh
          geometry={nodes.RoomDisplayOne004_96.geometry}
          material={materials['PaletteMaterial001.028']}
        />
      </group>
      <mesh
        geometry={nodes.Shelf_Keyboard.geometry}
        material={materials['PaletteMaterial001.016']}
        position={[-5.999, -1, -3.995]}
        scale={0.001}
      />
    </group>
  );
}

// Preload only in browser to avoid SSR issues
if (typeof window !== 'undefined') {
  useGLTF.preload('/RachosRoomMain.glb');
}
