/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 RoomDisplayTwo.glb --types 
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_1: THREE.SkinnedMesh
    mesh_1_1: THREE.SkinnedMesh
    mesh_2: THREE.SkinnedMesh
    mesh_3: THREE.SkinnedMesh
    mesh_4: THREE.SkinnedMesh
    mesh_5: THREE.SkinnedMesh
    mesh_6: THREE.SkinnedMesh
    mesh_7: THREE.SkinnedMesh
    mesh_8: THREE.SkinnedMesh
    mesh_9: THREE.SkinnedMesh
    mesh_10: THREE.SkinnedMesh
    mesh_11: THREE.SkinnedMesh
    mesh_12: THREE.SkinnedMesh
    mesh_13: THREE.SkinnedMesh
    mesh_14: THREE.SkinnedMesh
    mesh_0: THREE.Mesh
    mesh_0_1: THREE.Mesh
    mesh_0_2: THREE.Mesh
    mesh_0_3: THREE.Mesh
    mesh_0_4: THREE.Mesh
    mesh_0_5: THREE.Mesh
    mesh_0_6: THREE.Mesh
    mesh_0_7: THREE.Mesh
    mesh_0_8: THREE.Mesh
    mesh_0_9: THREE.Mesh
    mesh_0_10: THREE.Mesh
    mesh_0_11: THREE.Mesh
    mesh_0_12: THREE.Mesh
    mesh_0_13: THREE.Mesh
    mesh_0_14: THREE.Mesh
    mesh_0_15: THREE.Mesh
    mesh_0_16: THREE.Mesh
    mesh_0_17: THREE.Mesh
    mesh_0_18: THREE.Mesh
    mesh_0_19: THREE.Mesh
    mesh_0_20: THREE.Mesh
    mesh_0_21: THREE.Mesh
    mesh_0_22: THREE.Mesh
    mesh_0_23: THREE.Mesh
    mesh_0_24: THREE.Mesh
    mesh_0_25: THREE.Mesh
    mesh_0_26: THREE.Mesh
    mesh_0_27: THREE.Mesh
    mesh_0_28: THREE.Mesh
    mesh_0_29: THREE.Mesh
    mesh_0_30: THREE.Mesh
    mesh_0_31: THREE.Mesh
    mesh_0_32: THREE.Mesh
    mesh_0_33: THREE.Mesh
    mesh_0_34: THREE.Mesh
    mesh_0_35: THREE.Mesh
    mesh_0_36: THREE.Mesh
    mesh_0_37: THREE.Mesh
    mesh_0_38: THREE.Mesh
    mesh_0_39: THREE.Mesh
    mesh_0_40: THREE.Mesh
    mesh_0_41: THREE.Mesh
    mesh_0_42: THREE.Mesh
    mesh_0_43: THREE.Mesh
    mesh_0_44: THREE.Mesh
    mesh_0_45: THREE.Mesh
    mesh_0_46: THREE.Mesh
    mesh_0_47: THREE.Mesh
    mesh_0_48: THREE.Mesh
    mesh_0_49: THREE.Mesh
    mesh_0_50: THREE.Mesh
    mesh_0_51: THREE.Mesh
    mesh_0_52: THREE.Mesh
    mesh_0_53: THREE.Mesh
    mesh_0_54: THREE.Mesh
    mesh_0_55: THREE.Mesh
    mesh_0_56: THREE.Mesh
    mesh_0_57: THREE.Mesh
    mesh_0_58: THREE.Mesh
    mesh_0_59: THREE.Mesh
    mesh_0_60: THREE.Mesh
    mesh_0_61: THREE.Mesh
    mesh_0_62: THREE.Mesh
    mesh_0_63: THREE.Mesh
    mesh_0_64: THREE.Mesh
    mesh_0_65: THREE.Mesh
    mesh_0_66: THREE.Mesh
    mesh_0_67: THREE.Mesh
    mesh_0_68: THREE.Mesh
    mesh_0_69: THREE.Mesh
    mesh_0_70: THREE.Mesh
    mesh_0_71: THREE.Mesh
    mesh_0_72: THREE.Mesh
    mesh_0_73: THREE.Mesh
    mesh_0_74: THREE.Mesh
    mesh_0_75: THREE.Mesh
    mesh_0_76: THREE.Mesh
    mesh_0_77: THREE.Mesh
    mesh_0_78: THREE.Mesh
    mesh_0_79: THREE.Mesh
    mesh_0_80: THREE.Mesh
    mesh_0_81: THREE.Mesh
    mesh_0_82: THREE.Mesh
    mesh_0_83: THREE.Mesh
    mesh_0_84: THREE.Mesh
    mesh_0_85: THREE.Mesh
    mesh_0_86: THREE.Mesh
    mesh_0_87: THREE.Mesh
    mesh_0_88: THREE.Mesh
    mesh_0_89: THREE.Mesh
    mesh_0_90: THREE.Mesh
    mesh_0_91: THREE.Mesh
    mesh_0_92: THREE.Mesh
    mesh_0_93: THREE.Mesh
    mesh_0_94: THREE.Mesh
    mesh_0_95: THREE.Mesh
    mesh_0_96: THREE.Mesh
    mesh_0_97: THREE.Mesh
    mesh_0_98: THREE.Mesh
    mesh_0_99: THREE.Mesh
    mesh_0_100: THREE.Mesh
    mesh_0_101: THREE.Mesh
    mesh_0_102: THREE.Mesh
    mesh_0_103: THREE.Mesh
    mesh_0_104: THREE.Mesh
    mesh_0_105: THREE.Mesh
    mesh_0_106: THREE.Mesh
    mesh_0_107: THREE.Mesh
    mesh_0_108: THREE.Mesh
    mesh_0_109: THREE.Mesh
    mesh_0_110: THREE.Mesh
    mesh_0_111: THREE.Mesh
    mesh_0_112: THREE.Mesh
    mesh_0_113: THREE.Mesh
    mesh_0_114: THREE.Mesh
    mesh_0_115: THREE.Mesh
    mesh_0_116: THREE.Mesh
    mesh_0_117: THREE.Mesh
    mesh_0_118: THREE.Mesh
    mesh_0_119: THREE.Mesh
    mesh_0_120: THREE.Mesh
    mesh_0_121: THREE.Mesh
    mesh_0_122: THREE.Mesh
    mesh_0_123: THREE.Mesh
    mesh_0_124: THREE.Mesh
    mesh_0_125: THREE.Mesh
    mesh_0_126: THREE.Mesh
    mesh_0_127: THREE.Mesh
    mesh_0_128: THREE.Mesh
    mesh_0_129: THREE.Mesh
    mesh_0_130: THREE.Mesh
    _rootJoint: THREE.Bone
    neutral_bone: THREE.Bone
    _rootJoint_1: THREE.Bone
    _rootJoint_2: THREE.Bone
    _rootJoint_3: THREE.Bone
    _rootJoint_4: THREE.Bone
  }
  materials: {
    ['Skin.002']: THREE.MeshStandardMaterial
    ['PaletteMaterial001.054']: THREE.MeshStandardMaterial
    ['Eyes.002']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_MI_PJH.002']: THREE.MeshStandardMaterial
    ['CH_NPC_Pig_Eyelash_PJH.002']: THREE.MeshStandardMaterial
    ['lambert6SG.001']: THREE.MeshStandardMaterial
    ['lambert7SG.001']: THREE.MeshStandardMaterial
    ['blinn4SG.001']: THREE.MeshPhysicalMaterial
    ['Airlock.001']: THREE.MeshStandardMaterial
    ['AirPipe.001']: THREE.MeshStandardMaterial
    ['AmmoBox.001']: THREE.MeshStandardMaterial
    ['GameBoy.004']: THREE.MeshStandardMaterial
    ['bButton.004']: THREE.MeshStandardMaterial
    ['TT_checker_1024x1024_UV_GRID.008']: THREE.MeshStandardMaterial
    ['ARCADE.005']: THREE.MeshStandardMaterial
    ['PaletteMaterial002.016']: THREE.MeshStandardMaterial
    ['PaletteMaterial003.015']: THREE.MeshStandardMaterial
    ['PaletteMaterial001.032']: THREE.MeshStandardMaterial
    ['PaletteMaterial002.023']: THREE.MeshStandardMaterial
    ['PaletteMaterial002.024']: THREE.MeshBasicMaterial
    ['Stick.004']: THREE.MeshStandardMaterial
    ['lowpoly.004']: THREE.MeshStandardMaterial
    ['GamepadStuff.005']: THREE.MeshStandardMaterial
    ['gamepadMain.005']: THREE.MeshStandardMaterial
    ['PaletteMaterial003.016']: THREE.MeshStandardMaterial
    ['TT_checker_1024x1024_UV_GRID.009']: THREE.MeshStandardMaterial
    ['PaletteMaterial004.011']: THREE.MeshPhysicalMaterial
    ['controllerbody.004']: THREE.MeshStandardMaterial
    ['material.011']: THREE.MeshStandardMaterial
    ['ANALOG.004']: THREE.MeshStandardMaterial
    ['dpad.004']: THREE.MeshStandardMaterial
    ['cstick.004']: THREE.MeshStandardMaterial
    ['startbutton.002']: THREE.MeshStandardMaterial
    ['abutton.004']: THREE.MeshStandardMaterial
    ['zbutton.004']: THREE.MeshStandardMaterial
    ['bumpers.004']: THREE.MeshStandardMaterial
    ['PaletteMaterial001.033']: THREE.MeshStandardMaterial
    ['baloon.002']: THREE.MeshStandardMaterial
    ['baloon.005']: THREE.MeshStandardMaterial
    ['BedFrame.001']: THREE.MeshStandardMaterial
    ['BedFabrics.001']: THREE.MeshStandardMaterial
    ['CeillingLamp.001']: THREE.MeshStandardMaterial
    ['Chair.001']: THREE.MeshStandardMaterial
    ['ChairMetal.001']: THREE.MeshStandardMaterial
    ['ChineseSoldier.001']: THREE.MeshStandardMaterial
    ['PaletteMaterial007.007']: THREE.MeshStandardMaterial
    ['PaletteMaterial008.006']: THREE.MeshStandardMaterial
    ['PaletteMaterial001.047']: THREE.MeshStandardMaterial
    ['PaletteMaterial004.012']: THREE.MeshStandardMaterial
    ['PaletteMaterial005.015']: THREE.MeshStandardMaterial
    ['PaletteMaterial006.007']: THREE.MeshStandardMaterial
    ['PaletteMaterial003.017']: THREE.MeshStandardMaterial
    ['PaletteMaterial002.025']: THREE.MeshStandardMaterial
    ['02_-_Default.002']: THREE.MeshStandardMaterial
    ['04_-_Default.002']: THREE.MeshStandardMaterial
    ['05_-_Default.002']: THREE.MeshStandardMaterial
    ['DecorativePanels.001']: THREE.MeshStandardMaterial
    ['Door.001']: THREE.MeshStandardMaterial
    ['Ventilation.001']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['PaletteMaterial005.016']: THREE.MeshStandardMaterial
    ['PaletteMaterial006.009']: THREE.MeshPhysicalMaterial
    ['Keyboard.001']: THREE.MeshStandardMaterial
    ['VentLeder.001']: THREE.MeshStandardMaterial
    ['MonitorMouse.001']: THREE.MeshStandardMaterial
    ['forMayaAOnumber.002']: THREE.MeshBasicMaterial
    ['forMayaAOlambert15.002']: THREE.MeshStandardMaterial
    ['forMayaAOlambert16.002']: THREE.MeshStandardMaterial
    ['forMayaAOblinn6.002']: THREE.MeshStandardMaterial
    ['PaletteMaterial010.004']: THREE.MeshPhysicalMaterial
    ['forMayaAOGrill2.002']: THREE.MeshBasicMaterial
    ['Chrome_2.002']: THREE.MeshBasicMaterial
    ['forMayaAOrear_lights.002']: THREE.MeshBasicMaterial
    ['PaletteMaterial011.002']: THREE.MeshStandardMaterial
    ['material.012']: THREE.MeshStandardMaterial
    ['PaletteMaterial001.049']: THREE.MeshStandardMaterial
    ['Tassels.002']: THREE.MeshStandardMaterial
    ['PaletteMaterial001.050']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Glass.003']: THREE.MeshPhysicalMaterial
    ['PaletteMaterial001.051']: THREE.MeshPhysicalMaterial
    ['PaletteMaterial002.026']: THREE.MeshStandardMaterial
    ['PaletteMaterial004.013']: THREE.MeshStandardMaterial
    ['PaletteMaterial005.017']: THREE.MeshStandardMaterial
    ['PaletteMaterial006.010']: THREE.MeshStandardMaterial
    ['PaletteMaterial007.008']: THREE.MeshStandardMaterial
    ['PaletteMaterial008.007']: THREE.MeshStandardMaterial
    ['PaletteMaterial009.004']: THREE.MeshStandardMaterial
    ['PaletteMaterial010.005']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['SVGMat.003']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['default.002']: THREE.MeshStandardMaterial
    ['PaletteMaterial012.002']: THREE.MeshPhysicalMaterial
    ['christmas_tree.002']: THREE.MeshBasicMaterial
    ['equalizer.004']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['PaletteMaterial001.048']: THREE.MeshStandardMaterial
    ['material_0.002']: THREE.MeshBasicMaterial
    ['M_Bake.002']: THREE.MeshStandardMaterial
    ['PaletteMaterial008.008']: THREE.MeshPhysicalMaterial
    ['PaletteMaterial009.005']: THREE.MeshPhysicalMaterial
    ['blackFabric.005']: THREE.MeshStandardMaterial
    ['frontColor.004']: THREE.MeshStandardMaterial
    ['blackInternal.005']: THREE.MeshStandardMaterial
    ['OfficeChair.001']: THREE.MeshStandardMaterial
    ['Tables.001']: THREE.MeshStandardMaterial
    ['PaletteMaterial007.009']: THREE.MeshStandardMaterial
    ['Papers.001']: THREE.MeshStandardMaterial
    ['PistolTrigger.002']: THREE.MeshStandardMaterial
    ['PistolBody.002']: THREE.MeshStandardMaterial
    ['PistolRings.002']: THREE.MeshStandardMaterial
    ['Pipe.001']: THREE.MeshStandardMaterial
    ['Plant.001']: THREE.MeshStandardMaterial
    ['Material_0.002']: THREE.MeshStandardMaterial
    ['MeditationSanta_Model_9_u1_v1.002']: THREE.MeshStandardMaterial
    ['material_0.004']: THREE.MeshStandardMaterial
    ['material.013']: THREE.MeshStandardMaterial
    ['Sticker_SPC-SG.004']: THREE.MeshStandardMaterial
    ['baked.004']: THREE.MeshStandardMaterial
    ['RubixCube.004']: THREE.MeshStandardMaterial
    ['PaletteMaterial005.018']: THREE.MeshPhysicalMaterial
    ['Mtl2.004']: THREE.MeshStandardMaterial
    ['material.014']: THREE.MeshStandardMaterial
    ['PaletteMaterial002.027']: THREE.MeshStandardMaterial
    ['Glass.005']: THREE.MeshPhysicalMaterial
    ['PaletteMaterial003.018']: THREE.MeshStandardMaterial
    ['PaletteMaterial004.014']: THREE.MeshPhysicalMaterial
    ['PaletteMaterial005.019']: THREE.MeshPhysicalMaterial
    ['Sofa.001']: THREE.MeshStandardMaterial
    ['material_0.006']: THREE.MeshBasicMaterial
    ['Camera.001']: THREE.MeshStandardMaterial
    ['Walls.001']: THREE.MeshPhysicalMaterial
    ['PaletteMaterial001.053']: THREE.MeshPhysicalMaterial
    Material: THREE.MeshStandardMaterial
  }
}

// Define the available actions in the GLTF model for type safety
type ActionName =
  | 'Armature|Idle'
  | 'Armature|Walk'
  | 'Armature|Yell'
  | 'run'
  | 'AlienOrange'
  | 'AlienPurple'
  | 'AlienRLeft'
  | 'AlienRMiddle'
  | 'AlienRRight'
  | 'AliensGreenFront.018Action'
  | 'AliensGreenLeft.001Action.003'
  | 'AliensGreenFront.005Action'
  | 'Animation'
  | 'sound wave'
  | 'Main'
  | 'Scene'
  | 'Fan|FanAction'

// Define a type for the actions using Record
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function RoomDisplayTwo(props: JSX.IntrinsicElements['group']) {
  // Initialize useRef with null and update the type accordingly
  const group = useRef<THREE.Group | null>(null)

  // Load the GLTF model and cast it to GLTFResult for type safety
  const { nodes, materials, animations } = useGLTF('https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/oldRooms/RoomDisplayTwo.glb') as GLTFResult

  // Use useAnimations without specifying a generic parameter
  // Then, cast the actions to GLTFActions for type safety
  const { actions } = useAnimations(animations, group)

  // Cast actions to GLTFActions for type safety
  const typedActions = actions as unknown as GLTFActions
  // Use useEffect to play all animations when the component mounts
  useEffect(() => {
    // Play all defined animations when the component mounts
    Object.values(typedActions).forEach(action => action.play())

    // Cleanup: Stop all animations when the component unmounts
    return () => {
      Object.values(typedActions).forEach(action => action.stop())
    }
  }, [typedActions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="RoomDisplayTwo001">
        <group name="Object_11010" position={[-9.697, 6.206, -17.329]} rotation={[-Math.PI / 2, 0, -1.571]} scale={0.045}>
          <primitive object={nodes._rootJoint} />
          <primitive object={nodes.neutral_bone} />
        </group>
        <group name="Object_13008" position={[-21.469, 4.407, -14.875]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <primitive object={nodes._rootJoint_1} />
        </group>
        <group name="Object_155002" position={[-21.481, 4.415, -14.596]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <primitive object={nodes._rootJoint_2} />
        </group>
        <group name="Object_226002" position={[-21.687, 4.413, -14.606]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <primitive object={nodes._rootJoint_3} />
        </group>
        <group name="Object_84002" position={[-21.675, 4.405, -14.885]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <primitive object={nodes._rootJoint_4} />
        </group>
        <group name="RoomDisplayTwo001_1" position={[-14.976, 7.804, -15.192]} rotation={[Math.PI / 2, 0, 1.571]} scale={11.241}>
          <group name="AlienOrange002" position={[-0.011, 0, -0.006]} rotation={[0, 0, Math.PI]} scale={[0.03, 0.004, 0.03]} />
          <group name="AlienPurple002" position={[-0.69, 0.285, 0.276]} rotation={[0, 0.001, 1.682]} scale={[0.068, 0.015, 0.068]} />
          <group name="AlienRLeft002" position={[-0.694, 0.293, 0.271]} rotation={[1.552, -1.46, 3.123]} scale={[0.027, 0.001, 0.044]} />
          <group name="AlienRMiddle002" position={[-0.694, 0.293, 0.271]} rotation={[0, 0.001, 1.682]} scale={[0.027, 0.002, 0.027]} />
          <group name="AlienRRight002" position={[-0.694, 0.293, 0.271]} rotation={[0, 0.001, 1.682]} scale={[0.027, 0.002, 0.027]} />
          <group name="AliensGreenLeft002" position={[-0.692, 0.293, 0.27]} rotation={[-2.892, -0.148, -1.647]} scale={[0.045, 0.005, 0.045]} />
          <group name="AliensGreenMiddle002" position={[-0.691, 0.293, 0.271]} rotation={[-2.362, -0.166, -1.562]} scale={[0.061, 0.004, 0.045]} />
          <group name="AliensGreenRight002" position={[-0.692, 0.293, 0.27]} rotation={[-0.3, 0.088, 1.713]} scale={[0.047, 0.003, 0.072]} />
          <group name="Armature002" position={[-0.19, -0.47, 0.143]} rotation={[Math.PI, 0, 0]} scale={0.004} />
          <group name="Bake001_18002" position={[-0.021, 0.61, 0.222]} rotation={[-1.571, 1.566, 0]} scale={[0.002, 0.001, 0.001]} />
          <group name="baseCover001_0004" position={[-0.337, 0.033, 0.197]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.014, 0.023, 0.011]} />
          <group name="Circle001_11003" position={[0.004, 0.008, 0]} rotation={[Math.PI / 2, -0.54, -Math.PI / 2]} scale={0.014} />
          <group name="circle003" position={[-0.349, 0.043, -0.091]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.046, 0.043, 0.046]} />
          <group name="Circle003_13004" position={[0.004, 0.002, 0]} rotation={[Math.PI / 2, -0.54, -Math.PI / 2]} scale={0.014} />
          <group name="Circle005_16004" position={[0.004, 0.008, -0.018]} rotation={[Math.PI / 2, -0.54, -Math.PI / 2]} scale={0.014} />
          <group name="Circle007_18004" position={[0.004, 0.002, -0.018]} rotation={[Math.PI / 2, -0.54, -Math.PI / 2]} scale={0.014} />
          <group name="Circle009_4004" position={[0.004, 0.001, -0.012]} rotation={[Math.PI / 2, -0.54, -Math.PI / 2]} scale={0.011} />
          <group name="Circle011_1004" position={[0.004, 0.001, -0.006]} rotation={[Math.PI / 2, -0.54, -Math.PI / 2]} scale={0.011} />
          <group name="Circle013_7004" position={[0.004, 0.005, -0.009]} rotation={[Math.PI / 2, -0.54, -Math.PI / 2]} scale={0.011} />
          <group name="circle2003" position={[-0.349, 0.043, -0.091]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.046, 0.043, 0.046]} />
          <group name="Cylinder001_3002" position={[-0.021, 0.61, 0.216]} rotation={[-1.571, 1.566, 0]} scale={0.001} />
          <group name="Cylinder002_4002" position={[-0.021, 0.61, 0.222]} rotation={[-1.571, 1.566, 0]} scale={[0.002, 0.001, 0.001]} />
          <group name="Ears003" position={[-0.785, -0.428, 0.234]} rotation={[Math.PI, 0, 0]} scale={0.009} />
          <group name="Empty003" position={[-0.785, -0.428, 0.236]} rotation={[Math.PI, 0, 0]} scale={0.009} />
          <group name="equalizer_35004" position={[-0.337, 0.033, 0.22]} rotation={[-Math.PI / 2, -1.059, 0]} scale={[0.013, 0.013, 0.011]} />
          <group name="Eyes003" position={[-0.785, -0.424, 0.235]} rotation={[Math.PI, 0, 0]} scale={[0.009, 0.009, 0]} />
          <group name="Fan001" position={[-0.188, -0.436, -0.21]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
          <group name="gifts001_24002" position={[-0.019, 0.551, 0.221]} rotation={[1.696, 0.723, 2.966]} scale={[0.004, 0.003, 0.004]} />
          <group name="gifts002_25002" position={[-0.019, 0.557, 0.221]} rotation={[2.875, 1.455, 1.839]} scale={[0.002, 0.003, 0.005]} />
          <group name="gifts003_26002" position={[-0.02, 0.555, 0.221]} rotation={[1.696, 0.723, 2.966]} scale={[0.004, 0.003, 0.004]} />
          <group name="gifts_23002" position={[-0.018, 0.553, 0.221]} rotation={[2.877, 1.454, 1.834]} scale={[0.002, 0.003, 0.005]} />
          <group name="glass_1003" position={[-0.337, 0.033, 0.22]} rotation={[-Math.PI / 2, -1.059, 0]} scale={[0.013, 0.013, 0.011]} />
          <group name="Hand_origin003" position={[-0.791, -0.428, 0.242]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.009} />
          <group name="Hand_origin006" position={[-0.779, -0.428, 0.242]} rotation={[Math.PI, 0, 0]} scale={0.009} />
          <group name="indicator10_3004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.004, 0.011]} />
          <group name="indicator11_4004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.019, 0.011]} />
          <group name="indicator12_5004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.014, 0.011]} />
          <group name="indicator13_6004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.01, 0.011]} />
          <group name="indicator14_7004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.005, 0.011]} />
          <group name="indicator15_8004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.015, 0.011]} />
          <group name="indicator16_9004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.005, 0.011]} />
          <group name="indicator17_10004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.017, 0.011]} />
          <group name="indicator18_11004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.008, 0.011]} />
          <group name="indicator19_12004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.012, 0.011]} />
          <group name="indicator1_2004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.004, 0.011]} />
          <group name="indicator20_14004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.007, 0.011]} />
          <group name="indicator21_15004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.019, 0.011]} />
          <group name="indicator22_16004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.021, 0.011]} />
          <group name="indicator23_17004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.011, 0.011]} />
          <group name="indicator24_18004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.015, 0.011]} />
          <group name="indicator25_19004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.014, 0.011]} />
          <group name="indicator26_20004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.01, 0.011]} />
          <group name="indicator27_21004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.005, 0.011]} />
          <group name="indicator28_22004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.011, 0.011]} />
          <group name="indicator29_23004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.013, 0.011]} />
          <group name="indicator2_13004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.018, 0.011]} />
          <group name="indicator30_25004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.017, 0.011]} />
          <group name="indicator31_26004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.013, 0.011]} />
          <group name="indicator32_27004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.012, 0.011]} />
          <group name="indicator3_24004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.022, 0.011]} />
          <group name="indicator4_28004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.009, 0.011]} />
          <group name="indicator5_29004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.02, 0.011]} />
          <group name="indicator6_30004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.013, 0.011]} />
          <group name="indicator7_31004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.022, 0.011]} />
          <group name="indicator8_32004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.007, 0.011]} />
          <group name="indicator9_33004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.007, 0.011]} />
          <group name="Inner_Sphere_Chandelier004" position={[-0.349, 0.043, -0.091]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.046, 0.043, 0.046]} />
          <group name="linees_34004" position={[-0.337, 0.033, 0.22]} rotation={[Math.PI / 2, 1.059, 0]} scale={[0.013, 0.023, 0.011]} />
          <group name="Mouth003" position={[-0.785, -0.424, 0.238]} rotation={[Math.PI, 0, 0]} scale={0.009} />
          <group name="Outer_Sphere_Chandelier004" position={[-0.349, 0.043, -0.091]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.046, 0.043, 0.046]} />
          <group name="Plane001_6002" position={[-0.021, 0.613, 0.217]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane002_7002" position={[-0.021, 0.608, 0.216]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane003_8002" position={[-0.021, 0.613, 0.22]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane004_9002" position={[-0.021, 0.611, 0.216]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane005_10002" position={[-0.021, 0.605, 0.218]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane006_11002" position={[-0.021, 0.614, 0.221]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane007_12002" position={[-0.021, 0.614, 0.218]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane008_13002" position={[-0.021, 0.606, 0.221]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane009_14002" position={[-0.021, 0.607, 0.218]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Plane_5002" position={[-0.021, 0.607, 0.22]} rotation={[-0.791, -0.119, -1.616]} scale={0} />
          <group name="Polygon_Reduction_1002" position={[-0.2, 0.438, -0.097]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
          <group name="rings001_1002" position={[-0.02, 0.555, 0.212]} rotation={[-2.293, 1.393, 0.735]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings002_2002" position={[-0.019, 0.552, 0.212]} rotation={[2.113, 1.345, 2.585]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings003_3002" position={[-0.02, 0.551, 0.214]} rotation={[-2.293, 1.393, 0.735]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings004_4002" position={[-0.018, 0.552, 0.215]} rotation={[2.113, 1.345, 2.585]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings005_0002" position={[-0.018, 0.555, 0.213]} rotation={[2.113, 1.345, 2.585]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings006_5002" position={[-0.019, 0.551, 0.216]} rotation={[-2.293, 1.393, 0.735]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings007_6002" position={[-0.02, 0.55, 0.217]} rotation={[2.113, 1.345, 2.585]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings008_7002" position={[-0.02, 0.55, 0.219]} rotation={[-2.293, 1.393, 0.735]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings009_8002" position={[-0.018, 0.55, 0.22]} rotation={[2.369, 1.41, 2.335]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings010_9002" position={[-0.02, 0.551, 0.22]} rotation={[-2.724, 1.445, 1.158]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings011_10002" position={[-0.017, 0.556, 0.22]} rotation={[-2.293, 1.393, 0.735]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings012_11002" position={[-0.019, 0.557, 0.22]} rotation={[2.113, 1.345, 2.585]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings013_12002" position={[-0.02, 0.557, 0.218]} rotation={[-2.293, 1.393, 0.735]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings014_13002" position={[-0.016, 0.556, 0.216]} rotation={[2.113, 1.345, 2.585]} scale={[0.002, 0.003, 0.005]} />
          <group name="rings015_14002" position={[-0.02, 0.556, 0.214]} rotation={[-2.293, 1.393, 0.735]} scale={[0.002, 0.003, 0.005]} />
          <group name="Robot_Origin002" position={[-0.785, -0.428, 0.26]} rotation={[Math.PI, 0, 0]} scale={0.009} />
          <group name="star001_19002" position={[-0.02, 0.553, 0.213]} rotation={[2.877, 1.454, 1.834]} scale={[0.002, 0.003, 0.005]} />
          <group name="star002_20002" position={[-0.02, 0.553, 0.212]} rotation={[2.877, 1.454, 1.834]} scale={[0.002, 0.003, 0.005]} />
          <group name="star003_21002" position={[-0.02, 0.554, 0.212]} rotation={[2.877, 1.454, 1.834]} scale={[0.002, 0.003, 0.005]} />
          <group name="star004_22002" position={[-0.02, 0.554, 0.213]} rotation={[2.877, 1.454, 1.834]} scale={[0.002, 0.003, 0.005]} />
          <group name="Wave005" position={[-0.785, -0.428, 0.259]} rotation={[Math.PI, 0, 0]} scale={[0.009, 0.009, 0.001]} />
          <group name="Wave006" position={[-0.785, -0.428, 0.253]} rotation={[Math.PI, 0, 0]} scale={[0.009, 0.009, 0.007]} />
          <group name="Wave007" position={[-0.785, -0.428, 0.256]} rotation={[Math.PI, 0, 0]} scale={[0.009, 0.009, 0.004]} />
          <group name="Wave012" position={[-0.785, -0.428, 0.251]} rotation={[Math.PI, 0, 0]} scale={0.009} />
        </group>
        <group name="Mesh_1001" position={[-9.697, 6.206, -17.329]} rotation={[-Math.PI / 2, 0, -1.571]} scale={0.045}>
          <group position={[-28.295, -1.307, -28.118]} scale={0.002}>
            <skinnedMesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={materials['Skin.002']} skeleton={nodes.mesh_1.skeleton} />
            <skinnedMesh name="mesh_1_1" geometry={nodes.mesh_1_1.geometry} material={materials['PaletteMaterial001.054']} skeleton={nodes.mesh_1_1.skeleton} />
          </group>
        </group>
        <group name="Mesh_2001" position={[-9.697, 6.206, -17.329]} rotation={[-Math.PI / 2, 0, -1.571]} scale={0.045}>
          <skinnedMesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={materials['Eyes.002']} skeleton={nodes.mesh_2.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_5001" position={[-21.469, 4.407, -14.875]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={materials['CH_NPC_Pig_MI_PJH.002']} skeleton={nodes.mesh_3.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_7001" position={[-21.469, 4.407, -14.875]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_4" geometry={nodes.mesh_4.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.002']} skeleton={nodes.mesh_4.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_8001" position={[-21.469, 4.407, -14.875]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_5" geometry={nodes.mesh_5.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.002']} skeleton={nodes.mesh_5.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_3001" position={[-21.481, 4.415, -14.596]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_6" geometry={nodes.mesh_6.geometry} material={materials['CH_NPC_Pig_MI_PJH.002']} skeleton={nodes.mesh_6.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_4001" position={[-21.481, 4.415, -14.596]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_7" geometry={nodes.mesh_7.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.002']} skeleton={nodes.mesh_7.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_6001" position={[-21.481, 4.415, -14.596]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_8" geometry={nodes.mesh_8.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.002']} skeleton={nodes.mesh_8.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_10001" position={[-21.687, 4.413, -14.606]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_9" geometry={nodes.mesh_9.geometry} material={materials['CH_NPC_Pig_MI_PJH.002']} skeleton={nodes.mesh_9.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_11001" position={[-21.687, 4.413, -14.606]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_10" geometry={nodes.mesh_10.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.002']} skeleton={nodes.mesh_10.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_12001" position={[-21.687, 4.413, -14.606]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_11" geometry={nodes.mesh_11.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.002']} skeleton={nodes.mesh_11.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_14001" position={[-21.675, 4.405, -14.885]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_12" geometry={nodes.mesh_12.geometry} material={materials['CH_NPC_Pig_MI_PJH.002']} skeleton={nodes.mesh_12.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_15001" position={[-21.675, 4.405, -14.885]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_13" geometry={nodes.mesh_13.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.002']} skeleton={nodes.mesh_13.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group name="Mesh_16001" position={[-21.675, 4.405, -14.885]} rotation={[-1.561, 0.001, -1.451]} scale={[0.008, 0.01, 0.014]}>
          <skinnedMesh name="mesh_14" geometry={nodes.mesh_14.geometry} material={materials['CH_NPC_Pig_Eyelash_PJH.002']} skeleton={nodes.mesh_14.skeleton} position={[-28.295, -1.307, -28.118]} scale={0.002} />
        </group>
        <group position={[-28.295, -1.307, -28.118]} scale={0.002}>
          <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials['lambert6SG.001']} />
          <mesh name="mesh_0_1" geometry={nodes.mesh_0_1.geometry} material={materials['lambert7SG.001']} />
          <mesh name="mesh_0_2" geometry={nodes.mesh_0_2.geometry} material={materials['blinn4SG.001']} />
          <mesh name="mesh_0_3" geometry={nodes.mesh_0_3.geometry} material={materials['Airlock.001']} />
          <mesh name="mesh_0_4" geometry={nodes.mesh_0_4.geometry} material={materials['AirPipe.001']} />
          <mesh name="mesh_0_5" geometry={nodes.mesh_0_5.geometry} material={materials['AmmoBox.001']} />
          <mesh name="mesh_0_6" geometry={nodes.mesh_0_6.geometry} material={materials['GameBoy.004']} />
          <mesh name="mesh_0_7" geometry={nodes.mesh_0_7.geometry} material={materials['bButton.004']} />
          <mesh name="mesh_0_8" geometry={nodes.mesh_0_8.geometry} material={materials['TT_checker_1024x1024_UV_GRID.008']} />
          <mesh name="mesh_0_9" geometry={nodes.mesh_0_9.geometry} material={materials['ARCADE.005']} />
          <mesh name="mesh_0_10" geometry={nodes.mesh_0_10.geometry} material={materials['PaletteMaterial002.016']} />
          <mesh name="mesh_0_11" geometry={nodes.mesh_0_11.geometry} material={materials['PaletteMaterial003.015']} />
          <mesh name="mesh_0_12" geometry={nodes.mesh_0_12.geometry} material={materials['PaletteMaterial001.032']} />
          <mesh name="mesh_0_13" geometry={nodes.mesh_0_13.geometry} material={materials['PaletteMaterial002.023']} />
          <mesh name="mesh_0_14" geometry={nodes.mesh_0_14.geometry} material={materials['PaletteMaterial002.024']} />
          <mesh name="mesh_0_15" geometry={nodes.mesh_0_15.geometry} material={materials['Stick.004']} />
          <mesh name="mesh_0_16" geometry={nodes.mesh_0_16.geometry} material={materials['lowpoly.004']} />
          <mesh name="mesh_0_17" geometry={nodes.mesh_0_17.geometry} material={materials['GamepadStuff.005']} />
          <mesh name="mesh_0_18" geometry={nodes.mesh_0_18.geometry} material={materials['gamepadMain.005']} />
          <mesh name="mesh_0_19" geometry={nodes.mesh_0_19.geometry} material={materials['PaletteMaterial003.016']} />
          <mesh name="mesh_0_20" geometry={nodes.mesh_0_20.geometry} material={materials['TT_checker_1024x1024_UV_GRID.009']} />
          <mesh name="mesh_0_21" geometry={nodes.mesh_0_21.geometry} material={materials['PaletteMaterial004.011']} />
          <mesh name="mesh_0_22" geometry={nodes.mesh_0_22.geometry} material={materials['controllerbody.004']} />
          <mesh name="mesh_0_23" geometry={nodes.mesh_0_23.geometry} material={materials['material.011']} />
          <mesh name="mesh_0_24" geometry={nodes.mesh_0_24.geometry} material={materials['ANALOG.004']} />
          <mesh name="mesh_0_25" geometry={nodes.mesh_0_25.geometry} material={materials['dpad.004']} />
          <mesh name="mesh_0_26" geometry={nodes.mesh_0_26.geometry} material={materials['cstick.004']} />
          <mesh name="mesh_0_27" geometry={nodes.mesh_0_27.geometry} material={materials['startbutton.002']} />
          <mesh name="mesh_0_28" geometry={nodes.mesh_0_28.geometry} material={materials['abutton.004']} />
          <mesh name="mesh_0_29" geometry={nodes.mesh_0_29.geometry} material={materials['zbutton.004']} />
          <mesh name="mesh_0_30" geometry={nodes.mesh_0_30.geometry} material={materials['bumpers.004']} />
          <mesh name="mesh_0_31" geometry={nodes.mesh_0_31.geometry} material={materials['PaletteMaterial001.033']} />
          <mesh name="mesh_0_32" geometry={nodes.mesh_0_32.geometry} material={materials['baloon.002']} />
          <mesh name="mesh_0_33" geometry={nodes.mesh_0_33.geometry} material={materials['baloon.005']} />
          <mesh name="mesh_0_34" geometry={nodes.mesh_0_34.geometry} material={materials['BedFrame.001']} />
          <mesh name="mesh_0_35" geometry={nodes.mesh_0_35.geometry} material={materials['BedFabrics.001']} />
          <mesh name="mesh_0_36" geometry={nodes.mesh_0_36.geometry} material={materials['CeillingLamp.001']} />
          <mesh name="mesh_0_37" geometry={nodes.mesh_0_37.geometry} material={materials['Chair.001']} />
          <mesh name="mesh_0_38" geometry={nodes.mesh_0_38.geometry} material={materials['ChairMetal.001']} />
          <mesh name="mesh_0_39" geometry={nodes.mesh_0_39.geometry} material={materials['ChineseSoldier.001']} />
          <mesh name="mesh_0_40" geometry={nodes.mesh_0_40.geometry} material={materials['PaletteMaterial007.007']} />
          <mesh name="mesh_0_41" geometry={nodes.mesh_0_41.geometry} material={materials['PaletteMaterial008.006']} />
          <mesh name="mesh_0_42" geometry={nodes.mesh_0_42.geometry} material={materials['PaletteMaterial001.047']} />
          <mesh name="mesh_0_43" geometry={nodes.mesh_0_43.geometry} material={materials['PaletteMaterial004.012']} />
          <mesh name="mesh_0_44" geometry={nodes.mesh_0_44.geometry} material={materials['PaletteMaterial005.015']} />
          <mesh name="mesh_0_45" geometry={nodes.mesh_0_45.geometry} material={materials['PaletteMaterial006.007']} />
          <mesh name="mesh_0_46" geometry={nodes.mesh_0_46.geometry} material={materials['PaletteMaterial003.017']} />
          <mesh name="mesh_0_47" geometry={nodes.mesh_0_47.geometry} material={materials['PaletteMaterial002.025']} />
          <mesh name="mesh_0_48" geometry={nodes.mesh_0_48.geometry} material={materials['02_-_Default.002']} />
          <mesh name="mesh_0_49" geometry={nodes.mesh_0_49.geometry} material={materials['04_-_Default.002']} />
          <mesh name="mesh_0_50" geometry={nodes.mesh_0_50.geometry} material={materials['05_-_Default.002']} />
          <mesh name="mesh_0_51" geometry={nodes.mesh_0_51.geometry} material={materials['DecorativePanels.001']} />
          <mesh name="mesh_0_52" geometry={nodes.mesh_0_52.geometry} material={materials['Door.001']} />
          <mesh name="mesh_0_53" geometry={nodes.mesh_0_53.geometry} material={materials['Ventilation.001']} />
          <mesh name="mesh_0_54" geometry={nodes.mesh_0_54.geometry} material={materials['Material.018']} />
          <mesh name="mesh_0_55" geometry={nodes.mesh_0_55.geometry} material={materials['Material.019']} />
          <mesh name="mesh_0_56" geometry={nodes.mesh_0_56.geometry} material={materials['PaletteMaterial005.016']} />
          <mesh name="mesh_0_57" geometry={nodes.mesh_0_57.geometry} material={materials['PaletteMaterial006.009']} />
          <mesh name="mesh_0_58" geometry={nodes.mesh_0_58.geometry} material={materials['Keyboard.001']} />
          <mesh name="mesh_0_59" geometry={nodes.mesh_0_59.geometry} material={materials['VentLeder.001']} />
          <mesh name="mesh_0_60" geometry={nodes.mesh_0_60.geometry} material={materials['MonitorMouse.001']} />
          <mesh name="mesh_0_61" geometry={nodes.mesh_0_61.geometry} material={materials['forMayaAOnumber.002']} />
          <mesh name="mesh_0_62" geometry={nodes.mesh_0_62.geometry} material={materials['forMayaAOlambert15.002']} />
          <mesh name="mesh_0_63" geometry={nodes.mesh_0_63.geometry} material={materials['forMayaAOlambert16.002']} />
          <mesh name="mesh_0_64" geometry={nodes.mesh_0_64.geometry} material={materials['forMayaAOblinn6.002']} />
          <mesh name="mesh_0_65" geometry={nodes.mesh_0_65.geometry} material={materials['PaletteMaterial010.004']} />
          <mesh name="mesh_0_66" geometry={nodes.mesh_0_66.geometry} material={materials['forMayaAOGrill2.002']} />
          <mesh name="mesh_0_67" geometry={nodes.mesh_0_67.geometry} material={materials['Chrome_2.002']} />
          <mesh name="mesh_0_68" geometry={nodes.mesh_0_68.geometry} material={materials['forMayaAOrear_lights.002']} />
          <mesh name="mesh_0_69" geometry={nodes.mesh_0_69.geometry} material={materials['PaletteMaterial011.002']} />
          <mesh name="mesh_0_70" geometry={nodes.mesh_0_70.geometry} material={materials['material.012']} />
          <mesh name="mesh_0_71" geometry={nodes.mesh_0_71.geometry} material={materials['PaletteMaterial001.049']} />
          <mesh name="mesh_0_72" geometry={nodes.mesh_0_72.geometry} material={materials['Tassels.002']} />
          <mesh name="mesh_0_73" geometry={nodes.mesh_0_73.geometry} material={materials['PaletteMaterial001.050']} />
          <mesh name="mesh_0_74" geometry={nodes.mesh_0_74.geometry} material={materials['Material.020']} />
          <mesh name="mesh_0_75" geometry={nodes.mesh_0_75.geometry} material={materials['Glass.003']} />
          <mesh name="mesh_0_76" geometry={nodes.mesh_0_76.geometry} material={materials['PaletteMaterial001.051']} />
          <mesh name="mesh_0_77" geometry={nodes.mesh_0_77.geometry} material={materials['PaletteMaterial002.026']} />
          <mesh name="mesh_0_78" geometry={nodes.mesh_0_78.geometry} material={materials['PaletteMaterial004.013']} />
          <mesh name="mesh_0_79" geometry={nodes.mesh_0_79.geometry} material={materials['PaletteMaterial005.017']} />
          <mesh name="mesh_0_80" geometry={nodes.mesh_0_80.geometry} material={materials['PaletteMaterial006.010']} />
          <mesh name="mesh_0_81" geometry={nodes.mesh_0_81.geometry} material={materials['PaletteMaterial007.008']} />
          <mesh name="mesh_0_82" geometry={nodes.mesh_0_82.geometry} material={materials['PaletteMaterial008.007']} />
          <mesh name="mesh_0_83" geometry={nodes.mesh_0_83.geometry} material={materials['PaletteMaterial009.004']} />
          <mesh name="mesh_0_84" geometry={nodes.mesh_0_84.geometry} material={materials['PaletteMaterial010.005']} />
          <mesh name="mesh_0_85" geometry={nodes.mesh_0_85.geometry} material={materials['Material.021']} />
          <mesh name="mesh_0_86" geometry={nodes.mesh_0_86.geometry} material={materials['SVGMat.003']} />
          <mesh name="mesh_0_87" geometry={nodes.mesh_0_87.geometry} material={materials['Material.022']} />
          <mesh name="mesh_0_88" geometry={nodes.mesh_0_88.geometry} material={materials['default.002']} />
          <mesh name="mesh_0_89" geometry={nodes.mesh_0_89.geometry} material={materials['PaletteMaterial012.002']} />
          <mesh name="mesh_0_90" geometry={nodes.mesh_0_90.geometry} material={materials['christmas_tree.002']} />
          <mesh name="mesh_0_91" geometry={nodes.mesh_0_91.geometry} material={materials['equalizer.004']} />
          <mesh name="mesh_0_92" geometry={nodes.mesh_0_92.geometry} material={materials['Material.024']} />
          <mesh name="mesh_0_93" geometry={nodes.mesh_0_93.geometry} material={materials['PaletteMaterial001.048']} />
          <mesh name="mesh_0_94" geometry={nodes.mesh_0_94.geometry} material={materials['material_0.002']} />
          <mesh name="mesh_0_95" geometry={nodes.mesh_0_95.geometry} material={materials['M_Bake.002']} />
          <mesh name="mesh_0_96" geometry={nodes.mesh_0_96.geometry} material={materials['PaletteMaterial008.008']} />
          <mesh name="mesh_0_97" geometry={nodes.mesh_0_97.geometry} material={materials['PaletteMaterial009.005']} />
          <mesh name="mesh_0_98" geometry={nodes.mesh_0_98.geometry} material={materials['blackFabric.005']} />
          <mesh name="mesh_0_99" geometry={nodes.mesh_0_99.geometry} material={materials['frontColor.004']} />
          <mesh name="mesh_0_100" geometry={nodes.mesh_0_100.geometry} material={materials['blackInternal.005']} />
          <mesh name="mesh_0_101" geometry={nodes.mesh_0_101.geometry} material={materials['OfficeChair.001']} />
          <mesh name="mesh_0_102" geometry={nodes.mesh_0_102.geometry} material={materials['Tables.001']} />
          <mesh name="mesh_0_103" geometry={nodes.mesh_0_103.geometry} material={materials['PaletteMaterial007.009']} />
          <mesh name="mesh_0_104" geometry={nodes.mesh_0_104.geometry} material={materials['Papers.001']} />
          <mesh name="mesh_0_105" geometry={nodes.mesh_0_105.geometry} material={materials['PistolTrigger.002']} />
          <mesh name="mesh_0_106" geometry={nodes.mesh_0_106.geometry} material={materials['PistolBody.002']} />
          <mesh name="mesh_0_107" geometry={nodes.mesh_0_107.geometry} material={materials['PistolRings.002']} />
          <mesh name="mesh_0_108" geometry={nodes.mesh_0_108.geometry} material={materials['Pipe.001']} />
          <mesh name="mesh_0_109" geometry={nodes.mesh_0_109.geometry} material={materials['Plant.001']} />
          <mesh name="mesh_0_110" geometry={nodes.mesh_0_110.geometry} material={materials['Material_0.002']} />
          <mesh name="mesh_0_111" geometry={nodes.mesh_0_111.geometry} material={materials['MeditationSanta_Model_9_u1_v1.002']} />
          <mesh name="mesh_0_112" geometry={nodes.mesh_0_112.geometry} material={materials['material_0.004']} />
          <mesh name="mesh_0_113" geometry={nodes.mesh_0_113.geometry} material={materials['material.013']} />
          <mesh name="mesh_0_114" geometry={nodes.mesh_0_114.geometry} material={materials['Sticker_SPC-SG.004']} />
          <mesh name="mesh_0_115" geometry={nodes.mesh_0_115.geometry} material={materials['baked.004']} />
          <mesh name="mesh_0_116" geometry={nodes.mesh_0_116.geometry} material={materials['RubixCube.004']} />
          <mesh name="mesh_0_117" geometry={nodes.mesh_0_117.geometry} material={materials['PaletteMaterial005.018']} />
          <mesh name="mesh_0_118" geometry={nodes.mesh_0_118.geometry} material={materials['Mtl2.004']} />
          <mesh name="mesh_0_119" geometry={nodes.mesh_0_119.geometry} material={materials['material.014']} />
          <mesh name="mesh_0_120" geometry={nodes.mesh_0_120.geometry} material={materials['PaletteMaterial002.027']} />
          <mesh name="mesh_0_121" geometry={nodes.mesh_0_121.geometry} material={materials['Glass.005']} />
          <mesh name="mesh_0_122" geometry={nodes.mesh_0_122.geometry} material={materials['PaletteMaterial003.018']} />
          <mesh name="mesh_0_123" geometry={nodes.mesh_0_123.geometry} material={materials['PaletteMaterial004.014']} />
          <mesh name="mesh_0_124" geometry={nodes.mesh_0_124.geometry} material={materials['PaletteMaterial005.019']} />
          <mesh name="mesh_0_125" geometry={nodes.mesh_0_125.geometry} material={materials['Sofa.001']} />
          <mesh name="mesh_0_126" geometry={nodes.mesh_0_126.geometry} material={materials['material_0.006']} />
          <mesh name="mesh_0_127" geometry={nodes.mesh_0_127.geometry} material={materials['Camera.001']} />
          <mesh name="mesh_0_128" geometry={nodes.mesh_0_128.geometry} material={materials['Walls.001']} />
          <mesh name="mesh_0_129" geometry={nodes.mesh_0_129.geometry} material={materials['PaletteMaterial001.053']} />
          <mesh name="mesh_0_130" geometry={nodes.mesh_0_130.geometry} material={materials.Material} />
        </group>
      </group>
    </group>
  )
}

