/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 RoomDisplayOne.glb --types 
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

// Define the types for your GLTF model
type GLTFResult = GLTF & {
  nodes: {
    Object_0012: THREE.Mesh;
    Object_0012_1: THREE.Mesh;
    Object_0012_2: THREE.Mesh;
    Object_0012_3: THREE.Mesh;
    Object_0012_4: THREE.Mesh;
    Object_0012_5: THREE.Mesh;
    Object_0012_6: THREE.Mesh;
    Object_0012_7: THREE.Mesh;
    Object_0012_8: THREE.Mesh;
    Object_0012_9: THREE.Mesh;
    Object_0012_10: THREE.Mesh;
    Object_0012_11: THREE.Mesh;
    Object_0012_12: THREE.Mesh;
    Object_0012_13: THREE.Mesh;
    Object_0012_14: THREE.Mesh;
    Object_0012_15: THREE.Mesh;
    Object_0012_16: THREE.Mesh;
    Object_0012_17: THREE.Mesh;
    Object_0012_18: THREE.Mesh;
    Object_0012_19: THREE.Mesh;
    Object_0012_20: THREE.Mesh;
    Object_0012_21: THREE.Mesh;
    Object_0012_22: THREE.Mesh;
    Object_0012_23: THREE.Mesh;
    Object_0012_24: THREE.Mesh;
    Object_0012_25: THREE.Mesh;
    Object_0012_26: THREE.Mesh;
    Object_0012_27: THREE.Mesh;
    Object_0012_28: THREE.Mesh;
    Object_0012_29: THREE.Mesh;
    Object_0012_30: THREE.Mesh;
    Object_0012_31: THREE.Mesh;
    Object_0012_32: THREE.Mesh;
    Object_0012_33: THREE.Mesh;
    Object_0012_34: THREE.Mesh;
    Object_0012_35: THREE.Mesh;
    Object_0012_36: THREE.Mesh;
    Object_0012_37: THREE.Mesh;
    Object_0012_38: THREE.Mesh;
    Object_0012_39: THREE.Mesh;
    Object_0012_40: THREE.Mesh;
    Object_0012_41: THREE.Mesh;
    Object_0012_42: THREE.Mesh;
    Object_0012_43: THREE.Mesh;
    Object_0012_44: THREE.Mesh;
    Object_0012_45: THREE.Mesh;
  };
  materials: {
    lambert7SG: THREE.MeshStandardMaterial;
    blinn4SG: THREE.MeshPhysicalMaterial;
    lambert6SG: THREE.MeshStandardMaterial;
    TT_checker_1024x1024_UV_GRID: THREE.MeshStandardMaterial;
    ['ARCADE.002']: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    ['PaletteMaterial003.003']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.015']: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.008']: THREE.MeshStandardMaterial;
    ['PaletteMaterial003.006']: THREE.MeshBasicMaterial;
    Stick: THREE.MeshStandardMaterial;
    GameBoy: THREE.MeshStandardMaterial;
    lowpoly: THREE.MeshStandardMaterial;
    ['GamepadStuff.001']: THREE.MeshStandardMaterial;
    ['gamepadMain.001']: THREE.MeshStandardMaterial;
    ['Sticker_SPC-SG']: THREE.MeshStandardMaterial;
    baked: THREE.MeshStandardMaterial;
    RubixCube: THREE.MeshStandardMaterial;
    ['PaletteMaterial005.003']: THREE.MeshStandardMaterial;
    ['TT_checker_1024x1024_UV_GRID.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial006.003']: THREE.MeshPhysicalMaterial;
    controllerbody: THREE.MeshStandardMaterial;
    ['material.002']: THREE.MeshStandardMaterial;
    ANALOG: THREE.MeshStandardMaterial;
    dpad: THREE.MeshStandardMaterial;
    cstick: THREE.MeshStandardMaterial;
    startbutton: THREE.MeshStandardMaterial;
    abutton: THREE.MeshStandardMaterial;
    zbutton: THREE.MeshStandardMaterial;
    bumpers: THREE.MeshStandardMaterial;
    bButton: THREE.MeshStandardMaterial;
    ['PaletteMaterial002.009']: THREE.MeshPhysicalMaterial;
    Mtl2: THREE.MeshStandardMaterial;
    ['material.003']: THREE.MeshStandardMaterial;
    ['PaletteMaterial004.004']: THREE.MeshStandardMaterial;
    equalizer: THREE.MeshStandardMaterial;
    frontColor: THREE.MeshStandardMaterial;
    ['PaletteMaterial007.002']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial008.002']: THREE.MeshPhysicalMaterial;
    ['PaletteMaterial005.005']: THREE.MeshStandardMaterial;
    ['PaletteMaterial009.001']: THREE.MeshStandardMaterial;
    ['blackFabric.001']: THREE.MeshStandardMaterial;
    ['blackInternal.001']: THREE.MeshStandardMaterial;
    ['PaletteMaterial010.001']: THREE.MeshPhysicalMaterial;
    ['Material.014']: THREE.MeshStandardMaterial;
    ['PaletteMaterial001.017']: THREE.MeshStandardMaterial;
  };
};

// Define the available actions in the GLTF model for type safety
type ActionName =
  | 'Animation'
  | 'Armature.004|Armature.004Action'
  | 'Turn_Object_707'
  | 'Main'
  | 'sound wave';

// Define a type for the actions using Record
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

// Export the main component
export function RoomDisplayOne(props: JSX.IntrinsicElements['group']) {
  // Initialize useRef with null and update the type accordingly
  const group = useRef<THREE.Group | null>(null);

  // Load the GLTF model and cast it to GLTFResult for type safety
  const { nodes, materials, animations } = useGLTF(
    'https://racho-devs.s3.us-east-2.amazonaws.com/roomV2/desktop/oldRooms/RoomDisplayOne.glb'
  ) as GLTFResult;

  // Use useAnimations without specifying a generic parameter
  // Then, cast the actions to GLTFActions for type safety
  const { actions } = useAnimations(animations, group);
  // Cast actions to GLTFActions for type safety
  const typedActions = actions as unknown as GLTFActions;

  // Use useEffect to play all animations when the component mounts
  // Control animations using useEffect
  useEffect(() => {
    // Play all defined animations when the component mounts
    Object.values(typedActions).forEach((action) => action.play());

    // Cleanup: Stop all animations when the component unmounts
    return () => {
      Object.values(typedActions).forEach((action) => action.stop());
    };
  }, [typedActions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="RachosRoomOG">
        <group
          name="RoomDisplayOne"
          position={[-10.895, 0.65, -3.918]}
          scale={0.062}
        >
          <group
            name="baseCover001_0"
            position={[13.871, 75.646, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.553, 7.449, 3.746]}
          />
          <group
            name="Bone008_09001"
            position={[99.798, 446.972, -445.692]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.235}
          />
          <group
            name="Bone014_015001"
            position={[109.096, 443.797, -436.314]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.235}
          />
          <group
            name="Bone015_016001"
            position={[102.949, 443.797, -436.314]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.235}
          />
          <group
            name="circle001"
            position={[-61.686, 205.455, -176.423]}
            scale={[22.267, 20.675, 22.057]}
          />
          <group
            name="Circle001_11"
            position={[15.9, 32.076, 0]}
            rotation={[0, -0.827, Math.PI / 2]}
            scale={4.535}
          />
          <group
            name="Circle003_13"
            position={[15.9, 9.613, 0]}
            rotation={[0, -0.827, Math.PI / 2]}
            scale={4.535}
          />
          <group
            name="Circle005_16"
            position={[15.9, 32.076, -70.597]}
            rotation={[0, -0.827, Math.PI / 2]}
            scale={4.535}
          />
          <group
            name="Circle007_18"
            position={[15.9, 9.613, -70.597]}
            rotation={[0, -0.827, Math.PI / 2]}
            scale={4.535}
          />
          <group
            name="Circle009_4"
            position={[14.301, 4.875, -46.53]}
            rotation={[0, -0.827, Math.PI / 2]}
            scale={3.729}
          />
          <group
            name="Circle011_1"
            position={[14.301, 4.875, -24.067]}
            rotation={[0, -0.827, Math.PI / 2]}
            scale={3.729}
          />
          <group
            name="Circle013_7"
            position={[14.301, 21.818, -35.298]}
            rotation={[0, -0.827, Math.PI / 2]}
            scale={3.729}
          />
          <group
            name="circle2001"
            position={[-61.686, 205.455, -176.423]}
            scale={[22.267, 20.675, 22.057]}
          />
          <group
            name="equalizer_35"
            position={[13.871, 68.227, -98.518]}
            rotation={[0, 0.717, 0]}
            scale={[4.452, 4.129, 3.664]}
          />
          <group
            name="glass_1"
            position={[13.871, 68.227, -98.518]}
            rotation={[0, 0.717, 0]}
            scale={[4.452, 4.129, 3.664]}
          />
          <group
            name="indicator10_3"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 1.327, 3.664]}
          />
          <group
            name="indicator11_4"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 6.365, 3.664]}
          />
          <group
            name="indicator12_5"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 4.646, 3.664]}
          />
          <group
            name="indicator13_6"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 3.267, 3.664]}
          />
          <group
            name="indicator14_7"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 1.802, 3.664]}
          />
          <group
            name="indicator15_8"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 4.941, 3.664]}
          />
          <group
            name="indicator16_9"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 1.702, 3.664]}
          />
          <group
            name="indicator17_10"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 5.577, 3.664]}
          />
          <group
            name="indicator18_11"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 2.558, 3.664]}
          />
          <group
            name="indicator19_12"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 3.935, 3.664]}
          />
          <group
            name="indicator1_2"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 1.2, 3.664]}
          />
          <group
            name="indicator20_14"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 2.277, 3.664]}
          />
          <group
            name="indicator21_15"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 6.375, 3.664]}
          />
          <group
            name="indicator22_16"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 7.074, 3.664]}
          />
          <group
            name="indicator23_17"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 3.533, 3.664]}
          />
          <group
            name="indicator24_18"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 4.962, 3.664]}
          />
          <group
            name="indicator25_19"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 4.663, 3.664]}
          />
          <group
            name="indicator26_20"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 3.411, 3.664]}
          />
          <group
            name="indicator27_21"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 1.544, 3.664]}
          />
          <group
            name="indicator28_22"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 3.496, 3.664]}
          />
          <group
            name="indicator29_23"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 4.281, 3.664]}
          />
          <group
            name="indicator2_13"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 6, 3.664]}
          />
          <group
            name="indicator30_25"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 5.623, 3.664]}
          />
          <group
            name="indicator31_26"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 4.296, 3.664]}
          />
          <group
            name="indicator32_27"
            position={[13.871, 68.268, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 3.818, 3.664]}
          />
          <group
            name="indicator3_24"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 7.42, 3.664]}
          />
          <group
            name="indicator4_28"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 2.954, 3.664]}
          />
          <group
            name="indicator5_29"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 6.469, 3.664]}
          />
          <group
            name="indicator6_30"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 4.256, 3.664]}
          />
          <group
            name="indicator7_31"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 7.313, 3.664]}
          />
          <group
            name="indicator8_32"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 2.439, 3.664]}
          />
          <group
            name="indicator9_33"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.452, 2.165, 3.664]}
          />
          <group
            name="Inner_Sphere_Chandelier"
            position={[-61.686, 205.455, -176.423]}
            scale={[22.267, 20.675, 22.057]}
          />
          <group
            name="linees_34"
            position={[13.871, 68.227, -98.518]}
            rotation={[-Math.PI, -0.717, 0]}
            scale={[4.408, 7.432, 3.627]}
          />
          <group
            name="Outer_Sphere_Chandelier"
            position={[-61.686, 205.455, -176.423]}
            scale={[22.267, 20.675, 22.057]}
          />
          <group position={[-62.698, 117.64, -129.843]} scale={258.439}>
            <mesh
              name="Object_0012"
              geometry={nodes.Object_0012.geometry}
              material={materials.lambert7SG}
            />
            <mesh
              name="Object_0012_1"
              geometry={nodes.Object_0012_1.geometry}
              material={materials.blinn4SG}
            />
            <mesh
              name="Object_0012_2"
              geometry={nodes.Object_0012_2.geometry}
              material={materials.lambert6SG}
            />
            <mesh
              name="Object_0012_3"
              geometry={nodes.Object_0012_3.geometry}
              material={materials.TT_checker_1024x1024_UV_GRID}
            />
            <mesh
              name="Object_0012_4"
              geometry={nodes.Object_0012_4.geometry}
              material={materials['ARCADE.002']}
            />
            <mesh
              name="Object_0012_5"
              geometry={nodes.Object_0012_5.geometry}
              material={materials.PaletteMaterial002}
            />
            <mesh
              name="Object_0012_6"
              geometry={nodes.Object_0012_6.geometry}
              material={materials['PaletteMaterial003.003']}
            />
            <mesh
              name="Object_0012_7"
              geometry={nodes.Object_0012_7.geometry}
              material={materials['PaletteMaterial001.015']}
            />
            <mesh
              name="Object_0012_8"
              geometry={nodes.Object_0012_8.geometry}
              material={materials['PaletteMaterial002.008']}
            />
            <mesh
              name="Object_0012_9"
              geometry={nodes.Object_0012_9.geometry}
              material={materials['PaletteMaterial003.006']}
            />
            <mesh
              name="Object_0012_10"
              geometry={nodes.Object_0012_10.geometry}
              material={materials.Stick}
            />
            <mesh
              name="Object_0012_11"
              geometry={nodes.Object_0012_11.geometry}
              material={materials.GameBoy}
            />
            <mesh
              name="Object_0012_12"
              geometry={nodes.Object_0012_12.geometry}
              material={materials.lowpoly}
            />
            <mesh
              name="Object_0012_13"
              geometry={nodes.Object_0012_13.geometry}
              material={materials['GamepadStuff.001']}
            />
            <mesh
              name="Object_0012_14"
              geometry={nodes.Object_0012_14.geometry}
              material={materials['gamepadMain.001']}
            />
            <mesh
              name="Object_0012_15"
              geometry={nodes.Object_0012_15.geometry}
              material={materials['Sticker_SPC-SG']}
            />
            <mesh
              name="Object_0012_16"
              geometry={nodes.Object_0012_16.geometry}
              material={materials.baked}
            />
            <mesh
              name="Object_0012_17"
              geometry={nodes.Object_0012_17.geometry}
              material={materials.RubixCube}
            />
            <mesh
              name="Object_0012_18"
              geometry={nodes.Object_0012_18.geometry}
              material={materials['PaletteMaterial005.003']}
            />
            <mesh
              name="Object_0012_19"
              geometry={nodes.Object_0012_19.geometry}
              material={materials['TT_checker_1024x1024_UV_GRID.001']}
            />
            <mesh
              name="Object_0012_20"
              geometry={nodes.Object_0012_20.geometry}
              material={materials['PaletteMaterial006.003']}
            />
            <mesh
              name="Object_0012_21"
              geometry={nodes.Object_0012_21.geometry}
              material={materials.controllerbody}
            />
            <mesh
              name="Object_0012_22"
              geometry={nodes.Object_0012_22.geometry}
              material={materials['material.002']}
            />
            <mesh
              name="Object_0012_23"
              geometry={nodes.Object_0012_23.geometry}
              material={materials.ANALOG}
            />
            <mesh
              name="Object_0012_24"
              geometry={nodes.Object_0012_24.geometry}
              material={materials.dpad}
            />
            <mesh
              name="Object_0012_25"
              geometry={nodes.Object_0012_25.geometry}
              material={materials.cstick}
            />
            <mesh
              name="Object_0012_26"
              geometry={nodes.Object_0012_26.geometry}
              material={materials.startbutton}
            />
            <mesh
              name="Object_0012_27"
              geometry={nodes.Object_0012_27.geometry}
              material={materials.abutton}
            />
            <mesh
              name="Object_0012_28"
              geometry={nodes.Object_0012_28.geometry}
              material={materials.zbutton}
            />
            <mesh
              name="Object_0012_29"
              geometry={nodes.Object_0012_29.geometry}
              material={materials.bumpers}
            />
            <mesh
              name="Object_0012_30"
              geometry={nodes.Object_0012_30.geometry}
              material={materials.bButton}
            />
            <mesh
              name="Object_0012_31"
              geometry={nodes.Object_0012_31.geometry}
              material={materials['PaletteMaterial002.009']}
            />
            <mesh
              name="Object_0012_32"
              geometry={nodes.Object_0012_32.geometry}
              material={materials.Mtl2}
            />
            <mesh
              name="Object_0012_33"
              geometry={nodes.Object_0012_33.geometry}
              material={materials['material.003']}
            />
            <mesh
              name="Object_0012_34"
              geometry={nodes.Object_0012_34.geometry}
              material={materials['PaletteMaterial004.004']}
            />
            <mesh
              name="Object_0012_35"
              geometry={nodes.Object_0012_35.geometry}
              material={materials.equalizer}
            />
            <mesh
              name="Object_0012_36"
              geometry={nodes.Object_0012_36.geometry}
              material={materials.frontColor}
            />
            <mesh
              name="Object_0012_37"
              geometry={nodes.Object_0012_37.geometry}
              material={materials['PaletteMaterial007.002']}
            />
            <mesh
              name="Object_0012_38"
              geometry={nodes.Object_0012_38.geometry}
              material={materials['PaletteMaterial008.002']}
            />
            <mesh
              name="Object_0012_39"
              geometry={nodes.Object_0012_39.geometry}
              material={materials['PaletteMaterial005.005']}
            />
            <mesh
              name="Object_0012_40"
              geometry={nodes.Object_0012_40.geometry}
              material={materials['PaletteMaterial009.001']}
            />
            <mesh
              name="Object_0012_41"
              geometry={nodes.Object_0012_41.geometry}
              material={materials['blackFabric.001']}
            />
            <mesh
              name="Object_0012_42"
              geometry={nodes.Object_0012_42.geometry}
              material={materials['blackInternal.001']}
            />
            <mesh
              name="Object_0012_43"
              geometry={nodes.Object_0012_43.geometry}
              material={materials['PaletteMaterial010.001']}
            />
            <mesh
              name="Object_0012_44"
              geometry={nodes.Object_0012_44.geometry}
              material={materials['Material.014']}
            />
            <mesh
              name="Object_0012_45"
              geometry={nodes.Object_0012_45.geometry}
              material={materials['PaletteMaterial001.017']}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
